### DISCUSSION TITLE
Is it possible to use prefix-classes with "Root Reference" (/)?

### DISCUSSION THREAD

**Discussion by jt3k** [stylus/stylus#2619] [Ideas]
When I apply the prefix, then I can not use the slash

eg:
```styl
+prefix-classes('prefix-')
  .lalala
    lololo hohoho
    /.ie7 &
      zoom  1

```
gives me
```css
.prefix-lalala {
  lololo: hohoho;
}
.prefix-ie7 .prefix-lalala {
  zoom: 1;
}
```

but I expected
```css
.prefix-lalala {
  lololo: hohoho;
}
.ie7 .prefix-lalala {
  zoom: 1;
}
```
How to reach goal ?
