### DISCUSSION TITLE
Support container queries

### DISCUSSION THREAD

**Discussion by TokugawaTakeshi** [stylus/stylus#2727] [Ideas]
The browsers begins to support the [query container feature](https://www.ishadeed.com/article/container-queries-are-finally-here/). Below image is actual for September of 2022.

![image](https://user-images.githubusercontent.com/41653501/190946542-51cef7da-e642-4a5c-96b6-fddfbc4c9573.png)

[🌎 caniuse.com](https://caniuse.com/css-container-queries)

Currently, if we write

```stylus
.ToDosListPage

  font-size initial

  @container (min-width: 700px)

    background aliceblue
```

we'll get

```css
.ToDosListPage {
  font-size: initial;
}

@container (min-width: 700px) {
  background: #f0f8ff;
}
```

I dare to hope you will not ignore this very waited feature.

**Comment by iChenLei** [comment]
[MDN's @container example](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries#the_container_queries_proposal) work as expected.

![2022-09-19 13 24 45](https://user-images.githubusercontent.com/14012511/190954232-ff0316a3-a914-46a4-9262-924368edba85.png)

**Reply by TokugawaTakeshi** [reply]
Thank you for the answer. 
You right, the pattern when `@container` going as parent works correctly.
However, could `@container`  works as `@media` when it going not at root?

For example:

```stylus
.MainLayout

  display grid


  @media screen and (min-width: 500px)

    grid-template-columns auto minmax(0, 1fr)


  @media screen and (max-width: 499px)

    grid-template-columns 0 minmax(0, 1fr)
```

will be compiled to:

```css
.MainLayout {
  display: grid;
}
@media screen and (min-width: 500px) {
  .MainLayout {
    grid-template-columns: auto minmax(0, 1fr);
  }
}
@media screen and (max-width: 499px) {
  .MainLayout {
    grid-template-columns: 0 minmax(0, 1fr);
  }
}
```

while

```stylus
.MainLayout

  display grid


  @container (min-width: 500px)

    grid-template-columns auto minmax(0, 1fr)
```

to:

```css
.MainLayout {
  display: grid;
}
@container (min-width: 500px) {
  grid-template-columns: auto minmax(0, 1fr);
}
```

Would you please to make Stylus output

```css
.MainLayout {
  display: grid;
}
@container (min-width: 500px) {
  .MainLayout {
    grid-template-columns: auto minmax(0, 1fr);
  }
}
```

instead?
