### DISCUSSION TITLE
How can i change style "style only element"

### DISCUSSION THREAD

**Discussion by CRC32EX** [stylus/stylus#2759] [Q&A] [answered]
# Target HTML
![image](https://user-images.githubusercontent.com/25629617/219827829-73bac020-268d-404a-a8f7-d78283b9b7bd.png)

div element don't have `id` `name` `class` .
div element don't have any identifer.

**index.html**
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div style="background-color: green">
      Text001
    </div>

    <div style="background-color: gray">
      Text002
    </div>
  </body>
</html>
```

# What i tried
```css
div {
  background-color: red !important;
}
```

`background-color` changed successfully.
But, I don't want change `Text002` background-color.
I want change `Text001` only.

![image](https://user-images.githubusercontent.com/25629617/219827836-e4cfd54e-542c-4fa1-a302-6f4c06759318.png)

# Question
I want write Stylus like this.
But it's not working.
I don't know how to do it.

```css
div (if [background-color == 'green']) {
  background-color: red !important;
}
```
