### DISCUSSION TITLE
Is there even a way to use data-theme with stylus?

### DISCUSSION THREAD

**Discussion by AndresMpa** [stylus/stylus#2823] [Q&A] [answered]
I spent 6 hours looking for the correct way to make this with stylus, but I didn't got any good idea:

```css
:root {
  --main: #0f0f0f;
  --letter: snow;
}

[data-theme="light"] {
  --main: snow;
  --letter: black;
}

```

All I want is to set 2 themes, but there's no examples of this on internet, neither stylus documentation, I have also check discussion here, but there's not information neither
