### ISSUE TITLE
CSS compression should not strip out unit from animation duration.

### ISSUE THREAD

**Issue by GCheung55** [stylus/stylus#1002]
When stylus is executed with compression, the animation duration's unit is removed. This causes animation in Firefox to break.

Without compression:

``` css
.someAnimation {
    -webkit-animation: animateSomething 0.25s cubic-bezier(0, 1.14, 0, 1.13) 0s 1 normal forwards;
    -moz-animation: animateSomething 0.25s cubic-bezier(0, 1.14, 0, 1.13) 0s 1 normal forwards;
    -o-animation: animateSomething 0.25s cubic-bezier(0, 1.14, 0, 1.13) 0s 1 normal forwards;
    -ms-animation: animateSomething 0.25s cubic-bezier(0, 1.14, 0, 1.13) 0s 1 normal forwards;
    animation: animateSomething 0.25s cubic-bezier(0, 1.14, 0, 1.13) 0s 1 normal forwards;
}
```

With compression (with line breaks for easier reading):

``` css
.someAnimation{
    -webkit-animation:animateSomething .25s cubic-bezier(0,1.14,0,1.13) 0 1 normal forwards;
    -moz-animation:animateSomething .25s cubic-bezier(0,1.14,0,1.13) 0 1 normal forwards;
    -o-animation:animateSomething .25s cubic-bezier(0,1.14,0,1.13) 0 1 normal forwards;
    -ms-animation:animateSomething .25s cubic-bezier(0,1.14,0,1.13) 0 1 normal forwards;
    animation:animateSomething .25s cubic-bezier(0,1.14,0,1.13) 0 1 normal forwards
}
```

Note the duration (first 0 after the cubic-bezier declaration) is missing the unit in the compression.
