### ISSUE TITLE
How can I set default unit 'px' and get % when I use % ?

### ISSUE THREAD

**Issue by rwu823** [stylus/stylus#1004]
``` css
w()
  width:unit(arguments, px)

#foo
  w:20 

#foo
  w:20px

#foo 
  w:20%
```

``` css
/*output*/

#foo{
  width:20px
}
```
