### ISSUE TITLE
Nesting with `&` should put sub-selectors in the right order

### ISSUE THREAD

**Issue by mattbasta** [stylus/stylus#1052]
```
p:before {
  &.bar {
    color: red
  }
}
```
It's expected that the above code would produce the following:
```css
p.bar:before {
  color: red;
}
```

Instead, it produces

```css
p:before.bar {
  color: red;
}
```

...which is invalid and will never match anything.

Stylus should order selectors within a simple selector such that they are in a valid order.
