### ISSUE TITLE
@host is not supported

### ISSUE THREAD

**Issue by filaraujo** [stylus/stylus#1054]
With introduction of webcomponents, stylus does not support @host declarations

``` css
@host {
    * {
        background #fff
    }
}
```

this results in 

``` css
host * {
    background: #fff;
}
```
