### ISSUE TITLE
One too many commas

### ISSUE THREAD

**Issue by tregusti** [stylus/stylus#1062]
I've included [normalize.css](http://git.io/L11kdg) as a .styl include, and with this input:

``` css
button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"] {
    -webkit-appearance: button; /* 2 */
    cursor: pointer; /* 3 */
}
```

stylus generates this:

``` css
button,html input[type="button"],/* 1 */,input[type="reset"],input[type="submit"]{-webkit-appearance:button;cursor:pointer;}
```

An extra comma is added around the comment.
