### ISSUE TITLE
@-moz-document url-prefix() // still has a problem

### ISSUE THREAD

**Issue by tiye** [stylus/stylus#1077]
I suppose we are able to switch to indetation syntax everywhere curry brackets was used... like:

``` stylus
/* */
@css
  @-moz-document url-prefix()
    .inline-button 
      padding-right 0px
```

for

``` stylus
/* */
@css {
  @-moz-document url-prefix()
    .inline-button 
      padding-right 0px
}
```

Live demo here: http://learnboost.github.io/stylus/try.html
I found thie problem in command line tool too/

But code is generated like:

``` css
css -moz-document url-prefix() .inline-button {
  padding-right: 0px;
}
```

than

``` css
-moz-document url-prefix() .inline-button {
  padding-right: 0px;
}
```
