### ISSUE TITLE
--resolve-url not working as expected

### ISSUE THREAD

**Issue by tiye** [stylus/stylus#1092]
`a.styl` here:

``` stylus
.a
  content 'style of a'

@import 'dir/b.styl'
```

`dir/b.styl` here:

``` stylus

.b
  content 'content of b'

.b a
  background-image url('./d.png')
```

compiled to `a.css`:

``` css
.a {
  content: 'style of a';
}
.b {
  content: 'content of b';
}
.b a {
  background-image: url("./d.png");
}
```

with command:

```
➤➤ stylus -V
0.34.1
➤➤ uname -a
Darwin chentekiMacBook-Air.local 12.4.1 Darwin Kernel Version 12.4.1: Tue May 21 17:04:50 PDT 2013; root:xnu-2050.40.51~1/RELEASE_X86_64 x86_64
➤➤ stylus --resolve-url --include-css a.styl
```

which was supposed to be:

```
.b a {
  background-image: url("./dir/d.png");
}
```

I found a commit on this https://github.com/LearnBoost/stylus/commit/3181c53c5ca672f1b39824f5880e0ed97cbc948a but the test cases seem not to include mine.
Or did I miss any trick here?
