### ISSUE TITLE
import files in blocks and make them duplicated, makes compiled code a mess

### ISSUE THREAD

**Issue by tiye** [stylus/stylus#1093]
I was trying to find out if Stylus is suitable for a use case, and I got this:

`a.styl` is:

``` stylus
.at-a
  @import 'b.styl'

  @import 'c.css'

  content 'a css'
```

`b.styl` ls:

``` stylus
.at-b
  @import 'c.css'

  content 'b css'
```

`c.css` is:

``` stylus
.at-c {
  content: 'at-c';
}
```

compiled them with:

```
➤➤ stylus --include-css a.styl
```

and I got:

``` css
.at-a  .at-a .at-b {
.at-c {
  content: 'at-c';
}
    content: 'b css';
  }
.at-c {
  content: 'at-c';
}
 {

.at-c {
  content: 'at-c';
}
  content: 'a css';
}
.at-a .at-b {
.at-c {
  content: 'at-c';
}
  content: 'b css';
}
.at-c {
  content: 'at-c';
}
.at-c {
  content: 'at-c';
}
```

there are two features I was tring to find:
- reduce duplicated files if needed(, for deployment)
- while `@import` is in a block, insert code into that block

I could infer that some of this are not in the roadmap of Stylus, but it did make the code a mess, would Stylus try to change this?
