### ISSUE TITLE
Bug with @extend in @media

### ISSUE THREAD

**Issue by ohardy** [stylus/stylus#1095]
This :
```css
$sample
  color #000

a
  @extend $sample

@media (-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi)
  strong
    @extend $sample
```

generate this:
```css
a,
strong {
  color: #000;
}
@media (-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi) {
}
```

expected this:
```css
a {
  color: #000;
}
@media (-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi) {
  strong {
    color: #000;
  }
}
```
