### ISSUE TITLE
Crazy bug (extend, function, condition)

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1097]
Here is a code:

``` Stylus
outer()
  &
    inner(arguments[0])

inner()
  if arguments[0]
    & > .d
      @extends .a
  else
    @extends .a

.a
  prop: val

.b
  outer()

.c
  outer(true)
```

Here is what is expected:

``` CSS
.a,
.b,
.c > .d {
  prop: val;
}
```

Here is what Stylus renders (`.c,` appeared):

``` CSS
.a,
.b,
.c,
.c > .d {
  prop: val;
}
```

I couldn't reduce the test more:
1. If I replace the call to `outer` with its content, there is no bug
2. If I move `&` to `inner` and don't use `outer`, there is no bug.
3. Even if I make two functions with the same content as outer and use them, there is no bug.

Extra _fun_ thing: when I try to use `p()` right before the condition inside `inner` I get `Cannot read property 'extends' of undefined` error.
