### ISSUE TITLE
Another crazy bug (extend after nested selector with function)

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1104]
Ok, another crazy bug found: 

``` Stylus
foo()
  @extends $foo

  & .bar
    baz()

  @extends $bar

baz()
  content: 'styles for `& .bar`'

$foo
  content: 'First extend'

$bar
  content: 'Second extend'

.foo
  foo()
```

The desired output should have the exact selectors at `$foo` and `$bar`:

``` CSS
.foo {
  content: 'First extend';
}
.foo {
  content: 'Second extend';
}
.foo .bar {
  content: 'styles for `& .bar`';
}
```

But we got this now:

``` CSS
.foo {
  content: 'First extend';
}
.foo .bar {
  content: 'Second extend';
}
.foo .bar {
  content: 'styles for `& .bar`';
}
```

Notice the difference in the second selector.

Steps to reproduce in words:
1. Call a function inside a rule.
2. Inside this function create a nested selector.
3. Inside this nested selector there should be a function call.
4. And any extend inside the original function would get the latest selector above it.

The “latest selector” thing could be used to workaround this bug — just add the same selector (`&`) with the empty function inside it:

``` Stylus
foo()
  @extends $foo

  & .bar
    baz()

  &
    dope()

  @extends $bar

baz()
  content: 'styles for `& .bar`'

dope()
  // lol

$foo
  content: 'First extend'

$bar
  content: 'Second extend'

.foo
  foo()
```
