### ISSUE TITLE
Bug with nested functions and interpolations

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1106]
Here is the buggy code:

``` Stylus
foo()
  {arguments}()

baz()
  height: 10px

bar1()
  foo 'baz'

bar2()
  foo('baz')

.foobar1
  foo 'bar1'

.foobar2
  foo 'bar2'
```

Both `.foobar1` and `.foobar2` should have the same content as the `foo 'baz'` and `foo('baz')` should be equal, but the `foo 'baz'` variant don't work here and is treated literally:

``` CSS
.foobar1 {
  foo: 'baz';
}
.foobar2 {
  height: 10px;
}
```

**Comment by RachelSatoyama** [comment]
Do I understand correctly that the idea is to have this output
```css
.foobar1 {
  foo: 'baz';
}
```
in case there hasn't been foo declared
and 
```css
.foobar1 {
  height: 10px;
}
```
in case it was?
