### ISSUE TITLE
In some cases, conditional branches don't carry mixins into nested scope

### ISSUE THREAD

**Issue by bugeats** [stylus/stylus#1114]
Sorry for the super cryptic title, but I don't know how else to explain.  Check out this example:

``` stylus
// This doesn't work as expected
broken-container-mixin()

  some-variable = false

  my-helper(n)
    n + 20px

  section-mixin()
    font-size: my-helper(100px)
    unless some-variable
      width: my-helper(100px)
      .nested
        height: my-helper(100px)

  .some-section
    section-mixin()

.broken-container
  broken-container-mixin()

// ----

// This is my work-around
workaround-container-mixin()

  some-variable = false

  my-helper(n)
    n + 20px

  section-mixin()
    font-size: my-helper(100px)
    unless some-variable
      width: my-helper(100px)
    .nested
      unless some-variable
        height: my-helper(100px)

  .some-section
    section-mixin()

.workaround-container
  workaround-container-mixin()
```

This produces the following output:

``` css
.broken-container .some-section {
  font-size: 120px;
  width: 120px;
}
.broken-container .some-section .nested {
  height: my-helper(100px);
}
.workaround-container .some-section {
  font-size: 120px;
  width: 120px;
}
.workaround-container .some-section .nested {
  height: 120px;
}
```

See the part where `my-helper` is not interpreted?  This seems wrong to me.
