### ISSUE TITLE
css to stylus conversion fails at nested star selector

### ISSUE THREAD

**Issue by seniorpreacher** [stylus/stylus#1123]
I've tried to convert a generated Foundation css file to stylus, but it failed at the following lines:

``` css
@media print {
  * {
    background:transparent!important;
    color:black!important;
    box-shadow:none!important;
    text-shadow:none!important;
  }
  ...
}
```

Error message: `expected "}", got "newline"`
