### ISSUE TITLE
--resolve-url eats query and hash from url

### ISSUE THREAD

**Issue by disfated** [stylus/stylus#1125]
`style.styl`:

``` css
@font-face {
  src: url("some-font.eot?#iefix&v=1");
}
```

Suppose `some-font.eot` is found at given path, then

``` bash
$ stylus --resolve-url < style.styl
```

generates `style.css`:

``` css
@font-face {
  src: url("some-font.eot");
}
```

I would expect stylus to preserve `?#iefix&v=1` in resulting url.
