### ISSUE TITLE
bug: comments in group selectors

### ISSUE THREAD

**Issue by idealhack** [stylus/stylus#1134]
from [normalize.css](https://github.com/necolas/normalize.css/blob/dafaf9e/normalize.css#L324):

stylus:

``` css
button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"] {
    -webkit-appearance: button; /* 2 */
    cursor: pointer; /* 3 */
}
```

css:

``` css
button,
html input[type="button"],
/* 1 */,
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button;
/* 2 */
  cursor: pointer;
/* 3 */
}
```

css (compressed):

``` css
button,html input[type="button"],/* 1 */,input[type="reset"],input[type="submit"]{-webkit-appearance:button;cursor:pointer;}
```
