### ISSUE TITLE
Bug in vendored keyframes

### ISSUE THREAD

**Issue by seniorpreacher** [stylus/stylus#1135]
This code:

```
@keyframes spin
    0%
        transform rotate(0deg)
    100%
        transform rotate(359deg)
```

generates CSS like this:

``` css
@-webkit-keyframes spin{
  0%{transform:rotate(0)}
  100%{transform:rotate(359deg)}
}
```

The problem with this, it all the transforms should be vendorized  as well. Even if I add them manually, if I want to keep the _official_ @keyframes Stylus generates this vendorized versions, what overwrites my manually defined rules.
Okay, I could delete the 'official' from the vendor array, but then I can't use it anywhere else.
