### ISSUE TITLE
can't use properties inside of mixins

### ISSUE THREAD

**Issue by provencal** [stylus/stylus#1140]
The following code doesn't work as intended (or at least how I intended it :)

``` stylus
macro()
    margin-left -(@width / 2)

.cls
    macro()
    width 23px

.cls2
    width 23px
    margin-left -(@width / 2)
```

outputs

``` css
.cls {
  width: 23px;
}
.cls2 {
  width: 23px;
  margin-left: -11.5px;
}
```

I expected margin-left to be set in .cls, but it was not.
Is it a bug or are mixins not able to access properties ?
