### ISSUE TITLE
Literal CSS duplicated

### ISSUE THREAD

**Issue by Calvein** [stylus/stylus#1141]
I'm using Stylus 0.37.0 and I found a bug when using CSS literal.

``` styl
li
    margin 0 12px
    @css {
        margin: 0;
    }

    &.even
        margin-left 0

```

``` css
li {
  margin: 0 12px;
margin: 0;
}
margin: 0;
li.even {
  margin-left: 0;
}
```

Margin is duplicate outside the li scope, which make the `.even` not working.
It's working fine on the online tester.
