### ISSUE TITLE
Bug with media queries inside condition statements inside functions

### ISSUE THREAD

**Issue by Zyber17** [stylus/stylus#1142]
Putting a media query inside of a conditional statement that is in a function results in some wonky css.

For example:

``` stylus
x2img(objectHeight)
    if objectHeight > 64
        background-image url('image@2x.png')
    else
        background-image url('image.png')
        @media screen and (-webkit-min-device-pixel-ratio:1.5)
            background-image url('image@2x.png')

div
    x2img(32)
```

yields:

``` css
div@media screen and (-webkit-min-device-pixel-ratio:1.5) {
    div {
      background-image: url("image@2x.png");
    }
}
 {
  background-image: url("image.png");

}
@media screen and (-webkit-min-device-pixel-ratio:1.5) {
  div {
    background-image: url("image@2x.png");
  }
}
```
