### ISSUE TITLE
Unquoted color and color functions bug

### ISSUE THREAD

**Issue by pfrankov** [stylus/stylus#1151]
I'll just leave this here:

``` css
A = unquote("#fff");
B = lightness(A);

a {
    some-property: B;
}
```

`TypeError: expected rgba or hsla, but got literal:#fff`
