### ISSUE TITLE
Multi selectors that start with *

### ISSUE THREAD

**Issue by Calvein** [stylus/stylus#1161]
The comportment of multi selectors that start with a \* is different than others one:

``` styl
*
*:before
*:after
    box-sizing border-box

a
a:before
a:after
    box-sizing border-box
```

``` css
*
*: before;
*:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

a,
a:before,
a:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

```
