### ISSUE TITLE
Breakpoints interpolation in @keyframes

### ISSUE THREAD

**Issue by Andreyco** [stylus/stylus#1165]
Hi, could this be possible?

``` css
n = 10
@keyframes rotation
    {n}%
        transform:rotate(...);
    {n*2}%
        transform:rotate(...);
```

Basicaly, this is interpolation for @keyframe breakpoints, right?
Thanks, Andrej
