### ISSUE TITLE
Regression in postfix `if`

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1205]
```
$foo = #000 if "foo" == "foo"

.foo
  background: $foo
```

Now renders as

``` CSS
.foo {
  background: #000 if true;
}
```

This is a regression introduced in #1185
