### ISSUE TITLE
v0.40.1 bad compilation for styles with invalid colors

### ISSUE THREAD

**Issue by doochik** [stylus/stylus#1206]
v0.40.1 compiles this example to invalid CSS

```
.foo
  color: #000FFFA

  .bar
    color: red
```

Result:

``` css
.foo color: #000FFFA,
.foo .bar {
  color: #000;
}
```
