### ISSUE TITLE
Shorthand substitution

### ISSUE THREAD

**Issue by monolithed** [stylus/stylus#1225]
``` stylus
.selector:{focus, hover, active, visited}
    color red
```

``` css
.selector:focus,
.selector:hover,
.selector:active,
.selector:visited {
   color: red
}
```

This construct is typically used as shorthand in unix environment like:

``` sh
➜ du -h /usr/bin/{awk,sed}
 48K    /usr/bin/awk
 20K    /usr/bin/sed
```

I think that is a very powerful and necessary feature
