### ISSUE TITLE
Bug：Extends generate duplicate selectors

### ISSUE THREAD

**Issue by houkanshan** [stylus/stylus#1231]
A little difference with https://github.com/LearnBoost/stylus/issues/819

Tested on Stylus 0.40.3 & 0.38.0

Input:

``` stylus
$sel
  &
  &:hover
    color: #fff

a
  @extend $sel
```

Output:

``` css
a,
a:hover,
a {
  color: #fff;
}
```

The selector `a` is duplicate

Many Thx!
