### ISSUE TITLE
Spec for selector references

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1240]
That's a logical continuing for the existent parent reference — `&`.

All the proposed references should work like `&` works now: when they exist in the selector, this selector shouldn't have the parent's selector inserted before it automatically.

Some of those references could seem a bit like `@at-root` in Sass, but they could be way more powerful, because you can use them inside the multiple selectors and in any other similar cases.
## Parent reference — `&` — _status: already there_.

Ok, we already have it, I'm listing it here, so we could have there a full stack of all the possible references.

We should note that it works in Stylus by _literally_ inserting the parent selector, so things like `ul&` (prefixing the parent with `ul`, mostly used for specifying an element) or `&&` (used, for example, for multiplying the class to increase the specificity, **not working ATM**) should be possible.
## Root reference — `/` — _status: shipped in 0.42.0_

That's a reference to the root context. Could be used to place styles outside the current context, so they won't inherit the selector from the parent. Use case:

``` Stylus
.foo
  width: 10px

  .bar,
  /.baz
    height: 10px
```

would be rendered as

``` CSS
.foo {
  width: 10px;
}
.foo .bar,
.baz {
  height: 10px;
}
```

Could be used with or without space: `/.foo` and `/ .foo` are equal.

Note that root reference can be placed only at the beginning of a selector.
## Relative references — `../` — _status: shipped in 0.53.0_

While the parent reference — `&` — represents the whole current selector, we should have a way to move the nesting to the previous nesting level.

``` Stylus
.foo
  .bar
    width: 10px

    &,
    ../ .baz
      height: 10px
```

would render as

``` CSS
.foo .bar {
  width: 10px;
}
.foo .bar,
.foo .baz {
  height: 10px;
}
```

While on its own the relative references won't be very useful, they would be when used with the partial reference modifier.

As well as the root reference, relative reference can be used only at the start of the selector, however you can use multiple instances of relative references like `../../../` to get the deeper selectors.
## Partial references — `^[N]` — _status: shipped in 0.53.0_

Partial references gives you access to different numbered nesting levels individually. The `^[0]` would give you the selector from the first level, the `^[1]` would give you the rendered selector from the second level etc.

``` Stylus
.foo
  &__bar
    width: 10px

    ^[0]:hover &
      width: 20px
```

would be rendered to

``` CSS
.foo__bar {
  width: 10px;
}
.foo:hover .foo__bar {
  width: 20px;
}
```

Negative values are counting from the end, so `^[-1]` would give you the last selector from the chain before `&` (in that terms `&` would be equal to `^[-0]`).

``` Stylus
.foo
  &__bar
    &_baz
      width: 10px

      ^[-1]:hover &
        width: 20px
```

would be rendered to

``` CSS
.foo__bar_baz {
  width: 10px;
}
.foo__bar:hover .foo__bar_baz {
  width: 20px;
}
```

When the N is bigger than the available range of selectors, Stylus shouldn't render the whole selector at all (when in selector context) and should return `null` when returned from `selector()`.

``` Stylus
.a
  .b
    ^[0] .c,
    ^[10] .c
      test: selector('^[0]')
      test: selector('^[1]')
      test: selector('^[10]')

    ^[10] .c
      what: ever
```

Should render as

``` CSS
.a .c {
  test: '.a';
  test: '.a .b';
  test: null;
}
```

You can see that when the selector is _dropped_, if that's the only selector, the whole block shouldn't be rendered.

Note that partial reference contain the whole rendered chain of selectors until the given nesting level, not the “part” of the selector. That means that `^[-1]` would give you the same selector as relative reference `../`, but while the relative reference could be used only at the start of the selector, partial references could be used as any part of a selector.
### Ranges in partial references — `^[N..M]` — _status: shipped in 0.53.0_

If you'd have a case when you'd need to get the raw part of the selector, or to get the range of parts programmatically, you could use ranges inside partial reference.

If the range would start from the positive value, the result won't contain the selectors of the previuos levels and you'd get the result as if the selectors of those levels were inserted at the root of the stylesheet.

``` Stylus
.foo
  & .bar
    width: 10px

    ^[0]:hover ^[1..-1]
      width: 20px
```

Would be rendered as 

``` CSS
.foo .bar {
  width: 10px;
}
.foo:hover .bar {
  width: 20px;
}
```

The first number in the range would be the start index, the second — the end index, however the order of them won't matter as the selectors would always render from the first levels to the last, so `^[1..-1]` would be equal to the `^[-1..1]`.

When both numbers are equal, the result would be just one raw level of a selector, so you could replace `^[1..-1]` to just `^[1..1]` as in both cases you'd get only one level of a selector.
## Partial modifiers — `^^[N]` and `^^[N..M]` — _status: in consideration_

There could be cases when you'd like to work only with one part of the selector. For example, if you'll have something like:

``` Stylus
.a
  .b
    .c
      .d
        .e
          background: red
```

And then you'd like to modify the `.c` to be hovered. While it is possible with partial references, using the `^[2]:hover ^[3..-1]` selector, it can be rather cumbersome. The partial modifier make this a rather easy task:

``` Stylus
.a
  .b
    .c
      .d
        .e
          background: red

          ^^[2]:hover
            background: lime
```

Would render as

``` CSS
.a .b .c .d .e {
  background: red;
}
.a .b .c:hover .d .e {
  background: lime;
}
```

The partial modifier works just like partial reference, that means that `^^[2]` would actually reference a whole rendered selector from the start, so prefixing it would prefix the whole selector:

``` Stylus
.a
  .b
    .c
      .d
        .e
          background: red

          .wrapper ^^[2]:hover
            background: lime
```

Would render as 

``` CSS
.a .b .c .d .e {
  background: red;
}
.wrapper .a .b .c:hover .d .e {
  background: lime;
}
```

If you'd like to modify just the middle part, you could use range as you could use it at partial reference:

``` Stylus
.a
  .b
    .c
      .d
        .e
          background: red

          .wrapper ^^[2..2]:hover
            background: lime
```

Would render as 

``` CSS
.a .b .c .d .e {
  background: red;
}
.a .b .wrapper .c:hover .d .e {
  background: lime;
}
```

Note that as this is a _modifier_, you can't use more than one in a selector.
## Partial replacement — `^^^[N]` and `^^^[N..M]` — _status: in consideration_

There can be cases when you'd like not just _modify_ the part of a selector, but replace it completely. That's where the partial replacement become useful:

``` Stylus
.a
  .b
    .c
      .d
        .e
          background: red

          ^^^[2] .z
            background: lime
```

Would render as

``` CSS
.a .b .c .d .e {
  background: red;
}
.a .b .z .d .e {
  background: lime;
}
```

As well as you can't use two partial modifiers, you can't use two partial replacements or mix both.
## The subject of `&` in partial modifiers/replacements — _status: in consideration_

While in most cases `&` would always render as a whole selector of the current level, when it is used as a part of partial modifier or partial replacement, it's semantics become different.

When used _before_ partial modifier/replacement, it represents the whole previous rendered part before the mentioned part, when used _after_ — it represents the following parts merged together.

That means that, `& ^^[2..2] &`, for example, would be equal to just `^^[2]`.

You can use this effect if you'd like to change the way parts of selectors connect to each other:

``` Stylus
.a
  .b
    .c
      .d
        .e
          background: red

          &^^[2..2]&
            background: lime
```

Here removing the spaces would render as:

``` CSS
.a .b .c .d .e {
  background: red;
}
.a .b.c.d .e {
  background: lime;
}
```

And adding something before and after:

``` Stylus
.a
  .b
    .c
      .d
        .e
          background: red

          .aa & .bc ^^[2..2] .cd & .ee
            background: lime
```

Would make it possible to insert things in a more flexible way:

``` CSS
.a .b .c .d .e {
  background: red;
}
.aa .a .b .bc .c .cd .d .e .ee {
  background: lime;
}
```

That behaviour of `&` in the context of partial modifiers/replacements is another thing that make it possible to use only one of them in a selector.
## `selector()` bif — _status: shipped in 0.41.0_

There should be a `selector()` built-in function, that:
1. When called with string argument would return the string with an interpolated selector, i.e. all referenced expanded.
2. When called without argument it would equal to `selector('&')` — it would return the current selector.

Right now we already have powerful selectors, but have no way of looking or changing them, adding such getter would make it possible to do a lot of nice stuff.

``` Stylus
.foo
  .bar
    bar: selector()
```

would render as

``` CSS
.foo .bar {
  bar: ".foo .bar"
}
```

etc.
### Comma-separated lists as `selector()`'s arguments — _status: shipped in 0.53.0_

When a list like `'.a', '.b', '.c, .d'` is given to a `selector()` bif, it should be rendered as if those items in a list were nested selectors, like

``` Stylus
.a
  & .b
    & .c,
    & .d
```

As well as comma-separated lists, multiple arguments given to `selector()` should work in the same way.

This would make it possible to create nested structures easier.

Space-separated lists should render as if that was a single selector with spaces between items.
## `selectors()` bif — _status: shipped in 0.53.0_

There should be a `selectors()` bif that should return a comma-separated list of raw selectors from the current level.

``` Stylus
.a
  .b
    &__c
      foo: selectors()[0]
      bar: selectors()[1]
      baz: selectors()[2]
```

Should render as

``` CSS
.a .b__c {
  foo: '.a';
  bar: '& .b';
  baz: '&__c';
}
```

Note that the selectors like `.b` with omitted `&` would still have it in the raw form.

---

This is a proposed syntax, while I'm certain it is the best for the job (I've though about this feature for months already), if anyone would point me to possible problems or things to make better — I would gladly take them into account.

**Comment by sevenupcan** [comment]
:+1:  from me.

I'm working on a project which uses the shadow DOM and some of my mixins to create selectors with references to the shadow DOM but to do this I needed to manipulate the middle part of the selector.

To give you an example:

```stylus
.grandparent
     .parent
         .child
             mymixin: 300px;
```

would output
```css
.grandparent .parent::shadow .child {
    width: 300px;
}
```

This requires me having a selector a bit like the one below which I had to create by turning the `selector()` expression into several arrays and manipulating them (Thanks to @Panya for this tip).

```stylus
/{previous}::shadow {current} 
```
