### ISSUE TITLE
Feature request / Idea: chaining/combine of classes and ids

### ISSUE THREAD

**Issue by ryrun** [stylus/stylus#1245]
Descendant selectors are slow. I use stylus mainly with the indent syntax and produce css with many descendant selectors. What about chaining of classnames and combine styles of chained classes and ids?

Example:

``` sass
.menu
    padding: 0
    margin: 0
    _item
         font-size: 12px
        color: red

.text
    color: #ccc
    __link
         text-decoration: none
         &:hover
             text-decoration: underline
```

Generated CSS:

``` css
.menu{
    padding:0;
    margin:0
}
.menu_item{
    font-size:12px;
    color:red
}

.text{
    color:#ccc
}
.text_link{
    color:#ccc;
    text-decoration:none
}
.text_link:hover{
    color:#ccc;
    text-decoration:underline
}
```

_ = combine previous class or id
__ = combine previous class or id and copy styles

What do you think about it?
