### ISSUE TITLE
Bug with unquote

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1260]
`unquote` used inside the block is handled incorrectly:

```
.foo
  unquote('width:10px;')

.bar
  unquote('width:20px;')
  height: 20px
```

Now renders as

``` CSS
width:10px;
.bar {
width:20px;
  height: 20px;
}
width:20px;
```
1. When there are no other declarations inside the block, the unquoted entity is placed without the selector.
2. When there is another declaration, it is placed both inside and outside of the rule.

I guess we should always place it once and inside the rule.
