### ISSUE TITLE
`--resolve-url` and `image-size` not working as expected

### ISSUE THREAD

**Issue by firede** [stylus/stylus#1293]
### file tree

```
.
├── css
│   ├── img
│   │   └── logo.png (240px * 270px)
│   ├── lib
│   │   └── lib.styl
│   └── main.styl
└── img
    └── logo.png (120px * 135px)
```
### source code

`/css/lib/lib.styl`:

``` stylus
bg(_path)
    background-image: url(_path)
    _size = image-size(_path, true)
    if _size[0] != 0
        width: _size[0]
        height: _size[1]
```

`/css/main.styl`:

``` css
@import 'lib/lib'

.main
    bg: '../img/logo.png'
```
### compile css

`/css/main.css` ( **with** `-r` ):

``` css
.main {
  background-image: url("img/logo.png");
  width: 240px;
  height: 270px;
}
```

`/css/main.css` ( **without** `-r` ):

``` css
.main {
  background-image: url("../img/logo.png");
  width: 240px;
  height: 270px;
}
```
### expected

``` css
.main {
  background-image: url("../img/logo.png");
  width: 120px;
  height: 135px;
}
```
