### ISSUE TITLE
Spec for redirecting blocks: @prepend, @append and friends

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1296]
It would be nice to be able to redirect the blocks of code to different places. The point is that you could take any existent block and append any styles to it, or insert any other styles somewhere near it.

The keywords and syntax are drafty and could be discussed.
## `@append` and `@prepend`

There should be two similar at-rules: `@append` and `@prepend`.

They should take the literal selector as their first argument (like `@extend` does) and the block as the second one (either using curly braces or indentation):

``` Sass
@prepend .foo
  .bar
    width: 10px
```

or 

``` CSS
@prepend .foo {
  .bar {
    width: 10px;
  }
}
```

This would work a bit opposite to `@extend`: it would _move_ the given code block to the destination selector, so

``` Sass
.foo
  width: 10px

@prepend .foo
  height: 10px

@append .foo
  .bar
    padding: 0
```

would render as

``` CSS
.foo {
  height: 10px;
  width: 10px;
}
.foo .bar {
  padding: 0;
}
```
### Parent reference inside the redirect

The conten of `@append` and `@prepend` do not inherits its context, so when you use `&` inside the appended selector, it should be moved to the new context and expanded there, and selectorless properties would inserted as-is, not like the bubbling in media-queries works:

``` Sass
.foo
  width: 10px

.bar
  height: 10px

  @append .foo
    margin: 0
    &:hover
      padding: 0
```

Would render to 

``` CSS
.foo {
  width: 10px;
  margin: 0;
}
.foo:hover {
  padding: 0;
}
.bar {
  height: 10px;
}
```

If you'd want to use the current context's selector, you'd need to call `selector()` inside an interpolation:

``` Sass
.foo
  width: 10px

.bar
  @append .foo
    {selector()}:hover > &
      padding: 0
```

would render to

``` CSS
.foo {
  width: 10px;
}
.bar:hover > .foo {
  padding: 0;
}
```

I tried to think of opposite way but I found out the current proposal to have less cons: we would need to create a new entity just to mark the new context in the passed selectors, also I see `@append` and `@prepend` to be used mostly to add your own styles to the framework's styles, so it would be used often without the wrapping selectors, and it makes sense to optimize the syntax for this case. Also, the sum of `selector()` and `&` in this context seems to be logical. If anyone would come up with another way of doing this, I would glad to hear it.
### Multiple selectors

It is discussible, but I think `@append`, `@prepend` and other similar rules should target only the first occurrence of the given literal selector, so in that case:

``` Sass
.foo
  width: 10px

.foo:hover
  heigth: 20px

.foo
  padding: 0

@append .foo
  color: #f00
  &.is-disabled
    margin: 0

@append .foo:hover
  border: 0

@append .foo
  background: #000

```

The result would be

``` CSS
.foo {
  width: 10px;
  color: #f00;
  background: #000;
}
.foo.is-disabled {
  margin: 0;
}
.foo:hover {
  height: 20px;
  border: 0;
}
.foo {
  padding: 0;
}
```

You can see there also, that each `@append` adds its contents to the block.

Another option: `@prepend` could prepend to the first found block, the `@append` — to the last one.
## No `@insert-before` and `@insert-after`

At first I though on adding `@insert-before` and `@insert-after` or similar rules alongside the `@append` and `@prepend`, but I think it is not necessary: we can use the [root reference](https://github.com/LearnBoost/stylus/issues/1240) to do the same thing and we could do more nice things with it:

``` Sass
.foo
  width: 10px

.bar
  padding: 0

@append .foo
  /.baz
    height: 10px

@append .baz
  &:hover
  /.raz
    height: 20px
```

would render to 

``` CSS
.foo {
  width: 10px;
}
.baz {
  height: 10px;
}
.baz:hover,
.raz {
  height: 20px;
}
.bar {
  padding: 0;
}
```

So, that's it.

There would be, of course, a lot of minor and major questions, like could be `@extend` things added this way etc, but they could be processed later, it would be nice to have at least basic working `@append` and `@prepend` in Stylus.
