### ISSUE TITLE
stylus fails on substituting vars into css' calc function

### ISSUE THREAD

**Issue by cyberglot** [stylus/stylus#1310]
The following mixin

``` css
test(size)
    width calc(100% - size / 2)

.test-class
    test(5em)
```

is outputed as

``` css
.test-class {
  width: calc(100% - size / 2);
}
```

I know we must keep the maths inside the calc function, but i guess it'd be better to substitute all vars, no? Does it sound reasonable?
