### ISSUE TITLE
Property lookup bug

### ISSUE THREAD

**Issue by tremby** [stylus/stylus#1315]
I am using Stylus 0.41.3.

I have just found this bug:

Input:

``` stylus
div
    padding-left 10px
    @media screen and (orientation: portrait)
        padding-left 20px
        padding-right @padding-left
```

Expected output:

``` css
div {
  padding-left: 10px;
}
@media screen and (orientation: portrait) {
  div {
    padding-left: 20px;
    padding-right: 20px;
  }
}
```

Actual output:

``` css
div {
  padding-left: 10px;
}
@media screen and (orientation: portrait) {
  div {
    padding-left: 20px;
    padding-right: 10px;
  }
}
```
