### ISSUE TITLE
Issue with variable in parentheses

### ISSUE THREAD

**Issue by tremby** [stylus/stylus#1317]
I'm not sure if this is the same as or similar to #1051 or #279 (at least parts of it are).

I have

``` stylus
$var = 212px
div
    margin-left -$var
    margin-right -($var)
    margin-top (-$var)
    margin-bottom (- $var)
```

and I get

``` css
div {
  margin-left: -$var;
  margin-right: -212px;
  margin-top: -$var;
  margin-bottom: -212px;
}
```

I understand that at least the margin-left line is to do with the bugs mentioned above, but the others surprise me. Especially the fact that adding a space to the margin-top line to get the margin-bottom line makes the variable get noticed.
