### ISSUE TITLE
Variable scope issue

### ISSUE THREAD

**Issue by KATT** [stylus/stylus#1320]
This might just be not understanding how variables gets inherited in the different scopes.

I'm trying to create a mixin that has a media query using a variable declared in the mixin, like this:

``` css
responsive-image($image) {
  $path = $relative-image-path + $image;

  $ext = extname($path);
  $path2x = pathjoin(dirname($path), basename($path, $ext) + '@2x' + $ext);

  // [..]

  @media $retina {
    background-image: url($path2x);
  }
}
```

However, the `$path2x` variable doesn't get inherited to the `@media` scope. Is this a bug or have I misinterpreted how the variables work in Stylus?

Here is the full mixin that I'm trying to create: https://gist.github.com/KATT/8283246. As a workaround for now I'm just adding `$image2x` as a second argument.
