### ISSUE TITLE
Bug：Extends generate duplicate code

### ISSUE THREAD

**Issue by hxgdzyuyi** [stylus/stylus#1324]
Tested on Stylus 0.42.0

Input: 

index.styl

```
$test
  content: 'test'

$test
  content: 'test'

.css2
  @extend $test

.css1
  @extend $test
```

Output 

``` bash
stylus index.styl -p
```

``` css
.css2,
.css1 {
  content: 'test';
}
.css2,
.css1 {
  content: 'test';
}
```
