### ISSUE TITLE
create mutiple rules when @extending from vendored selectors

### ISSUE THREAD

**Issue by flying-sheep** [stylus/stylus#1325]
``` css
progress::-moz-progress-bar
    @extend .progress .progress-bar

progress::-webkit-progress-value
    @extend .progress .progress-bar
```

creates

``` css
.progress .progress-bar,
progress::-moz-progress-bar,
progress::-webkit-progress-value {
    float: left;
    ...
}
```

this won’t work anywhere. ideally both the initial stylus code and the following…

``` css
progress::-moz-progress-bar, progress::-webkit-progress-value
    @extend .progress .progress-bar
```

…would create 3 rules.
