### ISSUE TITLE
Bug with missing space in cascade

### ISSUE THREAD

**Issue by untone** [stylus/stylus#1332]
This code:

```
.foo
  bar baz

  &-2x .bar
    baz quux

```

Yields to:

``` css
.foo {
  bar: baz;
}
.foo-2x.bar {
  baz: quux;
}
```

Expected:

``` css
.foo {
  bar: baz;
}
.foo-2x .bar {
  baz: quux;
}
```
