### ISSUE TITLE
Odd multiply operations results.

### ISSUE THREAD

**Issue by leny** [stylus/stylus#1336]
Hi, I have made an unfortunate search for an existing issue about this subject, so I post it here : when you multiply an integer by a float, the results seems odd, as in these examples : 

``` stylus
body
    width 0 * 0.1rem
    width 1 * 0.1rem
    width 2 * 0.1rem
    width 3 * 0.1rem
    width 4 * 0.1rem
    width 5 * 0.1rem
    width 6 * 0.1rem
    width 7 * 0.1rem
    width 8 * 0.1rem
    width 9 * 0.1rem
    width 10 * 0.1rem
    width 11 * 0.1rem
    width 12 * 0.1rem
    width 13 * 0.1rem
    width 14 * 0.1rem
    width 15 * 0.1rem
    width 16 * 0.1rem
    width 17 * 0.1rem
    width 18 * 0.1rem
    width 19 * 0.1rem
    width 20 * 0.1rem
```

which outputs to : 

``` css
body {
  width: 0rem;
  width: 0.1rem;
  width: 0.2rem;
  width: 0.30000000000000004rem;
  width: 0.4rem;
  width: 0.5rem;
  width: 0.6000000000000001rem;
  width: 0.7000000000000001rem;
  width: 0.8rem;
  width: 0.9rem;
  width: 1rem;
  width: 1.1rem;
  width: 1.2000000000000002rem;
  width: 1.3rem;
  width: 1.4000000000000001rem;
  width: 1.5rem;
  width: 1.6rem;
  width: 1.7000000000000002rem;
  width: 1.8rem;
  width: 1.9000000000000001rem;
  width: 2rem;
}
```

Is this a _normal_ behavior, or some subtility I miss ?

Thanks,

_(sorry for my aproximate english, I try hard)_
