### ISSUE TITLE
Bug with current-property and block mixins

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1355]
`current-property` is not available when there is a block mixin call between it and property:

```
foo()
  baz()

bar()
  +baz()
    width: 10px

baz()
  test: current-property

raz
  foo: taz
  bar: taz
```

Returns now

``` CSS
raz {
  test: 'foo' taz;
  test: ;
}
```
