### ISSUE TITLE
Weird bug when assigning variable from a hash in a loop

### ISSUE THREAD

**Issue by abe33** [stylus/stylus#1431]
With Stylus 0.42.3, when looping over a hashes of hashes and extracting data inside the loop, the variable ends up being null after the first iteration, but the keys and values during the iteration are fine.

The failing code: 

``` stylus

icon_owner(base_selector, all_settings)
  &.{base_selector}
    for size_name, settings in all_settings

      horizontal_padding = settings.horizontal_padding
      vertical_padding = settings.vertical_padding
      font_size = settings.font_size
      icon_size = settings.icon_size

      p(size_name)
      p(settings)
      p(horizontal_padding)
      p(vertical_padding)
      p(font_size)
      p(icon_size)

      if size_name == default
        padding vertical_padding horizontal_padding
        font-size font_size

        i
          font-size icon_size

      else
        &.{base_selector}-{size_name}
          padding vertical_padding horizontal_padding
          font-size font_size

          i
            font-size icon_size

box_settings = {
  small: {
    horizontal_padding: 4px
    vertical_padding: 2px
    font_size: 10px
    icon_size: 14px
  }
  default: {
    horizontal_padding: 6px
    vertical_padding: 4px
    font_size: 12px
    icon_size: 16px
  }
  large: {
    horizontal_padding: 8px
    vertical_padding: 6px
    font_size: 14px
    icon_size: 18px
  }
}

icon_owner(box, box_settings)
```

The CSS result: 

``` css
.box {
  padding: ;
  font-size: ;
}
.box.box-small {
  padding: 2px 4px;
  font-size: 10px;
}
.box.box-small i {
  font-size: 14px;
}
.box i {
  font-size: ;
}
.box.box-large {
  padding: ;
  font-size: ;
}
.box.box-large i {
  font-size: ;
}
```

In the console:

```
inspect: 'small'
inspect: {"horizontal_padding":"(4px)","vertical_padding":"(2px)","font_size":"(10px)","icon_size":"(14px)"}
inspect: 4px
inspect: 2px
inspect: 10px
inspect: 14px
inspect: 'default'
inspect: {"horizontal_padding":"(6px)","vertical_padding":"(4px)","font_size":"(12px)","icon_size":"(16px)"}
inspect: null
inspect: null
inspect: null
inspect: null
inspect: 'large'
inspect: {"horizontal_padding":"(8px)","vertical_padding":"(6px)","font_size":"(14px)","icon_size":"(18px)"}
inspect: null
inspect: null
inspect: null
inspect: null
```

I just can't wrap my head around that. Is it an issue in the way I'm using the hash in the loop ? Is it an issue with nested hashes ?
