### ISSUE TITLE
rgba(...) in hash is ignored

### ISSUE THREAD

**Issue by jlowcs** [stylus/stylus#1458]
Somehow, it seems like rgba(...) is ignored or discarded when it's a hash value.

``` css
$myHash = {};
$myHash.shadow = -1px 0px 6px 2px rgba(0,0,0,0.5);
.my-class {
  box-shadow: $myHash.shadow
}
```

output:

``` css
.my-class {
  box-shadow: -1px 0px 6px 2px
}
```

It works well without a hash:

``` css
$myShadow = -1px 0px 6px 2px rgba(0,0,0,0.5);
.my-class {
  box-shadow: $myShadow
}
```

output:

``` css
.my-class {
  box-shadow: -1px 0px 6px 2px rgba(0,0,0,0.5)
}
```

Any idea as to why?

Stylus 0.42.3
