### ISSUE TITLE
Can't extend multiple levels nested

### ISSUE THREAD

**Issue by ianva** [stylus/stylus#1475]
Given the following input:

``` stylus
.cell-list
  >.item
    width 200px
.mod-product
  >.list
    @extend .cell-list
    float left
.reg-products  
  >.product
    @extend .mod-product
```

output:

``` css
.cell-list >.item,
.mod-product >.list >.item {
  width: 200px;
}
.mod-product >.list,
.reg-products >.product >.list {
  float: left;
}
```

`.reg-products` don't extend `.cell-list>.item`
