### ISSUE TITLE
!important not preserved for display: block

### ISSUE THREAD

**Issue by samdaltonmaag** [stylus/stylus#1476]
!important is lost when applied to display: block, but other display properties work.

For example:

``` stylus
.test
  display none !important
```

compliles to

``` css
.test {
  display: none !important;
}
```

but

``` stylus
.test
  display block !important
```

compiles to

``` css
.test {
  display: block;
}
```

Using v0.43.1.
