### ISSUE TITLE
@keyframes bug when used 0.44.0

### ISSUE THREAD

**Issue by firede** [stylus/stylus#1489]
stylus:

```
.view-detail
  @keyframes flash
    0%, 50%, 100%
      opacity: 1
    25%, 75%
      opacity: 0
```

output (0.43.1) :heavy_check_mark: :

``` css
@keyframes flash {
  0%, 50%, 100% {
    opacity: 1;
  }
  25%, 75% {
    opacity: 0;
  }
}
```

output (0.44.0) :heavy_multiplication_x: :

``` css
@keyframes flash {
  .view-detail 0%, .view-detail 50%, .view-detail 100% {
    opacity: 1;
  }
  .view-detail 25%, .view-detail 75% {
    opacity: 0;
  }
}
```
