### ISSUE TITLE
Allow functions called from property's value to properly propagate

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1491]
Look at this example:

```
foo(a, b, c)
  a

  background: b

  &:hover
    color: c

.bar
  color: foo(red, lime, blue)
```

Right now it is rendered as

``` CSS
.bar  .bar:hover {
    color: #00f;
  }
 {
  color: ;
}
```

Which is obviously wtf.

I'd say that when we're calling a mixin in a property context, we should place the returned blocks (`&:hover` one) and properties (`background`) outside of the current property, placing only propertyless values (`a` in this example) inside the current property.

With such behaviour example above should be rendered as

``` CSS
.bar {
  color: #f00;
  background: #0f0;
}
.bar:hover {
  color: #00f;
}
```
