### ISSUE TITLE
Fix `@extend`ing in block mixins

### ISSUE THREAD

**Issue by Ser-Gen** [stylus/stylus#1507]
Right now this code

``` css
hocus()
  &:hover,
  &:focus
    {block}

.fw-b
  font-weight: bold

.main
  +hocus()
    @extend .fw-b
    color: #333
```

renders as

``` css
.fw-b,
.main {
  font-weight: bold;
}
.main:hover,
.main:focus {
  color: #333;
}
```

To prevent this I need to add a parent selector:

``` css
.main
  +hocus()
    &
      @extend .fw-b
      color: #333
```

That code renders properly:

``` css
.fw-b,
.main:hover,
.main:focus {
  font-weight: bold;
}
.main:hover,
.main:focus {
  color: #333;
}
```

It would be cool if `&` would not be necessary.
