### ISSUE TITLE
Invalid line number on error

### ISSUE THREAD

**Issue by robhrt7** [stylus/stylus#1542]
There's an error on second line of this CSS, and the error output show right result with this CSS:

``` css
.stub-img__photo120
    {
    display: inline-block;
    }

.dsa,.dsa,.dsa, .dsda{
    1colo1: red;
    }
```

But when we add line breaks after CSS selector parts, error output become unexpected, givig false error line number. Seems like Stylus expects that selector could be set only in one line. 

``` css
.stub-img__photo120
    {
    display: inline-block;
    }

.dsa,
.dsa,
.dsa, 
.dsda{
    1colo1: red;
    }
```

```
ParseError: aprofile/aprofile.css:5
   1| .stub-img__photo120
   2|     {
   3|     display: inline-block;
   4|     }
 > 5|
   6| .dsa,
   7| .dsa,
   8| .dsa,
```
