### ISSUE TITLE
Treatment of undefined `$` idents in values

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1547]
There are a bunch of issues where people want some control over how the undefined keywords and/or values should be treated.

While nothing could be done to regular idents, as this would mean we would need to store all the possible keywords from CSS, we could allow some options on how to treat undefined values starting with `$`.

I can think of those possible values for such option:

## `pass`

Default, the undefined variables like `$bar` would be treated literally as idents.

``` Sass
.foo
  height: 10px
  width: $bar
```

Would render like

``` CSS
.foo {
  height: 10px;
  width: $bar;
}
```

## `error`

Throw error when there is an undefined variable as the value of the prop.

``` Sass
.foo
  width: $bar
```

Would throw an error.

## `skip-property`

Skip the whole property if there is an undefined `$bar` inside its values.

``` Sass
.foo
  height: 10px
  width: $bar
```

would render like

``` CSS
.foo {
  height: 10px;
}
```
## `skip-value`

Skip only the given undefined ident (we should make sure that if there would be two commas one after another in the output, we should make sure there would be only one).

``` Sass
.foo
  background: #fff $bar
```

would render like

``` CSS
.foo {
  background: #fff;
}
```

and 

``` Sass
.foo
  background: url('foo1.png'),
              $bar,
              url('foo3.png')
```

would render like

``` CSS
.foo {
  background: url("foo1.png"), url("foo3.png");
}
```

- - -

That's just a proposal, I'm not sure we need all those cases, for example `skip-value` seems a bit overhead, but maybe there are people who would like this behaviour? Feel free to left your comments and how you'd like Stylus to treat the undefined variables which names start with `$`.
