### ISSUE TITLE
Selector misinterpreted as a property: value;

### ISSUE THREAD

**Issue by Bockit** [stylus/stylus#1551]
``` stylus
.hello-world
    .foo
        float right
        width 220px

        figure video
        figure img
            display block
```

Gives the following CSS

``` css
.hello-world .foo {
  float: right;
  width: 220px;
  figure: video;
}
.hello-world .foo figure img {
  display: block;
}
```

You can see figure:video as a property:value where it should be a selector. For those who run across this problem, an easy fix is to use a comma in your selector list.
