### ISSUE TITLE
0.46.0 introduced some inconsistencies with the Root Reference selector

### ISSUE THREAD

**Issue by zspecza** [stylus/stylus#1572]
I'm not entirely sure where in 0.46.0 this broke.

Here's a snippet of Stylus:

``` sass
_modernizr(features, declaration, support)
  selector = support ? '' : ('.no-js ' + selector())
  for feature in features
    selector += support ? ('.' + feature) : (', .no-' + feature + ' ' + selector())
  selector += (' ' + selector()) if support
  /{selector}
    {declaration}

yep()
  _modernizr(arguments, block, true)

nope()
  _modernizr(arguments, block, false)

.test
  +yep(csstransforms csstransforms3d)
    transform: translate3d(100px, 0, 0)
  +nope(csstransforms csstransforms3d)
    left: 100px
```

Here's what this snippet compiles to in `0.45.x`:

``` css
.csstransforms.csstransforms3d .test {
  transform: translate3d(100px, 0, 0);
}
.no-js .test,
.no-csstransforms .test,
.no-csstransforms3d .test {
  left: 100px;
}
```

Here's what it compiles to in `0.46.0`:

``` css
.csstransforms.csstransforms3d .test {
  transform: translate3d(100px, 0, 0);
}
.no-js .test,
.test .no-csstransforms .test,
.test .no-csstransforms3d .test {
  left: 100px;
}
```
