### ISSUE TITLE
duplicate keyframe declarations

### ISSUE THREAD

**Issue by yocontra** [stylus/stylus#1579]
I have a file with all of my animations declared that is used by some other files. It basically looks like this:

```
  @keyframes popin
    from
      transform: scale(0)
    to
      transform: scale(1)

  @keyframes popout
    from
      transform: scale(1)
    to
      transform: scale(0)

  @keyframes fadein
    from
      opacity: 0
    to
      opacity: 1
```

and after being `@require`d by multiple files, the output CSS looks like this

``` css
@-moz-keyframes popin {
  from {
    transform: scale(0);
  }
  to {
    transform: scale(1);
  }
}
@-webkit-keyframes popin {
  from {
    transform: scale(0);
  }
  to {
    transform: scale(1);
  }
}
@-o-keyframes popin {
  from {
    transform: scale(0);
  }
  to {
    transform: scale(1);
  }
}
@keyframes popin {
  from {
    transform: scale(0);
  }
  to {
    transform: scale(1);
  }
}
@-moz-keyframes popout {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(0);
  }
}
@-webkit-keyframes popout {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(0);
  }
}
@-o-keyframes popout {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(0);
  }
}
@keyframes popout {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(0);
  }
}
@-moz-keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@-webkit-keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@-o-keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@-moz-keyframes popin {
  from {
    transform: scale(0);
  }
  to {
    transform: scale(1);
  }
}
@-webkit-keyframes popin {
  from {
    transform: scale(0);
  }
  to {
    transform: scale(1);
  }
}
@-o-keyframes popin {
  from {
    transform: scale(0);
  }
  to {
    transform: scale(1);
  }
}
@keyframes popin {
  from {
    transform: scale(0);
  }
  to {
    transform: scale(1);
  }
}
@-moz-keyframes popout {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(0);
  }
}
@-webkit-keyframes popout {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(0);
  }
}
@-o-keyframes popout {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(0);
  }
}
@keyframes popout {
  from {
    transform: scale(1);
  }
  to {
    transform: scale(0);
  }
}
@-moz-keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@-webkit-keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@-o-keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
```

Is there any way to strictly import a file one time?
