### ISSUE TITLE
Stylus failing to handle `::shadow foo` selectors

### ISSUE THREAD

**Issue by ghost** [stylus/stylus#1607]
```
node
  bar
    background green

    paper-input::shadow .color
      background red
```

yields

``` css
node bar {
  background: #008000;
paper-input
}
node bar :shadow .color {
  background: #f00;
}
```

Note that this seems to be an issue having more parts of a selector after a `:`

Work-around for anyone else having this issue:

```
paper-input::shadow
  .color
    background red
```
