### ISSUE TITLE
`/deep/` selector doesn't work as the beginning of a selector

### ISSUE THREAD

**Issue by zyklus** [stylus/stylus#1624]
This is part of shadow-dom

```css
foo /deep/
	color red

	/deep/
		color red
```

expected:
```css
foo /deep/ {
  color: #f00;
}
foo /deep/ /deep/ {
  color: #f00;
}
```

actual:
```css
foo /deep/ {
  color: #f00;
}
deep/ {
  color: #f00;
}
```

Temporary work-around for anyone else having this issue:

```css
foo /deep/
	color red

	& /deep/
		color red
```
