### ISSUE TITLE
Mixin with the same name as the value of a variable

### ISSUE THREAD

**Issue by Ser-Gen** [stylus/stylus#1631]
I have variable and need to construct mixin with its value:

``` sass
$param = 'color'

{$param}()
  color green

.foo
  color red
```

It's renders as

``` css
color() {
  color: #008000;
}
.foo {
  color: #f00;
}
```

But I need

``` css
.foo {
  color: #008000;
}
```

How can I get it?
