### ISSUE TITLE
@import-ing a stylus file with a loop in it results in only outputing contents of said loop

### ISSUE THREAD

**Issue by izeau** [stylus/stylus#1641]
I have found this really weird bug… **Sometimes**, using `stylus *.styl && cat test2.css` (or `stylus . && cat test2.css` outputs an erroneous result, where only contents of a loop in @import-ed file are present. However, using `stylus test2.styl && cat test2.css` produces a normal result. Can you reproduce this bug? FWIW, it happens in `gulp-stylus` as well (stevelacy/gulp-stylus#68).
- stylus: 0.47.3

---
###### Source files

``` stylus
// test1.styl
a
  color red

for i in (1..3)
  b
    color green

c
  color blue
```

``` stylus
// test2.styl
@import "test1" // or @import "./test1", same result
```

---
###### Result

``` css
/* test1.css */
a {
  color: #f00;
}
b {
  color: #008000;
}
b {
  color: #008000;
}
b {
  color: #008000;
}
c {
  color: #00f;
}
```

``` css
/* test2.css */
b {
  color: #008000;
}
b {
  color: #008000;
}
b {
  color: #008000;
}
```

---
###### Expected result

``` css
/* test2.css */
a {
  color: #f00;
}
b {
  color: #008000;
}
b {
  color: #008000;
}
b {
  color: #008000;
}
c {
  color: #00f;
}
```
