### ISSUE TITLE
BUG: 0.47.3 not interpolating in @media

### ISSUE THREAD

**Issue by DavidSouther** [stylus/stylus#1642]
``` stylus
$screen-md-max = 991px
$screen-lg-min = 992px

.Page
    > main[role="main"]
        display flex

    @media( min-width: $screen-lg-min )
        > main[role="main"]
            flex-direction row
            max-width $screen-md-max
```

Line 8 above, line 4 below (or do I have the syntax wrong?

``` css
.Page > main[role="main"] {
  display: flex;
}
@media( min-width: $screen-lg-min ) {
  .Page > main[role="main"] {
    flex-direction: row;
    max-width: 991px;
  }
}
```
