### ISSUE TITLE
Semicolon sensitive bug

### ISSUE THREAD

**Issue by xnuk** [stylus/stylus#1644]
```
menus={
    twitter:{background:#55acee url('./img/twitter.png')},
    gmail:{background:#d14836 url('./img/gmail.png')},
    profile:{background:#ff4567 url('./img/xnuk.png')}
}

for i,v in menus
    .{i}
        background v['background']
        background-repeat no-repeat
        background-position center
```

Does not work, but when I add semicolon at end of 9th line:

```
        background v['background'];
```

It works.

For your information, rendered result:

``` css
.twitter {
  background: #55acee url("./img/twitter.png");
  background-repeat: no-repeat;
  background-position: center;
}
.gmail {
  background: #d14836 url("./img/gmail.png");
  background-repeat: no-repeat;
  background-position: center;
}
.profile {
  background: #ff4567 url("./img/xnuk.png");
  background-repeat: no-repeat;
  background-position: center;
}
```
