### ISSUE TITLE
Incorrect property lookup

### ISSUE THREAD

**Issue by ghost** [stylus/stylus#1645]
Hi! It seems that I found a bug

Input:

```
breakpoint($point)
    if ($point == lg)
        @media only screen and (min-width: 960px)
            {block}

div
    padding-left 10px
    +breakpoint(lg)
        padding-left 20px
        padding-right @padding-left
```

Expected output:

``` css
div {
  padding-left: 15px;
}
@media only screen and (min-width: 960px){
  div {
    padding-left: 20px;
    padding-right: 20px;
  }
}
```

Actual output:

``` css
div {
  padding-left: 15px;
}
@media only screen and (min-width: 960px) {
  div {
    padding-left: 20px;
    padding-right: 15px;
  }
}
```
