### ISSUE TITLE
:host selector for Shadow Dom needs parenthesis

### ISSUE THREAD

**Issue by nicola** [stylus/stylus#1657]
Something like this:

``` css
:host {
  &([default]) {
    &([disabled]) {
      background-color: #fff;
    }
  }
}
```

compiles into: 

``` css
:host([default])([disabled]) {
  background-color: true;
}
```

While it should preserve parenthesis:

``` css
:host([default][disabled]) {
  background-color: true;
}
```

Any idea or will this be eventually supported?
