### ISSUE TITLE
@extend under @media query with breaks multi-level selectors

### ISSUE THREAD

**Issue by donut** [stylus/stylus#1658]
When there is a multilevel selector under a `@media` query that uses `@extend` the full selector is added but then so is the deepest level of the selector without its parents. For example,

``` stylus
$test-thing
  display none

$test-thang
  visibility hidden

#thing
  .blurg
    @extends $test-thing

@media only screen
  #thing
    .blurg
      @extends $test-thang
  #thing .goomba
    @extends $test-thang
```

complies to

``` css
#thing .blurg {
  display: none;
}
#thing .blurg,
#thing .goomba,
.blurg {
  visibility: hidden;
}
```

Note the naked `.blurg` in the second set of selectors. It should be prefixed with `#thing` but it's not.

This is with Stylus 0.47.3.
