### ISSUE TITLE
v0.46 broke this valid stylesheet (Object &:link has no method 'clone')

### ISSUE THREAD

**Issue by feross** [stylus/stylus#1660]
This stylus code used to work in v0.45.1, but it throws an error in v0.46:

``` css
LINK = '&:link, &:visited'

ul
  &.left
    li
      a
        {LINK}
          color: BLUE
          @media only screen and (max-width: 699px)
            border-right: 0 

```

The error is:

```
/Users/feross/code/stylus/bin/stylus:607
              throw err;
                    ^
TypeError: test.styl:11
    7|         {LINK}
    8|           color: BLUE
    9|           @media only screen and (max-width: 699px)
   10|             border-right: 0 
 > 11| 

Object &:link has no method 'clone'

    at /Users/feross/code/stylus/lib/nodes/selector.js:69:66
    at Array.map (native)
    at Selector.clone (/Users/feross/code/stylus/lib/nodes/selector.js:69:34)
    at /Users/feross/code/stylus/lib/nodes/group.js:86:21
    at Array.forEach (native)
    at Group.clone (/Users/feross/code/stylus/lib/nodes/group.js:85:14)
    at Normalizer.bubble (/Users/feross/code/stylus/lib/visitor/normalizer.js:116:30)
    at Normalizer.visitMedia (/Users/feross/code/stylus/lib/visitor/normalizer.js:248:8)
    at Normalizer.Visitor.visit (/Users/feross/code/stylus/lib/visitor/index.js:28:40)
    at Normalizer.visitBlock (/Users/feross/code/stylus/lib/visitor/normalizer.js:167:25)
```

I used git bisect and narrowed down the issue to this commit: 8a7f3bc3c773fae403ff19075353291bb651c655 by @Panya 

I don't have the experience to fix the issue, but I hope that my work isolating the faulty commit is useful.
