### ISSUE TITLE
non-quoted base64 images fail in url()

### ISSUE THREAD

**Issue by lesanra** [stylus/stylus#1665]
``` css
.image
{
    background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjxzdmcgd2lkdGg9IjI5cHgiIGhlaWdodD0iMzJweCIgdmlld0JveD0iMCAwIDI5IDMyIiB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHhtbG5zOnNrZXRjaD0iaHR0cDovL3d3dy5ib2hlbWlhbmNvZGluZy5jb20vc2tldGNoL25zIj4KICAgIDx0aXRsZT5TbGljZSAxPC90aXRsZT4KICAgIDxkZXNjcmlwdGlvbj5DcmVhdGVkIHdpdGggU2tldGNoIChodHRwOi8vd3d3LmJvaGVtaWFuY29kaW5nLmNvbS9za2V0Y2gpPC9kZXNjcmlwdGlvbj4KICAgIDxkZWZzPjwvZGVmcz4KICAgIDxnIGlkPSJQYWdlLTEiIHN0cm9rZT0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIxIiBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHNrZXRjaDp0eXBlPSJNU1BhZ2UiPgogICAgICAgIDxnIGlkPSJ0b3BtZW51X19zdWJpdGVtIiBza2V0Y2g6dHlwZT0iTVNMYXllckdyb3VwIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxLjAwMDAwMCwgMC4wMDAwMDApIiBmaWxsPSIjRkYwMDAwIj4KICAgICAgICAgICAgPGcgaWQ9Ikdyb3VwIiBza2V0Y2g6dHlwZT0iTVNTaGFwZUdyb3VwIj4KICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0yMy4wMTMsMTUuOTkzIEMyMy43NTIsMTUuMjY2IDI0LjQyNCwxNC41MzggMjQuOTk2LDEzLjgyNCBDMjcuNzUxLDEwLjM3OSAyNy41MDksOC4zODUgMjYuODIxLDcuMzE4IEMyNi4zODUsNi42NDMgMjUuNDI4LDUuODM5IDIzLjMzNyw1LjgzOSBDMjEuOTYsNS44MzkgMjAuMjUzLDYuMjA0IDE4LjM4Niw2Ljg0MyBDMTcuNDEyLDIuODYgMTUuNzM4LDAgMTMuMzkzLDAgQzExLjA1MywwIDkuMzgyLDIuODQ2IDguNDA2LDYuODE0IEM2LjUzOSw2LjE3IDQuODMyLDUuODAxIDMuNDU2LDUuODAxIEMxLjM4Niw1LjgwMSAwLjQzMyw2LjU5OCAtMC4wMDIsNy4yNjggQy0xLjM5Miw5LjQwNSAwLjQ4LDEyLjcyIDMuNzczLDE1Ljk2NiBDMy4wMzQsMTYuNjkzIDIuMzYyLDE3LjQyIDEuNzkxLDE4LjEzNSBDLTAuOTY0LDIxLjU4IC0wLjcyMiwyMy41NzQgLTAuMDM0LDI0LjY0MSBDMC40MDIsMjUuMzE2IDEuMzU5LDI2LjEyIDMuNDUsMjYuMTIgTDMuNDUxLDI2LjEyIEM0LjgyNywyNi4xMiA2LjUzMywyNS43NTUgOC40LDI1LjExNyBDOS4zNzUsMjkuMDk5IDExLjA0OSwzMS45NTkgMTMuMzk0LDMxLjk1OSBDMTUuNzM0LDMxLjk1OSAxNy40MDUsMjkuMTEzIDE4LjM4MSwyNS4xNDUgQzIwLjI0OSwyNS43ODkgMjEuOTU1LDI2LjE1OCAyMy4zMzIsMjYuMTU4IEMyNS40MDEsMjYuMTU4IDI2LjM1NCwyNS4zNjEgMjYuNzg5LDI0LjY5MSBDMjguMTc4LDIyLjU1MyAyNi4zMDYsMTkuMjM5IDIzLjAxMywxNS45OTMgTDIzLjAxMywxNS45OTMgWiBNMjMuMzM4LDcuNzkxIEMyNC4yODIsNy43OTEgMjQuOTM2LDcuOTk4IDI1LjE4LDguMzc2IEMyNS41MjQsOC45MSAyNS4yODMsMTAuMzM4IDIzLjQ3MSwxMi42MDQgQzIyLjkzLDEzLjI4IDIyLjI4OSwxMy45NyAyMS41ODIsMTQuNjYyIEMyMC44NTUsMTQuMDI0IDIwLjA4MywxMy4zOTYgMTkuMjc3LDEyLjc4NyBDMTkuMTc5LDExLjQwMSAxOS4wMiwxMC4wNDUgMTguNzk2LDguNzY3IEMyMC41NCw4LjE1IDIyLjExNyw3Ljc5MSAyMy4zMzgsNy43OTEgTDIzLjMzOCw3Ljc5MSBaIE0xNS41ODYsMTkuMzc5IEMxNC44NTUsMTkuODUxIDE0LjExOSwyMC4yODQgMTMuMzg0LDIwLjY5NyBDMTIuNjUxLDIwLjI4MSAxMS45MTYsMTkuODQ1IDExLjE4NywxOS4zNzEgQzEwLjU1OSwxOC45NjMgOS45NzMsMTguNTUyIDkuNDA1LDE4LjE0MiBDOS4zNywxNy40NDIgOS4zNDYsMTYuNzI3IDkuMzQ2LDE1Ljk3OSBDOS4zNDYsMTUuMjI3IDkuMzcsMTQuNTA4IDkuNDA1LDEzLjgwNSBDOS45ODYsMTMuMzg4IDEwLjU4LDEyLjk3NyAxMS4xOTksMTIuNTc4IEMxMS45MywxMi4xMDYgMTIuNjY3LDExLjY3MyAxMy40MDIsMTEuMjYgQzE0LjEzNSwxMS42NzYgMTQuODcsMTIuMTEyIDE1LjU5OSwxMi41ODYgQzE2LjIyNiwxMi45OTQgMTYuODEyLDEzLjQwNCAxNy4zOCwxMy44MTQgQzE3LjQxNSwxNC41MTQgMTcuNDM5LDE1LjIzIDE3LjQzOSwxNS45NzkgQzE3LjQzOSwxNi43MzEgMTcuNDE1LDE3LjQ1IDE3LjM4LDE4LjE1MiBDMTYuNzk5LDE4LjU2OSAxNi4yMDUsMTguOTggMTUuNTg2LDE5LjM3OSBMMTUuNTg2LDE5LjM3OSBaIE0xNy40ODksMjAuMzQ2IEMxNy4zOTIsMjEuMjAyIDE3LjI3NCwyMi4wMTQgMTcuMTQzLDIyLjc5NCBDMTYuNDczLDIyLjUwMiAxNS43OTYsMjIuMTg1IDE1LjEwNywyMS44NDUgQzE1LjY2MSwyMS41MTIgMTYuMjE1LDIxLjE4NSAxNi43NjYsMjAuODI5IEMxNy4wMTIsMjAuNjcxIDE3LjI0NywyMC41MDcgMTcuNDg5LDIwLjM0NiBMMTcuNDg5LDIwLjM0NiBaIE0xMS44MTYsMjEuODc3IEMxMS4wNDIsMjIuMjU2IDEwLjI4MSwyMi42MDggOS41MjgsMjIuOTM0IEM5LjM4MSwyMi4wNTYgOS4yNDksMjEuMTQzIDkuMTM5LDIwLjE4IEM5LjQwNCwyMC4zNTggOS42NjYsMjAuNTQxIDkuOTM0LDIwLjcxNSBDMTAuNTYsMjEuMTIzIDExLjE4OCwyMS40OTcgMTEuODE2LDIxLjg3NyBMMTEuODE2LDIxLjg3NyBaIE04LjA3MSwxNy43MjQgQzcuMzUyLDE3LjEzMSA2LjY1MywxNi41NDEgNS45ODEsMTUuOTU1IEM2LjY1NiwxNS4zNzIgNy4zNjQsMTQuNzkzIDguMDcyLDE0LjIxNCBDOC4wNjQsMTQuODA5IDguMDQzLDE1LjQwMyA4LjA0MywxNS45OTggQzguMDQzLDE2LjU3NCA4LjA2MywxNy4xNDggOC4wNzEsMTcuNzI0IEw4LjA3MSwxNy43MjQgWiBNOS4xMzQsMTEuNzggQzkuMjQ1LDEwLjgwNyA5LjM3OSw5Ljg4MyA5LjUyOCw4Ljk5NyBDMTAuMjg5LDkuMzMgMTEuMDYsOS42ODkgMTEuODQzLDEwLjA3NiBDMTEuMjEzLDEwLjQ1NCAxMC41ODMsMTAuODI3IDkuOTU2LDExLjIzMiBDOS42NzcsMTEuNDEgOS40MDksMTEuNTk3IDkuMTM0LDExLjc4IEw5LjEzNCwxMS43OCBaIE0xNC45ODgsMTAuMDg1IEMxNS43NTIsOS43MTIgMTYuNTAzLDkuMzY0IDE3LjI0NSw5LjA0MyBDMTcuMzksOS45MDkgMTcuNTIxLDEwLjgxIDE3LjYyOCwxMS43NiBDMTcuMzY3LDExLjU4NSAxNy4xMDksMTEuNDA0IDE2Ljg0NSwxMS4yMzMgQzE2LjIyOSwxMC44MyAxNS42MDgsMTAuNDYgMTQuOTg4LDEwLjA4NSBMMTQuOTg4LDEwLjA4NSBaIE0xOC44MzgsMTQuNDQxIEMxOS40NzIsMTQuOTY0IDIwLjA4OSwxNS40ODQgMjAuNjgxLDE2LjAwMSBDMjAuMDg2LDE2LjUxNSAxOS40NjIsMTcuMDI2IDE4LjgzNywxNy41MzYgQzE4Ljg0NCwxNy4wMTIgMTguODYyLDE2LjQ5IDE4Ljg2MiwxNS45NjYgQzE4Ljg2MywxNS40NTggMTguODQ1LDE0Ljk1IDE4LjgzOCwxNC40NDEgTDE4LjgzOCwxNC40NDEgWiBNMTMuMzkzLDEuOTUzIEMxNC40MDIsMS45NTMgMTUuNjg3LDQuMDA0IDE2LjUzNiw3LjU0OCBDMTUuNTE3LDcuOTc0IDE0LjQ3MSw4LjQ2NiAxMy40MDYsOS4wMyBDMTIuMzM0LDguNDU3IDExLjI4Miw3Ljk1NyAxMC4yNTYsNy41MjUgQzExLjEwNSwzLjk5NSAxMi4zODYsMS45NTMgMTMuMzkzLDEuOTUzIEwxMy4zOTMsMS45NTMgWiBNMS42MzQsOC4zMzIgQzEuODc3LDcuOTYgMi41MjQsNy43NTQgMy40NTUsNy43NTQgQzQuNjc1LDcuNzU0IDYuMjUsOC4xMTUgNy45OTQsOC43MzcgQzcuNzY3LDEwLjAxOSA3LjYwNywxMS4zNzkgNy41MDksMTIuNzcgQzYuNjk4LDEzLjM3OSA1LjkzMSwxNCA1LjIxMywxNC42MjcgQzIuMjY5LDExLjcxNiAxLjA0Myw5LjI0MiAxLjYzNCw4LjMzMiBMMS42MzQsOC4zMzIgWiBNMy40NSwyNC4xNjcgTDMuNDUsMjQuMTY3IEMyLjUwNSwyNC4xNjcgMS44NTEsMjMuOTU5IDEuNjA3LDIzLjU4MiBDMS4yNjMsMjMuMDQ4IDEuNTA0LDIxLjYyIDMuMzE2LDE5LjM1NCBDMy44NTcsMTguNjc4IDQuNDk4LDE3Ljk4OCA1LjIwNCwxNy4yOTYgQzUuOTMxLDE3LjkzNCA2LjcwMiwxOC41NjIgNy41MDgsMTkuMTcgQzcuNjA2LDIwLjU1NiA3Ljc2NSwyMS45MTMgNy45OSwyMy4xOTEgQzYuMjQ2LDIzLjgwOSA0LjY3LDI0LjE2NyAzLjQ1LDI0LjE2NyBMMy40NSwyNC4xNjcgWiBNMTMuMzkzLDMwLjAwNSBDMTIuMzg0LDMwLjAwNSAxMS4wOTksMjcuOTU1IDEwLjI1LDI0LjQxMSBDMTEuMjY5LDIzLjk4NSAxMi4zMTYsMjMuNDkzIDEzLjM4MSwyMi45MjggQzE0LjQ1MiwyMy41MDEgMTUuNTA1LDI0LjAwMSAxNi41MywyNC40MzMgQzE1LjY4MiwyNy45NjMgMTQuMzk5LDMwLjAwNSAxMy4zOTMsMzAuMDA1IEwxMy4zOTMsMzAuMDA1IFogTTI1LjE1MSwyMy42MjYgQzI0LjkwOSwyMy45OTkgMjQuMjYzLDI0LjIwNCAyMy4zMzEsMjQuMjA0IEMyMi4xMTEsMjQuMjA0IDIwLjUzNSwyMy44NDMgMTguNzkxLDIzLjIyIEMxOS4wMTcsMjEuOTM5IDE5LjE3OCwyMC41NzggMTkuMjc2LDE5LjE4NyBDMjAuMDg3LDE4LjU3OCAyMC44NTQsMTcuOTU3IDIxLjU3MiwxNy4zMjkgQzI0LjUxNywyMC4yNDMgMjUuNzQzLDIyLjcxNiAyNS4xNTEsMjMuNjI2IEwyNS4xNTEsMjMuNjI2IFoiIGlkPSJTaGFwZSI+PC9wYXRoPgogICAgICAgICAgICAgICAgPGNpcmNsZSBpZD0iT3ZhbCIgY3g9IjEzLjE5NCIgY3k9IjE2LjE5NCIgcj0iMS4xOTQiPjwvY2lyY2xlPgogICAgICAgICAgICA8L2c+CiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4=);
}
```

results in

```
/Users/lesanra/sites/market/proto/node_modules/stylus/bin/stylus:607
              throw err;
                    ^
ParseError: tst.css:3
   1| .image
   2| {
 > 3|     background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjxzdmcgd2lkdGg9IjI5cHgiIGhlaWdodD0iMzJweCIgdmlld0JveD0iMCAwIDI5IDMyIiB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHhtbG5zOnNrZXRjaD0iaHR0cDovL3d3dy5ib2hlbWlhbmNvZGluZy5jb20vc2tldGNoL25zIj4KICAgIDx0aXRsZT5TbGljZSAxPC90aXRsZT4KICAgIDxkZXNjcmlwdGlvbj5DcmVhdGVkIHdpdGggU2tldGNoIChodHRwOi8vd3d3LmJvaGVtaWFuY29kaW5nLmNvbS9za2V0Y2gpPC9kZXNjcmlwdGlvbj4KICAgIDxkZWZzPjwvZGVmcz4KICAgIDxnIGlkPSJQYWdlLTEiIHN0cm9rZT0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIxIiBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHNrZXRjaDp0eXBlPSJNU1BhZ2UiPgogICAgICAgIDxnIGlkPSJ0b3BtZW51X19zdWJpdGVtIiBza2V0Y2g6dHlwZT0iTVNMYXllckdyb3VwIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxLjAwMDAwMCwgMC4wMDAwMDApIiBmaWxsPSIjRkYwMDAwIj4KICAgICAgICAgICAgPGcgaWQ9Ikdyb3VwIiBza2V0Y2g6dHlwZT0iTVNTaGFwZUdyb3VwIj4KICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0yMy4wMTMsMTUuOTkzIEMyMy43NTIsMTUuMjY2IDI0LjQyNCwxNC41MzggMjQuOTk2LDEzLjgyNCBDMjcuNzUxLDEwLjM3OSAyNy41MDksOC4zODUgMjYuODIxLDcuMzE4IEMyNi4zODUsNi42NDMgMjUuNDI4LDUuODM5IDIzLjMzNyw1LjgzOSBDMjEuOTYsNS44MzkgMjAuMjUzLDYuMjA0IDE4LjM4Niw2Ljg0MyBDMTcuNDEyLDIuODYgMTUuNzM4LDAgMTMuMzkzLDAgQzExLjA1MywwIDkuMzgyLDIuODQ2IDguNDA2LDYuODE0IEM2LjUzOSw2LjE3IDQuODMyLDUuODAxIDMuNDU2LDUuODAxIEMxLjM4Niw1LjgwMSAwLjQzMyw2LjU5OCAtMC4wMDIsNy4yNjggQy0xLjM5Miw5LjQwNSAwLjQ4LDEyLjcyIDMuNzczLDE1Ljk2NiBDMy4wMzQsMTYuNjkzIDIuMzYyLDE3LjQyIDEuNzkxLDE4LjEzNSBDLTAuOTY0LDIxLjU4IC0wLjcyMiwyMy41NzQgLTAuMDM0LDI0LjY0MSBDMC40MDIsMjUuMzE2IDEuMzU5LDI2LjEyIDMuNDUsMjYuMTIgTDMuNDUxLDI2LjEyIEM0LjgyNywyNi4xMiA2LjUzMywyNS43NTUgOC40LDI1LjExNyBDOS4zNzUsMjkuMDk5IDExLjA0OSwzMS45NTkgMTMuMzk0LDMxLjk1OSBDMTUuNzM0LDMxLjk1OSAxNy40MDUsMjkuMTEzIDE4LjM4MSwyNS4xNDUgQzIwLjI0OSwyNS43ODkgMjEuOTU1LDI2LjE1OCAyMy4zMzIsMjYuMTU4IEMyNS40MDEsMjYuMTU4IDI2LjM1NCwyNS4zNjEgMjYuNzg5LDI0LjY5MSBDMjguMTc4LDIyLjU1MyAyNi4zMDYsMTkuMjM5IDIzLjAxMywxNS45OTMgTDIzLjAxMywxNS45OTMgWiBNMjMuMzM4LDcuNzkxIEMyNC4yODIsNy43OTEgMjQuOTM2LDcuOTk4IDI1LjE4LDguMzc2IEMyNS41MjQsOC45MSAyNS4yODMsMTAuMzM4IDIzLjQ3MSwxMi42MDQgQzIyLjkzLDEzLjI4IDIyLjI4OSwxMy45NyAyMS41ODIsMTQuNjYyIEMyMC44NTUsMTQuMDI0IDIwLjA4MywxMy4zOTYgMTkuMjc3LDEyLjc4NyBDMTkuMTc5LDExLjQwMSAxOS4wMiwxMC4wNDUgMTguNzk2LDguNzY3IEMyMC41NCw4LjE1IDIyLjExNyw3Ljc5MSAyMy4zMzgsNy43OTEgTDIzLjMzOCw3Ljc5MSBaIE0xNS41ODYsMTkuMzc5IEMxNC44NTUsMTkuODUxIDE0LjExOSwyMC4yODQgMTMuMzg0LDIwLjY5NyBDMTIuNjUxLDIwLjI4MSAxMS45MTYsMTkuODQ1IDExLjE4NywxOS4zNzEgQzEwLjU1OSwxOC45NjMgOS45NzMsMTguNTUyIDkuNDA1LDE4LjE0MiBDOS4zNywxNy40NDIgOS4zNDYsMTYuNzI3IDkuMzQ2LDE1Ljk3OSBDOS4zNDYsMTUuMjI3IDkuMzcsMTQuNTA4IDkuNDA1LDEzLjgwNSBDOS45ODYsMTMuMzg4IDEwLjU4LDEyLjk3NyAxMS4xOTksMTIuNTc4IEMxMS45MywxMi4xMDYgMTIuNjY3LDExLjY3MyAxMy40MDIsMTEuMjYgQzE0LjEzNSwxMS42NzYgMTQuODcsMTIuMTEyIDE1LjU5OSwxMi41ODYgQzE2LjIyNiwxMi45OTQgMTYuODEyLDEzLjQwNCAxNy4zOCwxMy44MTQgQzE3LjQxNSwxNC41MTQgMTcuNDM5LDE1LjIzIDE3LjQzOSwxNS45NzkgQzE3LjQzOSwxNi43MzEgMTcuNDE1LDE3LjQ1IDE3LjM4LDE4LjE1MiBDMTYuNzk5LDE4LjU2OSAxNi4yMDUsMTguOTggMTUuNTg2LDE5LjM3OSBMMTUuNTg2LDE5LjM3OSBaIE0xNy40ODksMjAuMzQ2IEMxNy4zOTIsMjEuMjAyIDE3LjI3NCwyMi4wMTQgMTcuMTQzLDIyLjc5NCBDMTYuNDczLDIyLjUwMiAxNS43OTYsMjIuMTg1IDE1LjEwNywyMS44NDUgQzE1LjY2MSwyMS41MTIgMTYuMjE1LDIxLjE4NSAxNi43NjYsMjAuODI5IEMxNy4wMTIsMjAuNjcxIDE3LjI0NywyMC41MDcgMTcuNDg5LDIwLjM0NiBMMTcuNDg5LDIwLjM0NiBaIE0xMS44MTYsMjEuODc3IEMxMS4wNDIsMjIuMjU2IDEwLjI4MSwyMi42MDggOS41MjgsMjIuOTM0IEM5LjM4MSwyMi4wNTYgOS4yNDksMjEuMTQzIDkuMTM5LDIwLjE4IEM5LjQwNCwyMC4zNTggOS42NjYsMjAuNTQxIDkuOTM0LDIwLjcxNSBDMTAuNTYsMjEuMTIzIDExLjE4OCwyMS40OTcgMTEuODE2LDIxLjg3NyBMMTEuODE2LDIxLjg3NyBaIE04LjA3MSwxNy43MjQgQzcuMzUyLDE3LjEzMSA2LjY1MywxNi41NDEgNS45ODEsMTUuOTU1IEM2LjY1NiwxNS4zNzIgNy4zNjQsMTQuNzkzIDguMDcyLDE0LjIxNCBDOC4wNjQsMTQuODA5IDguMDQzLDE1LjQwMyA4LjA0MywxNS45OTggQzguMDQzLDE2LjU3NCA4LjA2MywxNy4xNDggOC4wNzEsMTcuNzI0IEw4LjA3MSwxNy43MjQgWiBNOS4xMzQsMTEuNzggQzkuMjQ1LDEwLjgwNyA5LjM3OSw5Ljg4MyA5LjUyOCw4Ljk5NyBDMTAuMjg5LDkuMzMgMTEuMDYsOS42ODkgMTEuODQzLDEwLjA3NiBDMTEuMjEzLDEwLjQ1NCAxMC41ODMsMTAuODI3IDkuOTU2LDExLjIzMiBDOS42NzcsMTEuNDEgOS40MDksMTEuNTk3IDkuMTM0LDExLjc4IEw5LjEzNCwxMS43OCBaIE0xNC45ODgsMTAuMDg1IEMxNS43NTIsOS43MTIgMTYuNTAzLDkuMzY0IDE3LjI0NSw5LjA0MyBDMTcuMzksOS45MDkgMTcuNTIxLDEwLjgxIDE3LjYyOCwxMS43NiBDMTcuMzY3LDExLjU4NSAxNy4xMDksMTEuNDA0IDE2Ljg0NSwxMS4yMzMgQzE2LjIyOSwxMC44MyAxNS42MDgsMTAuNDYgMTQuOTg4LDEwLjA4NSBMMTQuOTg4LDEwLjA4NSBaIE0xOC44MzgsMTQuNDQxIEMxOS40NzIsMTQuOTY0IDIwLjA4OSwxNS40ODQgMjAuNjgxLDE2LjAwMSBDMjAuMDg2LDE2LjUxNSAxOS40NjIsMTcuMDI2IDE4LjgzNywxNy41MzYgQzE4Ljg0NCwxNy4wMTIgMTguODYyLDE2LjQ5IDE4Ljg2MiwxNS45NjYgQzE4Ljg2MywxNS40NTggMTguODQ1LDE0Ljk1IDE4LjgzOCwxNC40NDEgTDE4LjgzOCwxNC40NDEgWiBNMTMuMzkzLDEuOTUzIEMxNC40MDIsMS45NTMgMTUuNjg3LDQuMDA0IDE2LjUzNiw3LjU0OCBDMTUuNTE3LDcuOTc0IDE0LjQ3MSw4LjQ2NiAxMy40MDYsOS4wMyBDMTIuMzM0LDguNDU3IDExLjI4Miw3Ljk1NyAxMC4yNTYsNy41MjUgQzExLjEwNSwzLjk5NSAxMi4zODYsMS45NTMgMTMuMzkzLDEuOTUzIEwxMy4zOTMsMS45NTMgWiBNMS42MzQsOC4zMzIgQzEuODc3LDcuOTYgMi41MjQsNy43NTQgMy40NTUsNy43NTQgQzQuNjc1LDcuNzU0IDYuMjUsOC4xMTUgNy45OTQsOC43MzcgQzcuNzY3LDEwLjAxOSA3LjYwNywxMS4zNzkgNy41MDksMTIuNzcgQzYuNjk4LDEzLjM3OSA1LjkzMSwxNCA1LjIxMywxNC42MjcgQzIuMjY5LDExLjcxNiAxLjA0Myw5LjI0MiAxLjYzNCw4LjMzMiBMMS42MzQsOC4zMzIgWiBNMy40NSwyNC4xNjcgTDMuNDUsMjQuMTY3IEMyLjUwNSwyNC4xNjcgMS44NTEsMjMuOTU5IDEuNjA3LDIzLjU4MiBDMS4yNjMsMjMuMDQ4IDEuNTA0LDIxLjYyIDMuMzE2LDE5LjM1NCBDMy44NTcsMTguNjc4IDQuNDk4LDE3Ljk4OCA1LjIwNCwxNy4yOTYgQzUuOTMxLDE3LjkzNCA2LjcwMiwxOC41NjIgNy41MDgsMTkuMTcgQzcuNjA2LDIwLjU1NiA3Ljc2NSwyMS45MTMgNy45OSwyMy4xOTEgQzYuMjQ2LDIzLjgwOSA0LjY3LDI0LjE2NyAzLjQ1LDI0LjE2NyBMMy40NSwyNC4xNjcgWiBNMTMuMzkzLDMwLjAwNSBDMTIuMzg0LDMwLjAwNSAxMS4wOTksMjcuOTU1IDEwLjI1LDI0LjQxMSBDMTEuMjY5LDIzLjk4NSAxMi4zMTYsMjMuNDkzIDEzLjM4MSwyMi45MjggQzE0LjQ1MiwyMy41MDEgMTUuNTA1LDI0LjAwMSAxNi41MywyNC40MzMgQzE1LjY4MiwyNy45NjMgMTQuMzk5LDMwLjAwNSAxMy4zOTMsMzAuMDA1IEwxMy4zOTMsMzAuMDA1IFogTTI1LjE1MSwyMy42MjYgQzI0LjkwOSwyMy45OTkgMjQuMjYzLDI0LjIwNCAyMy4zMzEsMjQuMjA0IEMyMi4xMTEsMjQuMjA0IDIwLjUzNSwyMy44NDMgMTguNzkxLDIzLjIyIEMxOS4wMTcsMjEuOTM5IDE5LjE3OCwyMC41NzggMTkuMjc2LDE5LjE4NyBDMjAuMDg3LDE4LjU3OCAyMC44NTQsMTcuOTU3IDIxLjU3MiwxNy4zMjkgQzI0LjUxNywyMC4yNDMgMjUuNzQzLDIyLjcxNiAyNS4xNTEsMjMuNjI2IEwyNS4xNTEsMjMuNjI2IFoiIGlkPSJTaGFwZSI+PC9wYXRoPgogICAgICAgICAgICAgICAgPGNpcmNsZSBpZD0iT3ZhbCIgY3g9IjEzLjE5NCIgY3k9IjE2LjE5NCIgcj0iMS4xOTQiPjwvY2lyY2xlPgogICAgICAgICAgICA8L2c+CiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4=);
   4| }
   5|

expected ")", got ";"

    at Parser.error (/Users/lesanra/sites/market/proto/node_modules/stylus/lib/parser.js:257:11)
    at Parser.expect (/Users/lesanra/sites/market/proto/node_modules/stylus/lib/parser.js:285:12)
    at Parser.url (/Users/lesanra/sites/market/proto/node_modules/stylus/lib/parser.js:1546:10)
    at Parser.functionCall (/Users/lesanra/sites/market/proto/node_modules/stylus/lib/parser.js:1557:52)
    at Parser.primary (/Users/lesanra/sites/market/proto/node_modules/stylus/lib/parser.js:2021:18)
    at Parser.member (/Users/lesanra/sites/market/proto/node_modules/stylus/lib/parser.js:1914:21)
    at Parser.subscript (/Users/lesanra/sites/market/proto/node_modules/stylus/lib/parser.js:1888:21)
    at Parser.unary (/Users/lesanra/sites/market/proto/node_modules/stylus/lib/parser.js:1879:17)
    at Parser.defined (/Users/lesanra/sites/market/proto/node_modules/stylus/lib/parser.js:1853:21)
    at Parser.multiplicative (/Users/lesanra/sites/market/proto/node_modules/stylus/lib/parser.js:1827:21)
```
