### ISSUE TITLE
Bug with extending selector nesting inside placeholder selector

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1687]
When you're extending a selector that is nested inside the placeholder selector and that matches that one nested selector, the extending won't work. Example:

```
$foo
  .foo
    padding: 0

.foo,
.bar
  @extends $foo .foo
```

Should produce

``` CSS
.foo,
.bar {
  padding: 0;
}
```

However, right now it produces

``` CSS
.bar {
  padding: 0;
}
```

Real life use case: http://stackoverflow.com/questions/25763763/how-to-partial-import-in-stylus as

Here we could solve it using this code:

```
$foo
  @import 'foo'

body
  @extends $foo body
```

But due to this bug it won't work.
