### ISSUE TITLE
Using adjacent sibling selector "+" and parent selector "&" together does not work correctly with @extend

### ISSUE THREAD

**Issue by kristerkari** [stylus/stylus#1691]
Stylus @ dev branch:

With code:

``` stylus
$test {
  color: #fff;
  & + & {
    color: #000;
  }
}

.test1 {
  @extend $test;
}

.test2 {
  @extend $test;
}
```

Expected (what Sass outputs): 

``` css
.test1,
.test2 {
  color: #fff;
}
.test1 + .test1,
.test2 + .test1,
.test1 + .test2,
.test2 + .test2 {
  color: #000;
}
```

Actual:

``` css
.test1,
.test2 {
  color: #fff;
}
.test1 + .test1,
.test2 + .test2 {
  color: #000;
}
```

Same thing without using a placeholder:

``` stylus
.test3 {
  color: #fff;
  & + & {
    color: #000;
  }
}

.test4 {
  @extend .test3;
}

.test5 {
  @extend .test3;
}
```

Expected (what Sass outputs):

``` css
.test3,
.test4,
.test5 {
  color: #fff;
}
.test3 + .test3,
.test4 + .test3,
.test5 + .test3,
.test3 + .test4,
.test4 + .test4,
.test5 + .test4,
.test3 + .test5,
.test4 + .test5,
.test5 + .test5 {
  color: #000;
}
```

Actual:

``` css
.test3,
.test4,
.test5 {
  color: #fff;
}
.test3 + .test3,
.test4 + .test4,
.test5 + .test5 {
  color: #000;
}
```
