### ISSUE TITLE
nested media queries with variables

### ISSUE THREAD

**Issue by remitbri** [stylus/stylus#1701]
With 0.49.0, I now have the following problem: nested media queries are looped in reverse order. I.e

``` stylus
.yay
  for j in 8..10
    @media (min-width:unit(1200/16*j/10,em))
      font-size: (j/10)em
```

produces

``` css
@media (min-width: 60em) {
  .yay {
    font-size: 0.8em;
  }
}
@media (min-width: 67.5em) {
  .yay {
    font-size: 0.9em;
  }
}
@media (min-width: 75em) {
  .yay {
    font-size: 1em;
  }
}
```

which is good,

but

``` stylus
.nay
  for j in 8..10
    @media (min-width:unit(1200/16*j/10,em))
      @media (min-height:unit(780/16*j/10,em))
        font-size: (j/10)em

.nope
  @media only screen
    for j in 8..10
      @media (min-width:unit(1200/16*j/10,em))
        font-size: (j/10)em
```

gives

``` css
@media (min-width: 75em) and (min-height: 48.75em) {
  .nay {
    font-size: 1em;
  }
}
@media (min-width: 67.5em) and (min-height: 43.875em) {
  .nay {
    font-size: 0.9em;
  }
}
@media (min-width: 60em) and (min-height: 39em) {
  .nay {
    font-size: 0.8em;
  }
}
@media only screen and (min-width: 75em) {
  .nope {
    font-size: 1em;
  }
}
@media only screen and (min-width: 67.5em) {
  .nope {
    font-size: 0.9em;
  }
}
@media only screen and (min-width: 60em) {
  .nope {
    font-size: 0.8em;
  }
}
```

…which is in reverse order of declaration!
_(The problem does not come from the `for` loop itself. I observed the malfunction on an old template where I couldn't use the loop at the time and had to manually set `j` and repeat the code…)_
