### ISSUE TITLE
Issue with symbols property (@counter-style)

### ISSUE THREAD

**Issue by futekov** [stylus/stylus#1707]
The first example from the [counter styles spec](http://www.w3.org/TR/2014/WD-css-counter-styles-3-20140826/#cyclic-system) doesn't work in Stylus, here's the code:

``` css
@counter-style triangle {
  system: cyclic;
  symbols: ‣;
  suffix: " ";
}
```

The problem is with the unicode symbol (the right-pointing triangle). Tested with Stylus 0.47.1, 0.48.0, and 0.49.0. Sass doesn't mind such symbols.

A workaround is to escape the charater with a `\`, but if this becomes a commonly used feature in CSS it will be very tedious to escape every special character.
