### ISSUE TITLE
Mixin with block and display: block produces invalid output

### ISSUE THREAD

**Issue by jordaaash** [stylus/stylus#1712]
Stylus:

``` css
blockify()
  display block
  { block }

.red
  +blockify()
    background red
```

Invalid output:

``` css
.red {
 {
    background: #f00;
  }
  display: ;
  background: #f00;
}
```

Workaround:

``` css
blockify()
  display unquote('block')
  { block }

.red
  +blockify()
    background red
```

Valid output:

``` css
.red {
  display: block;
  background: #f00;
}
```
