### ISSUE TITLE
Bug with Microsoft filter function.

### ISSUE THREAD

**Issue by trusktr** [stylus/stylus#1726]
I have something like

``` css
            button {
                position: relative;
                color: #0B486B!important;

                filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#d9ffa1', endColorstr='#bad690', GradientType=0 );

                border: 2px solid #053652;
            }
```

Which results in the stylus error

```
stylus:400:132
   396|             button {
   397|                 position: relative;
   398|                 color: #0B486B!important;
   399| 
   400|                 filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#d9ffa1', endColorstr='#bad690', GradientType=0 );
-------------------------------------------------------------------------------------------------------------------------------------------^
   401| 
   402|                 border: 2px solid #053652;
   403|             }

expected "indent", got ";"
```
