### ISSUE TITLE
@scope vs. @media priority nesting

### ISSUE THREAD

**Issue by kuba-kubula** [stylus/stylus#1730]
Say I have a code like this:

```
@scope .basis

body
  color #345

@media print
  body
    color #000

```

Expected output (from my point of view) is:

``` css
.basis body {
  color: #345;
}

@media print {
  .basis body {
    color: #000;
  }
}
```

But instead it writes:

``` css
.basis body {
  color: #345;
}

@media print {
  body {
    color: #000;
  }
}
```

So basically what's missing: `.basis` prepended selector inside the `@media` part.
It's about scope...

Is there any other solution how to prepend ".selector " to the whole compiled CSS, or do I have to throw it into a CSS-parse and change all the selectors there?

_(Note: I used to hack the `compileSelectors` function, but it worked only with 0.43.1, and hence there was a pressure for upgrade - I'm looking for easy solutions)_
