### ISSUE TITLE
Make current-property place nice with +cache

### ISSUE THREAD

**Issue by maruf89** [stylus/stylus#1734]
Using your +media library to set media queries I noticed that using `calc()` inside a media query cache call overrides the non media query variable. I'm almost positive the issue has to do with `current-property` in the calc mixin but I don't know what alternatives exist

**Stylus Markup**

``` styl
/*.top-sec */.sec
        $margin = 8
        $blocks = 3
        display block
        margin 3em auto
        padding-bottom 1em
        border-bottom 1px solid $light-blue-3
        text-align center
        // Notice how width isn't set at all

        +media('lap-and-up')
            border none
            width calc('33.33% - ' + unit(ceil(($margin * 2) / $blocks), 'px'))
            display inline-block
            vertical-align top
            padding 0 em(6)
            margin 0 em($margin) 0 0
```

**Calc Mixin**

``` styl
calc()
    if current-property
        for prefix in vendors
            arguments = unquote(arguments)
            add-property(current-property[0], s('-%s-calc(%s)', prefix, arguments))
        s('calc(%s)', arguments)
    else
        error('calc() must be used within a property')
```

**Browser Output**

``` css
.Tandem .sec {
    display: block;
    margin: 3em auto;
    padding-bottom: 1em;
    border-bottom: 1px solid #9ccee3;
    text-align: center;
    width: -webkit-calc(33.33% - 6px);
    width: -moz-calc(33.33% - 6px);
    width: -ms-calc(33.33% - 6px);
}
```
