### ISSUE TITLE
Bug - expected "indent", got "outdent"

### ISSUE THREAD

**Issue by andres-torres-marroquin** [stylus/stylus#1738]
This code fails.

``` css
$colors = 'red'
$red = red
$background_list = {
    red: $red
}
for $color in $colors
    &.{$color}
        background $background_list[$color]
        color rgba(0, 0, 0, 0.45)
```

I made some research about this bug, and these are the results:

---

This code works (this might be a good workaround for someone), note the semicolon on the `background` line:

``` css
$colors = 'red'
$red = red
$background_list = {
    red: $red
}
for $color in $colors
    &.{$color}
        background $background_list[$color];
        color rgba(0, 0, 0, 0.45)
```

Which compiles correctly into:

``` css
.red {
  background: #f00;
  color: rgba(0,0,0,0.45);
}
```

---

And this one compiles too, but note that the `background` line isn't present: 

``` css
$colors = 'red'
$red = red
$background_list = {
    red: $red
}
for $color in $colors
    &.{$color}
        color rgba(0, 0, 0, 0.45)
```

---

And this is the workaround that I liked better to use for this case:

``` css
$red = red
$background_list = {
    red: $red
}
for $key, $value in $background_list
    &.{$key}
        background $value
        color rgba(0, 0, 0, 0.45)
```

Which compiles correctly into: (expected output)

``` css
.red {
  background: #f00;
  color: rgba(0,0,0,0.45);
}
```
