### ISSUE TITLE
#id selectors starting with [a-f] trip up attribute-value selector interpolation

### ISSUE THREAD

**Issue by maranomynet** [stylus/stylus#1786]
All this seems pretty messed up:

``` less
$bar = baz;
#a[foo="{$bar}"] { margin: 0; }
#g[foo="{$bar}"] { padding: 0; }
```

Results in:

``` css
#a[foo="{$bar}"] { margin: 0; }
#g[foo="baz"] { padding: 0; }
```

`#[a-f]` doesn't interpolate, while `#[g-z]` does.

...but wait, it gets worse, following the first successful interpolation, brace-scopes get messed up, like so:

``` less
$bar = baz;
#a[foo="{$bar}"] { margin: 0; }
#l[foo="{$bar}"] { padding: 0; }
div {
  p[foo="{$bar}"] { border: 0; }
}
```

Results in this error:

```
 2| #a[foo="{$bar}"] { margin: 0; }
 3| #l[foo="{$bar}"] { padding: 0; }
 4| div {
 5|   p[foo="{$bar}"] { border: 0; }
-----------------------------------^
 6| }

unexpected "}"
```

Joy!
