### ISSUE TITLE
/ Selector Not Working

### ISSUE THREAD

**Issue by srsgores** [stylus/stylus#1789]
I am seeking a way to access my root selector within [the context of a modifier](https://gist.github.com/srsgores/1471c8dd1393e679cd5e):

```
$navPadding 1em
.nav
    padding $navPadding
    &-vertical
        ./-items
            white-space normal
```

I might expect the following from this:

```
.nav {
    padding: 1em;
}

.nav-vertical .nav-items {
    white-space: normal;
}
```

But I get this:

```
.nav {
    padding: 1em;
}

.nav-vertical ./-items {
    white-space: normal;
}
```

I have referred to the commit https://github.com/LearnBoost/stylus/pull/1309 and its [spec respectively](), and this appears to be the functionality of `/`.  Perhaps I am misunderstanding, in which case I suggest docs be updated to reflect any of my misunderstandings (it appears that the [Stylus documentation](http://learnboost.github.io/stylus/docs/bifs.html) lacks any info on the `../`, `/` selectors).

**Comment by ommartin** [comment]
Wondering if this is a bug/missing implementation, or am I using the root selector in a wrong way; in the following case the root selector doesn't compile to the actual selector, it just stays "/" in the final CSS code. 

```stylus
.foo
  .bar
    margin-top 10px
    & + /
      margin-top 30px
```

compiles to:

```css
.foo .bar {
  margin-top: 10px;
}
.foo .bar + / {
  margin-top: 30px;
}
```

instead of expected:

```css
.foo .bar {
  margin-top: 10px;
}
.foo .bar + .bar {
  margin-top: 30px;
}
```

Can anyone comment on this? 

Thanks!

**Comment by Panya** [comment]
@ommartin yep, you're using it in a wrong way. The root reference could be used only at the start of a selector to eliminate nesting:
```styl
.foo
   color: red
  /.bar
    color: blue
```
=>
```css
.foo {
  color: #f00;
}
.bar {
  color: #00f;
}
```
The feature you're looking for is `[N]` (Partial reference) that described in #1240:
```styl
.foo
  .bar
    margin-top 10px
    & + &[-1]
      margin-top 30px
```
and it's not implemented yet.
