### ISSUE TITLE
Postpositive `&` doesn't work properly when omitting commas.

### ISSUE THREAD

**Issue by cssmagic** [stylus/stylus#1793]
> Node: v0.10.26
> Stylus: v0.49.3
#### Case 1

Prepositive `&` without comma:

``` css
.test
    &-ok
    &-error
        display block
```

``` css
.test-ok,
.test-error {
    display: block;
}
```
#### Case 2

Postpositive `&` with comma:

``` css
.test
    div&,
    p&
        display block
```

``` css
div.test,
p.test {
    display: block;
}
```
## Failed

Postpositive `&` without comma:
#### Case 1

``` css
.test
    div&
    p&
        display block
```

``` css
.test,
p.test {
    display: block;
}
```
#### Case 2

``` css
.test
    display inline
    div&
    p&
        display block
```

``` css
.test {
    display: inline;
div
}
.test,
p.test {
    display: block;
}
```
