### ISSUE TITLE
Using comma and block but not nest

### ISSUE THREAD

**Issue by teabyii** [stylus/stylus#1794]
Then i use stylus like this code: 

```
$content = 
  .test
    padding 0

#id, .class
  {$content} 
```

It converts to

``` css
#id .test,
.class .test {
  padding: 0;
}
```

But i want to be

``` css
#id, .class .test {
  padding: 0;
}
```

Have a good way? Thanks.
