### ISSUE TITLE
If we use two tags with comma, project build will be falling

### ISSUE THREAD

**Issue by gela-d** [stylus/stylus#1848]
If we have such construction
```css
.a
{
    color: black;
 
    h1,
    h2 
    {
        color: red;
    }
}
 ```
during building we have errors such as
`Cannot read property 'block' of undefined`

If we left only one tag, everything will be ok.
