### ISSUE TITLE
--resolve-url doesn't consider --out option

### ISSUE THREAD

**Issue by doochik** [stylus/stylus#1880]
I have the following dirs structure
```
/src
  /hubs
    common.styl
  /styl
    my.styl
/out
```

common.styl
```
@require '../styl/**'
```

my.styl
```
.a
   background: url('ico.png')
```

Run stylus
```
stylus src/hubs/common.styl -r -o out
```

out/common.css
```css
.a {
  background: url("../styl/ico.png"); // THIS IS BUG
}
```

out/common.css must be
```css
.a {
  background: url("../src/styl/ico.png");
}
```
