### ISSUE TITLE
Consecutive nested @media break bubbling

### ISSUE THREAD

**Issue by maranomynet** [stylus/stylus#1882]
[According to the docs](http://learnboost.github.io/stylus/docs/media.html#nested-media-queries) this code:

```Stylus
@media screen
    .foo
        @media (max-width: 499px)
            width: 200px;
        @media (min-width: 500px)
            width: 50%;
        @media (min-width: 900px)
            width: 25%;
``` 

Should output:

```CSS
@media screen and (max-width: 499px) {
    width: 200px;
}
@media screen and (min-width: 500px) {
    width: 50%;
}
@media screen and (min-width: 900px) {
    width: 25%;
}
```

But instead [outputs](http://learnboost.github.io/stylus/try.html) this weirdness:

```CSS
@media screen {
    @media screen and (max-width: 499px) and (min-width: 500px) {
        .foo .foo {
            width: 50%;
        }
    }
    @media screen and (max-width: 499px) and (min-width: 500px) and (min-width: 900px) {
        .foo .foo {
            width: 25%;
        }
    }
}
@media screen and (max-width: 499px) {
    .foo {
        width: 200px;
    }
}
```
