### ISSUE TITLE
Accessing nested object of imported global values

### ISSUE THREAD

**Issue by tunderdomb** [stylus/stylus#1883]
It seems you can't access nested values of javascript provided globals inside stylus stylesheets.

Using the  javascript API to provide globals like:
```js
stylus("blah", {
  globals: {
    js: {
      hey: {
        ho: "let's go"
      }
    },
    animName: "hello"
  }
})
```
which is digested by: 
```js
function Renderer(str, options) {
  options = options || {};
  options.globals = options.globals || {};
  // ... rest of the file
```
And in a stylesheet you should be able to use them like: 
```css
stylus = {
  hey: {
    ho: "hey"
  }
}

body
  margin: 0
  padding: 0
  animation: 2s animName infinite
  user-select none
  works: stylus.hey.ho
  breaks: js.hey.ho
```
But then: 
```
{ [TypeError: index.styl:15:14
   11|   padding: 0
   12|   animation: 2s animName infinite
   13|   user-select none
   14|   works: stylus.hey.ho
   15|   breaks: js.hey.ho
--------------------^

Cannot read property 'nodeName' of undefined
    at "body" (index.styl:8:2)
]
  lineno: 15,
  column: 14,
  filename: 'index.styl',
  stylusStack: '    at ("index.styl:8:2)',
  input: '\r\n\r\nstylus = {\r\n  hey: {\r\n    ho: "hey"\r\n  }\r\n}\r\n\r\nbody\r\n  margin: 0\r\n  padding: 0\r\n  animation: 2s animName infinite\r\n  user-select none\r\n  works: stylus.hey.ho\r\n  breaks: js.hey.ho' }

```

Note that without trying to access the js provided hash, it works.
It also doesn't work with `js['hey']` `js["hey"]` or any kind of sensible accessor format.

Does stylus not convert object into arrays? Or am I doing it wrong.
