### ISSUE TITLE
selector inside Nested @media

### ISSUE THREAD

**Issue by zba** [stylus/stylus#1884]
@media screen
      .test
       .widget 
         padding 10px;
         @media (min-width: 600px) 
           .inner
             padding 20px

yeild to

    @media screen {
      .test .widget {
        padding: 10px;
      }
    }
    @media screen and (min-width: 600px) {
      .inner {
        padding: 20px;
      }
    }

instead of:

    @media screen {
       .test .widget {
         padding: 10px;
       }
     }
     @media screen and (min-width: 600px) {
       .test .widget .inner {
         padding: 20px;
       }
     }

it may be related to #1882

**Comment by zba** [comment]
It is broken between 0.45.1 and 0.46.0 , this means that it was broken when the nested @media was implemented.

**Comment by vio** [comment]
I encountered the same issue with the following case:

```stylus
.module
  @media (min-width: 768px)
    &__header
      &-logo
        background-image: url('logo--tablet.png')

        @media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi), (min-resolution: 2dppx)
          background-image: url('logo--tablet-2x.png')
```

```css
/* Common case - retina background update for a specific breakpoint */
@media (min-width: 768px) {
    .module__header-logo {
        background-image: url("logo--tablet.png");
    }
}
@media (min-width: 768px) and (-webkit-min-device-pixel-ratio: 2), (min-width: 768px) and (min-resolution: 192dpi), (min-width: 768px) and (min-resolution: 2dppx) {
    .module__header-logo {
        background-image: url("logo--tablet-2x.png");
    }
}
```

However, found that `selector()` can help:
```stylus
.module
  @media (min-width: 768px)
    &__header
      &-logo
        background-image: url('logo--tablet.png')

        @media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi), (min-resolution: 2dppx)
          /{selector()}
            background-image: url('logo--tablet-2x.png')
```

```css
@media (min-width: 768px) {
    .module__header-logo {
        background-image: url("logo--tablet.png");
    }
}
@media (min-width: 768px) and (-webkit-min-device-pixel-ratio: 2), (min-width: 768px) and (min-resolution: 192dpi), (min-width: 768px) and (min-resolution: 2dppx) {
    .module__header-logo {
        background-image: url("logo--tablet-2x.png");
    }
}
```

**Comment by webdif** [comment]
+1

**Comment by kizu** [comment]
We'll fix this eventually, for the time being you can use this workaround mixin:

``` styl
media($query)
  @media $query
    /{selector()}
      {block}
```

Used like this:

``` styl
+media('screen')
  .test
    .widget
      padding: 10px

      +media('(min-width: 600px)')
        .inner
          padding: 20px
```

it would render as desired:

``` css
@media screen {
  .test .widget {
    padding: 10px;
  }
}
@media screen and (min-width: 600px) {
  .test .widget .inner {
    padding: 20px;
  }
}
```

**Comment by webdif** [comment]
Great workaround! :+1:

**Comment by cspotcode** [comment]
I'm using Jeet, which constructs media queries on my behalf, so using the proposed workaround would involve digging into Jeet's code.  I'd like to fix this bug myself and submit a PR.  Can anyone point me in the right direction or tell me where to look in the code?

This is what I'm seeing:

```styl
@media screen
    .s1
      .s2
        rule-should-apply-to: '.s1 .s2'
        selector-is: selector()
        @media screen
          rule-should-apply-to: '.s1 .s2'
          selector-is: selector()
```

```css
@media screen {
  .s1 .s2 {
    rule-should-apply-to: '.s1 .s2';
    selector-is: '.s1 .s2';
  }
}
@media screen {
  .s2 { /* <-- this is wrong */
    rule-should-apply-to: '.s1 .s2';
    selector-is: '.s1 .s2'; /* ...but selector() computes the right thing */
  }
}
```

**Comment by opl-** [comment]
Bump, just encountered this issue too. @kizu When's the "eventually"? Been 2 years already. :P

**Comment by phyllisstein** [comment]
It's an edgier case, but this bug also affects some PostCSS plugins. [`postcss-plumber`](https://github.com/jamonserrano/postcss-plumber), e.g., expects a syntax like this in the CSS:

```css
p {
  @plumber {
    leading-bottom: 1
    leading-top: 2
  }
}
```

The Stylus equivalent...

```stylus
p
  @plumber
    leading-bottom: 1
    leading-top: 2
```

...yields the same funky nestless at-rule as a media query, and also drops the selector:

```css
@plumber {
  leading-bottom: 1;
  leading-top: 2;
}
```
