### ISSUE TITLE
Units returned by convert behave as integers in calucations: 10em + convert("1.25em") = 11em

### ISSUE THREAD

**Issue by tisek** [stylus/stylus#1903]
Sample stylus code:
```stylus
native = 1.25em
converted = convert("1.25em")

body
  converted: converted
  result-of-addition: 10em + converted
  expected-result: 10em + native
```

Resulting CSS:
```css
body {
  converted: 1.25em;
  result-of-addition: 11em;
  expected-result: 11.25em;
}
```
