### ISSUE TITLE
Auto merging equal selectors and attributes inside selectors

### ISSUE THREAD

**Issue by ryrun** [stylus/stylus#1924]
I've a feature request. What about auto merging selectors to remove redundancy for the output css file? As far as i know, there shouldn't be any problems, when the last declaration will be used. Atleast the selector is 100% equal.

Example:

From:
```stylus
.button
   color: red
.special .button
   font-size: 32px
.button
   font-family: Arial
```
To:
```css
.special .button {
   font-size: 32px
}
.button {
   color: red;
   font-family: Arial
}
```

Maybe it could also merge attributes inside selectors and take care of the important tag:

Example:

From:
```stylus
.button
   color: red;
.button
   color: blue;
.button2
   color: red!important;
.button2
   color: blue;
```
To:
```css
.button {
   color: blue;
}
.button2 {
   color: red!important;
}
```

I know, stylus is not a compressor, but it parse the source anyway, so i think it could easily take care of it. It would be a really nice feature, when i reuse stylus files for several projects.
