### ISSUE TITLE
@keyframes not expanding properly

### ISSUE THREAD

**Issue by soubok** [stylus/stylus#1931]
Hello,
The following stylus code:
```stylus
	@keyframes foo
		0%
			transform:scale(1,0.5) translate3d(0,0,0);
```
expands as:
```css
	@-moz-keyframes foo {
		0% {
	    transform: scale(1, 0.5) translate3d(0, 0, 0);
	}
	}
	@-webkit-keyframes foo {
		0% {
	    transform: scale(1, 0.5) translate3d(0, 0, 0);
	}
	}
	@-o-keyframes foo {
		0% {
	    transform: scale(1, 0.5) translate3d(0, 0, 0);
	}
	}
	@keyframes foo {
		0% {
	    transform: scale(1, 0.5) translate3d(0, 0, 0);
	}
```
The last "}" is missing, this make the following css code not evaluated by the browser.

Thanks,
Franck.
