### ISSUE TITLE
Way to get only current selector not and compiled selector?

### ISSUE THREAD

**Issue by sevenupcan** [stylus/stylus#1942]
Hi is it possible to know only the current selector and not the whole compiled selector? I have a mixin which appends some classes in-between the current selector, but I need both the selectors that were before it and the current selector.

For example

```stylus
test-mixin() {
    current = current-selector()
    > .container-wrapper > {current}-test {
        width: arguments;
    }
}

.parent {
    .current {
        test-mixin: 30px;
    }
}
```

would compile to:

```css
.parent > .container-wrapper > .current-test {
    width: 30px;
}
```
