### ISSUE TITLE
Support for Themes

### ISSUE THREAD

**Issue by vote539** [stylus/stylus#1948]
I'm writing a stylesheet for a web site where I need to support multiple skins/themes.  For example, one theme might be black-on-white with red as the primary color, and another theme might be white-on-black with maroon as the primary color.

Almost all of the CSS from one theme translates over to the other theme, except for things like foreground and background color.

As an illustrative example, say we have a div.  The size and position of that div is fixed between themes, but the color might change.  We could separate this into three different CSS files like so:

```css
/* main.css */
#box {
	position: absolute;
	top: 50px;
	left: 50px;
	width: 200px;
	height: 200px;
	background-color: blue; /* default */
}

/* theme1.css */
#box {
	backround-color: red;
}

/* theme2.css */
#box {
	background-color: maroon
}
```

Then the end user would load *main.css* plus one of the theme stylesheets.

So now the question/suggestion comes: how can we leverage the power of Stylus to create multiple CSS theme files?

I envision something like this maybe (pseudo-code):

```stylus
primaryColor = blue  // default
theme(theme1)
	primaryColor = red
theme(theme2)
	primaryColor = maroon

#box
	position: absolute
	top: 50px
	left: 50px
	width: 200px
	height: 200px
	background-color: primaryColor
```

which would in turn generate the three CSS files listed above.

Thoughts?
