### ISSUE TITLE
absence of space causes parse error.

### ISSUE THREAD

**Issue by charlierudolph** [stylus/stylus#1950]
Found a very interesting case where the absence of a space causes a parse error.

Stylus parse succeeds on
```css
@-webkit-keyframes spin {0%{transform:rotate(0)}}
```
Stylus parse errors on
```css
@-webkit-keyframes spin{0%{transform:rotate(0)}}
```
with
```
ParseError: stylus:1:49
   1| @-webkit-keyframes spin{0%{transform:rotate(0)}}
------------------------------------------------------^

expected "indent", got "eos"
```
