### ISSUE TITLE
Error parsing Base64-encoded PNG - expected ")" got ";"

### ISSUE THREAD

**Issue by Moter8** [stylus/stylus#1969]
```
Potentially unhandled rejection [24] ParseError: C:/Users/xxx/Documents/git/Neue Webseite/style/style.styl:631:42
```

--> style.styl:631:42   char 42 is the ; after image/png.

```css
  nav #tel {
    text-align: right;
    /*  margin-left: 45%;*/
    font-size: 1em;
    line-height: 1em;

    font-weight: 400;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABQElEQVRIS7WV/zEFQRCEvxcBIiCDRwSIABE8IkAGZEAEhEAEngyEIANEQH3cqrG1e7/cTdX9s3XXPd2z07dg5lrMjE8kOAaWBcJH4GVsI5HgswJyC1xMQfAObBSA7H5vCoI1sF8B2gJsYHBFi+6BVQXhBHgYjA5/hnwK3E09h6hgE3irEBwCWji48j3QhqMM5QzQvlGVExwATwHpGrgahdx8VNrkeJv+dUXlKBHkKrRHm0ZVLYtugPOAeAl4Nrjawk57YjYZF8ZGXp5razGv2gi8tq9ZfGiXatJWx+X0TBKf57SYXXG923QXM0pSSUzf2uZLZrwUh5xbsNN0U4rytpl8N9+lIAFol/sQB9818EEECcwrrO/bXeip+b4KcjyD0acW7x+AqntbVGvY+ThslXkhkrLfv+BYBT0c+nlldoIv94wvGRkmCCUAAAAASUVORK5CYII=);
    background-repeat: no-repeat;
    background-size: 20px 20px;
    padding-left: 24px;
    padding-bottom: 4px;
  }

```

```
expected ")", got ";"

    at Parser.error (C:\Users\xxx\Documents\git\Neue Webseite\node_modules\gulp-stylus\node_modules\stylus\lib\parser.js:257:11)
    at Parser.expect (C:\Users\xxx\Documents\git\Neue Webseite\node_modules\gulp-stylus\node_modules\stylus\lib\parser.js:285:12)
    at Parser.url (C:\Users\xxx\Documents\git\Neue Webseite\node_modules\gulp-stylus\node_modules\stylus\lib\parser.js:1679:10)
    at Parser.functionCall (C:\Users\xxx\Documents\git\Neue Webseite\node_modules\gulp-stylus\node_modules\stylus\lib\parser.js:1690:52)
    at Parser.primary (C:\Users\xxx\Documents\git\Neue Webseite\node_modules\gulp-stylus\node_modules\stylus\lib\parser.js:2157:18)
    at Parser.member (C:\Users\xxx\Documents\git\Neue Webseite\node_modules\gulp-stylus\node_modules\stylus\lib\parser.js:2049:21)
    at Parser.subscript (C:\Users\xxx\Documents\git\Neue Webseite\node_modules\gulp-stylus\node_modules\stylus\lib\parser.js:2027:21)
    at Parser.unary (C:\Users\xxx\Documents\git\Neue Webseite\node_modules\gulp-stylus\node_modules\stylus\lib\parser.js:2018:17)
    at Parser.defined (C:\Users\xxx\Documents\git\Neue Webseite\node_modules\gulp-stylus\node_modules\stylus\lib\parser.js:1990:21)
    at Parser.multiplicative (C:\Users\xxx\Documents\git\Neue Webseite\node_modules\gulp-stylus\node_modules\stylus\lib\parser.js:1964:21)
```
