### ISSUE TITLE
change variable values in @media queries

### ISSUE THREAD

**Issue by drulia** [stylus/stylus#1973]
I would like to change variable value in media query and have automatically generated css where that variable was used.

I'm currently using variable to determine width of the sidebar:
```stylus
LEFT_SIDEBAR = 200px;
```

Then using it as:
```stylus
.sidebar
  width: LEFT_SIDEBAR

.content
  left: LEFT_SIDEBAR
```

But when I try to change variable value in media query it generates nothing:
```stylus
@media screen and (max-width: 1000px)
  LEFT_SIDEBAR = 150px;
```

What I would expect is to see this:
```css
.sidebar {
  width: 200px;
}
.content {
  left: 200px;
}
@media screen and (max-width: 1000px) {
  .sidebar {
    width: 150px;
  }
  .content {
    left: 150px;
  }
}
```

**Comment by Panya** [comment]
This would be very magical and implicit in more complex examples. Also it's a lot of work for compiler (tracking usage of variables, copying blocks of code in different places, etc.) for such "simple" feature. I'd suggest you to use mixins with parameters instead.

**Comment by kolesnikova-tavi** [comment]
It's a pity. It would be great.

**Comment by kolesnikova-tavi** [comment]
I do something like that:
```
$media_mobile_landscape = 480px
$media_mobile = 320px

mobile()
  @media screen and (max-width: $media_mobile)
    {block}

mobile_landscape()
  @media screen and (max-width: $media_mobile_landscape)
    {block}

only_mobile_landscape()
  @media screen and (min-width: $media_mobile + 1px) and (max-width: $media_mobile_landscape)
    {block}
```
And then
```
+mobile()
    body
        background #f00

+only_mobile_landscape()
    body
        background #00f
```

**Comment by kbtzr** [comment]
Good thing is that folks working on CSS4 know that this feature would be a game changer so we can expect more advanced concepts for variables available in the near future. :tada:

**Comment by mynameistechno** [comment]
This would be awesome for use with dark mode, e.g.
```css
@media (prefers-color-scheme: dark) {
  $background-color: black;
  $text-color: white;
}
```
