### ISSUE TITLE
0.52.1+ w/spaces before colon and variable value

### ISSUE THREAD

**Issue by ohnnyj** [stylus/stylus#1998]
```css
colors = {
  background: #fff
}

body {
  background-color : colors.background;
}
```

ParseError: ./styles.styl:6:40
   2|   background: #fff
   3| }
   4|
   5| body {
   6|   background-color : colors.background;
---------------------------------------------^
   7| }
   8|

expected "indent", got ";"

Note the space space after background-color.

This only happens when using nested hash variables. Using an explicit value is ok. Using background = #fff; is ok.
