### ISSUE TITLE
Modulo Operator Produces Unexpected Results

### ISSUE THREAD

**Issue by Anaphase** [stylus/stylus#2008]
The modulo operator seems to produce some unexpected results when used in certain ways. Consider the following examples:

## Example 1
```stylus
for $number in (1 .. 10)
  div:nth-of-type({$number})
    z-index ($number % 4)
```

produces

```css
div:nth-of-type(1) {
  z-index: 1;
}
div:nth-of-type(2) {
  z-index: 2;
}
div:nth-of-type(3) {
  z-index: 3;
}
div:nth-of-type(4) {
  z-index: 0;
}
div:nth-of-type(5) {
  z-index: 1;
}
div:nth-of-type(6) {
  z-index: 2;
}
div:nth-of-type(7) {
  z-index: 3;
}
div:nth-of-type(8) {
  z-index: 0;
}
div:nth-of-type(9) {
  z-index: 1;
}
div:nth-of-type(10) {
  z-index: 2;
}
```

This is normal expected behavior. Now, if we try to modify `$number` inline with the modulo statement, things get weird.

## Example 2
```stylus
for $number in (1 .. 10)
  div:nth-of-type({$number})
    z-index (($number + 1) % 4)
```

produces

```css
div:nth-of-type(1) {
  z-index: 2% 4;
}
div:nth-of-type(2) {
  z-index: 3% 4;
}
div:nth-of-type(3) {
  z-index: 4% 4;
}
div:nth-of-type(4) {
  z-index: 5% 4;
}
div:nth-of-type(5) {
  z-index: 6% 4;
}
div:nth-of-type(6) {
  z-index: 7% 4;
}
div:nth-of-type(7) {
  z-index: 8% 4;
}
div:nth-of-type(8) {
  z-index: 9% 4;
}
div:nth-of-type(9) {
  z-index: 10% 4;
}
div:nth-of-type(10) {
  z-index: 11% 4;
}
```

It seems in Example 2 that `$number + 1` gets converted to a string literal or something because the `% 4` is concatenated to the value of `$number + 1` instead of acting as the modulo operator. What's up with that?

A workaround is to use [`sum()`](https://learnboost.github.io/stylus/docs/bifs.html#sumnums) like so:

## Example 3
```stylus
for $number in (1 .. 10)
  div:nth-of-type({$number})
    z-index (sum($number 1) % 4)
```

but that's kinda funky, especially when Example 2 should intuitively produce the same result. Am I missing something here?

**Comment by Panya** [comment]
This behaviour was introduced long time ago for things like:
```styl
$width = 100
body
  width: ($width - 10)%
```
=>
```css
body {
  width: 90%;
}
```
But I think we can fix it for cases when `%` is surrounded by spaces. Thanks for the report.
