### ISSUE TITLE
&.foobar in :any(...)>p does unexpected behavior.

### ISSUE THREAD

**Issue by xnuk** [stylus/stylus#2013]
- source:
```stylus
:any(#foo, #bar, #baz)>p
  margin 0
  &.foobar
    text-align right
```

- expected:
```css
:any(#foo, #bar, #baz)>p {
  margin: 0;
}
:any(#foo, #bar, #baz)>p.foobar {
  text-align: right;
}
```

- result:
```css
:any(#foo,
#bar,
#baz)>p {
  margin: 0;
}
:any(#foo.foobar,
#bar.foobar,
#baz)>p.foobar {
  text-align: right;
}
```

Using v0.52.4.

Does it translate like this on purpose?
