### ISSUE TITLE
How to pass variables via command line?

### ISSUE THREAD

**Issue by DSigmund** [stylus/stylus#2014]
I want to convert a stylus file with some variables to css.

The point is, i need to create 3 different css files with the variables changed.

Can i somehow achieve this without editing the stylus files?

e.g. 
        stylus < main.styl > main-red.css --with {$prim-color:red}

**Comment by Panya** [comment]
You can write a simple plugin using JS API for this:
**variables.js**:
```js
module.exports = function(vars) {
  return function(stylus) {
    for (var name in vars) {
      stylus.define(name, vars[name]);
    }
  };
};
```

**test.styl**
```stylus
body
  color: convert($prim-color)
```

And run it like this:
```
stylus --use ./variables.js --with '{ "$prim-color": "#c00" }' test.styl
```

Compiles to (`test.css`):
```css
body {
  color: #c00;
}
```

**Comment by DSigmund** [comment]
Hi, Many Thanks for the quick answer!

Mikhail Korepanov <notifications@github.com> schrieb am Di., 22. Sep. 2015
um 21:34 Uhr:

**Comment by shammellee** [comment]
You can also use environment variables.

> I'm namespacing the variables with `NODE_` to prevent naming conflicts with existing environment variables.

```js
// globals.js
module.exports = function()
{
  return function(stylus)
  {
    const GLOBAL_REGEX = /^NODE_/;  // Matches variables whose name start with NODE_
    const ENV_KEYS     = Object.keys(process.env);  // Get array of all environment variable names

    for(let i = 0; i < ENV_KEYS.length; i++)
    {
      if(GLOBAL_REGEX.test(ENV_KEYS[i]))  // If environment variable name matches regex
      {
        stylus.define(ENV_KEYS[i], process.env[ENV_KEYS[i]]);  // Define variable as a stylus global
      }
    }
  };
};
```

```stylus
// styles.styl
pill(pill_color)
  background-color pill_color
  border-radius 20px
  display inline-block
  height @border-radius * 2
  width 100px

.red-pill
  pill NODE_COLOR_RED

.blue-pill
  pill NODE_COLOR_BLUE
```

```sh
# shell
$ export NODE_COLOR_RED='#f00'
$ export NODE_COLOR_BLUE='#00f'
$ stylus --use globals.js styles.styl
```

```css
/* styles.css */
.red-pill {
  background-color: #f00;
  border-radius: 20px;
  display: inline-block;
  height: 40px;
  width: 100px;
}
.blue-pill {
  background-color: #00f;
  border-radius: 20px;
  display: inline-block;
  height: 40px;
  width: 100px;
}
```
