### ISSUE TITLE
[Bug] Hash pseudo

### ISSUE THREAD

**Issue by nblackburn** [stylus/stylus#2016]
I have encountered a bug when following a hash property with a pseudo element

```stylus
class = { row: 'row' }
setting = { gutter: 1em }

.{class.row}
	padding-bottom setting.gutter
	&:last-child
		padding-bottom 0
``` 

Which compiles to the following...

```css
.row padding-bottom setting.gutter,
.row:last-child {
  padding-bottom: 0;
}
```
