### ISSUE TITLE
Don't render property if it's value is `null`

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#2019]
``` Stylys
.foo
  width: null
  height: 10px
```

Right now renders as 

``` CSS
.foo {
  width: ;
  height: 10px;
}
```

But should render as

``` CSS
.foo {
  height: 10px;
}
```
