### ISSUE TITLE
Feature request: @extend !important

### ISSUE THREAD

**Issue by Soviut** [stylus/stylus#2042]
I'd like to see an `!important` flag added to the `@extend` function that would add the `!important` suffix to all the extended properties. This would compliment the existing `!optional` flag that already exists.

```stylus
.input
    padding 10px
    color color1

.generated-input
    @extend .input !important
```
yields:
```css
.generated-input {
    padding: 10px !important;
    color: #CCCCCC !important;
}
```

The reason this would be useful is I'm having to style a form via an online generator for a site that already has existing form styles that I need to match. The generated form is very particular about selection specificity and I find myself having to use `!important` quite a bit. It'd be nice if this nuclear option was available to stomp all the styles at once while extending.

**Comment by Panya** [comment]
Well, this is completely different feature comparing to `!optional` and tbh I don't think that the feature should be implemented in Stylus' core. Basically that's not even an `@extend`, because we need to copy and modify extending block instead of just adding a selector to its group:
```styl
.input
    padding 10px
    color red

.generated-input
    @extend .input
```
=>
```css
.input,
.generated-input {
  padding: 10px;
  color: #f00;
}
```
vs.
```styl
.input
    padding 10px
    color color1

.generated-input
    @extend .input !important
```
=>
```css
.generated-input {
    padding: 10px !important;
    color:  #f00 !important;
}
```

I suggest you use PostCSS for this task.
