### ISSUE TITLE
Comment indentation should not affect scoping behaviour; causes unexpected CSS output

### ISSUE THREAD

**Issue by axefrog** [stylus/stylus#2053]
I saw some other issues with regards to block scoping and comment indentation, and they appear to have been closed (presumably fixed?) but here are some more that are issues right now, and took me ages to figure out what the heck was going on:

### Base example, working correctly:

```stylus
html.foo
  color red
@media screen
  .bar
    color blue
```

Output:

```css
html.foo {
  color: #f00;
}
@media screen {
  .bar {
    color: #00f;
  }
}
```

### Erroneous example 1:

```stylus
html.foo
  color red
    // a comment
@media screen
  .bar
    color blue
```

Initial selector completely destroyed:

```css
@media screen {
  .bar {
    color: #00f;
  }
}
```

### Erroneous example 2:

```stylus
html.foo
  color red
  // a comment
    // a comment
@media screen
  .bar
    color blue
```

Root selector erroneously appended to media query selector:

```css
html.foo {
  color: #f00;
}
@media screen {
  html.foo .bar {
    color: #00f;
  }
}
```

-----

There might be other comment indentation edge case bugs as well, but it seems to me that if you could have the parser completely disregard comment indentation, these hard-to-find bugs would all magically go away.
