### ISSUE TITLE
Feature Request: custom pseudo-classes

### ISSUE THREAD

**Issue by JWo1F** [stylus/stylus#2064]
Hi all! I want to write my own pseudo-classes, for example:
```stylus
:header()
  h1, h2, h3, h4, h5, .header
    {block}

.main:header
  color red
```
Will compile to:
```css
h1.main, h2.main, h3.main,
h4.main, h5.main, .header.main {
  color: red;
}
```

I thinks it's awesome idea, what do you think of it?
