### ISSUE TITLE
Mixins don't work inside atblocks

### ISSUE THREAD

**Issue by Moncader** [stylus/stylus#2081]
Calling a function inside an atblock doesn't output any of the properties of the mixin.

Looking at the AST, it looked like the function just returned a Null node and didn't add anything at all to the block.

```stylus
test()
  width 10px

$myblock =
  test()
  height 10px

.myclass
  {$myblock}
```

Expected output
```css
.myclass {
  width: 10px;
  height: 10px;
}
```

Actual output
```css
.myclass {
  height: 10px;
}
```
