### ISSUE TITLE
@page causes problems

### ISSUE THREAD

**Issue by Pinpickle** [stylus/stylus#2085]
I'm trying to use Stylus to do some print work using [`@page`](https://developer.mozilla.org/en/docs/Web/CSS/@page) and [CSS Paged Media Module Level 3](https://www.w3.org/TR/css3-page/). A lot of the things involving it is unsupported in most browsers, but you can do a fair bit at the moment.

Among other things, it lets you do this

```
@page {
  /* Styles to apply to a page */
  @bottom-center {
     /* Put content in the bottom center margin box of the page */
  }
}

@page:first {
  /* Styles to apply to the first page */
}
```

A lot of it already works in Stylus but it's the second `@page:first` selector that gives me grief. I've tried a lot of methods and workarounds.

```stylus
// Stylus

// 1
@page:first {
  foo: bar;
}

// 2
@page {
  &:first {
    foo: bar;
  }
}

// 3
{'@page:first'} {
  foo: bar;
}

// 4
{'@page:first'} {
  @bottom-center {
    foo: bar;
  }
}

// 5
{'@page:first'} {
  {'@bottom-center'} {
    foo: bar;
  }
}
```

```css
/* CSS */

/* 1 */
@page :first { /* note the space, selector no longer works */
  foo: bar;
}

/* 2 */
@page {
  :first {
    foo: bar;
  }
}

/* 3 */
@page:first { /* Success! But ugly */
  foo: bar;
}

/* 4 */
@page:first {
}

@bottom-center { /* This should be inside the @page block */
  foo: bar; 
}

/* 5 */
@page:first {
}

@page:first @bottom-center { /* Still not correct */
  foo: bar;
}
```

The workaround is successful, but took a few goes to find it out and it doesn't work in all cases. Would be nice to see this get full class support. Are there any other suggested workarounds to use that don't involve `@css`?

**Comment by kizu** [comment]
Yep, that's a bug, as specs allow constructions like `@foo:bar`, we shouldn't add a space there.

Another workaround is to use `unquote`, maybe used inside a mixin:

``` styl
at-page($selector)
  unquote('@page' + $selector + ' {')
  {block}
  unquote('}')

+at-page(':first')
  @bottom-center
    foo: bar
```

the result is rather ugly (we lose the indentation):

``` css
@page:first {
@bottom-center {
  foo: bar;
}
}
```

but should render well I guess.
