### ISSUE TITLE
Issues around `@media` and mixins

### ISSUE THREAD

**Issue by tjbenton** [stylus/stylus#2102]
I've run into a few problems with the `@media` implementation. Most of the mixin that I wrote is located at the bottom of this issue. I realize this is a long explanation so if you want me to submit this in a different way or want me to create test cases for this I can, just let me know what I can do to help with this issue.
#### Problems

1. `current-media()` doesn't return the correct value when it's called inside of a called mixin

``` styl
+media('>=sm') {
  current-media()
  // got `@media (((($parsed-query.type)): (($parsed-query.size))))`
  // expected `@media (min-width: 568px)`
}
```

2.  Variables defined inside of a media query don't get stored locally to the media query they where declared in. The variables that are defined in a media query should also be available to the block that is passed in the mixin. They also don't override variables if they where previously declared in the global scope. 

``` styl
@media (min-width: 500px)
  $something = 'something awesome'

// some other styles...

@media (min-width: 500px)
  .foo
    content $something;
```

**CSS output**

``` css
@media (min-width: 500px) {
    .foo {
        content: $something;
    }
}
```

**Expected CSS output**

``` css
@media (min-width: 500px) {
    .foo {
        content: 'something awesome';
    }
}
```

3. Because the `current-media()` doesn't return the compiled media query this causes havoc with the [`+cache`](https://github.com/stylus/stylus/blob/dev/lib/functions/index.styl#L274) mixin because when the [`+cache`](https://github.com/stylus/stylus/blob/dev/lib/functions/index.styl#L274) mixin checks for the [`current-media`](https://github.com/stylus/stylus/blob/dev/lib/functions/index.styl#L275) it will return `''` when called inside of a mixin.

``` styl
reset($extend = true)
  if $extend
    +cache('reset' + $media)
      reset(false)
  else
    list-style none outside none unless @list-style
    margin-left 0 unless @margin-left
    margin-right 0 unless @margin-right
    padding 0 unless @padding


for $breakpoint in $media-breakpoints-list
  +media($breakpoint)
    .foo{$media}
      reset()

    .bar{$media}
      reset()
```

**CSS output**

``` css
.foo,
.bar,
.foo\@sm,
.bar\@sm,
.foo\@md,
.bar\@md,
.foo\@lg,
.bar\@lg {
  list-style: none outside none;
  margin-left: 0;
  margin-right: 0;
  padding: 0;
}
```

**Expected CSS Output**

``` css
.foo, .bar {
  list-style: none outside none;
  margin-left: 0;
  margin-right: 0;
  padding: 0;
}
@media (min-width: 568px) {
  .foo\@sm, .bar\@sm {
    list-style: none outside none;
    margin-left: 0;
    margin-right: 0;
    padding: 0;
  }
}
@media (min-width: 768px) {
  .foo\@md, .bar\@md {
    list-style: none outside none;
    margin-left: 0;
    margin-right: 0;
    padding: 0;
  }
}
@media (min-width: 1024px) {
  .foo\@lg, .bar\@lg {
    list-style: none outside none;
    margin-left: 0;
    margin-right: 0;
    padding: 0;
  }
}
```
## Using `@media` in a mixin

``` styl
+media('>=sm') {
  p(
    unquote('a. current-media inside of called mixin = '),
    -string(current-media()),
    unquote(''),
    unquote('b. the media variable defined in mixin = '),
    -string($media)
  )
  .foo{$media} {
     background: $media
  }
}
```

stdout

``` bash
inspect: a. current-media inside of called mixin =
inspect: ''
inspect:
inspect: b. the media variable defined in mixin =
inspect: 'ident $media'
inspect:
inspect: c. current-media inside of defined mixin @media =
inspect: '@media (((($parsed-query.type)): (($parsed-query.size))))'
```

This is what I would expect as the stdout

``` bash
inspect: a. current-media inside of called mixin =
inspect: '@media (min-width: 568px)'
inspect:
inspect: b. the media variable defined in mixin =
inspect: 'string \@sm'
inspect:
inspect: c. current-media inside of defined mixin @media =
inspect: '@media (min-width: 568px)'
```

CSS output

``` css
@media (min-width: 568px) {
    .foo\@sm {
        background: $media;
    }
}
```

Expected CSS output

``` css
@media (min-width: 568px) {
    .foo\@sm {
        background: '\@sm';
    }
}
```

The media query mixin that the code above is referring to

``` styl
$media-breakpoints = { 'sm': 568px, 'md': 768px, 'lg': 1024px }

$media-breakpoints-list = split(',', ',>=' + join(',>=', keys($media-breakpoints)))

media($breakpoint) {
  $parsed-query = parse-query($breakpoint)
  // $parsed-query returns an object like this
  // {
  //   type: 'min-width',
  //   size: '568px',
  //   expression: 'min-width: 568px',
  //   operator: '>=',
  //   value: 'sm'
  // }

  if !$parsed-query.value {
    $media = $m = ''
    {block}
  } else {
    @media ({$parsed-query.type} : $parsed-query.size) {
      p(
        unquote(''),
        unquote('c. current-media inside of defined mixin @media = '),
        -string(current-media())
      )

      // set the current media state
      if $parsed-query.value in keys($media-breakpoints) {
        $media = $m = '\@' + $parsed-query.value
      }
      {block}
    }
  }
}
```

**Comment by Panya** [comment]
Hi. Thanks for the report. Could you send a PR with broken test cases? (I'm not sure that I completely understand 2-nd and 3-rd problem).

**Comment by tjbenton** [comment]
I created a PR with the broken test cases. Let me know if you have any questions, or point me in the right direction and I can see if I can fix it. Thanks

**Comment by cspotcode** [comment]
I just ran into this as well.  Even though @tjbenton already submitted a broken test, here's a simple reproduction:

```styl
$color-red()
  +cache()
    color: red

$conditional = 'screen'
@media $conditional
  .red-on-screen
    $color-red()

$conditional = 'print'
@media $conditional
  .red-in-print
    $color-red()

// `@media print` is never generated
```

**Comment by seleckis** [comment]
My case could be refered to this issue:

E.g.:
```stylus
above($args)
	$media = "@media "
	$comma = ""
	for $orient, $bp in $args
		$media += $comma + "(min-width: " + $bp + ") and (orientation: " + $orient + ")"
		$comma = ", "
	$media = unquote($media)
	{$media}
		{block}
body
	+above({ portrait: 768px, landscape: 1024px })
		font-size: 18px
```

I expect to see:
```css
@media (min-width: 768px) and (orientation: portrait), (min-width: 1024px) and (orientation: landscape) {
  body {
    font-size: 18px;
  }
}
```
But I get
```css
body @media (min-width: 768px) and (orientation: portrait),
body (min-width: 1024px) and (orientation: landscape) {
  font-size: 18px;
}
```
Is it? Or there are problems with my code?
