### ISSUE TITLE
Pass arguments to a hash getter inside a mixin?

### ISSUE THREAD

**Issue by mike3run** [stylus/stylus#2118]
Hey guys I'm trying to port my handy Sass breakpoints mixin let me show the rough idea:

```stylus
// Hash
breakpoints = {
  xs : null,
  small : 120px,
  medium : 200px
}

// Mixin
mq(bp)
  size = breakpoints.bp
  @media (min-width:size)
    {block}

// Expected use but not working
.home
  color pink
  +mq(medium)
    color red
```

What I'm expecting to get is

```css
.home {
  color: #ffc0cb;
}
@media (min-width:200px ) {
  .home {
    color: #f00;
  }
}
```

Instead I get:

```css
.home {
  color: #ffc0cb;
}
@media (min-width: ) {
  .home {
    color: #f00;
  }
}
```

Any thoughts??
