### ISSUE TITLE
Get parent selector combinator?

### ISSUE THREAD

**Issue by thybzi** [stylus/stylus#2121]
One more thing I'd like to ask.

Is there any way (existing or planning) to get the [combinator](https://www.w3.org/TR/selectors/#combinators) of parent selector rule?

I mean this:
```styl
.wrapper

  & > figure
     // somehow get '>' here to use in selectors
```

Together with partial modifiers from [future spec](https://github.com/stylus/stylus/issues/1240), it can provide an elegant way to generate the following CSS code from within the `& > figure` block.

```css
.wrapper > figure + *,
.wrapper > * + figure {
  margin-top: 24px;
}
```
