### ISSUE TITLE
Bug in selectors() function

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#2130]
See #2121: 

```styl
.wrapper
  & > figure
    test: selectors()
```

results in 

```css
.wrapper > figure {
  test: '.wrapper', '& & > figure';
}
```

Which is incorrect, as the second item of the list the `selectors()` returns should be `& > figure`.
