### ISSUE TITLE
^[n..m] selector ranges insert undesired spaces

### ISSUE THREAD

**Issue by cspotcode** [stylus/stylus#2133]
Given this stylus:

    .s1
      &-s2
        &-s3
          &-s4
            ^[2]
              // first three levels of selectors
              syntax: "^[2]"
            ^[0..2]
              // I expect this to be identical to the above, but it's not
              syntax: "^[0..2]"

I get this output:

    .s1-s2-s3 {
      syntax: "^[2]";
    }
    .s1 -s2 -s3 {
      syntax: "^[0..2]";
    }

In #1240 one of the examples uses ranges to insert into the middle of a selector:

>     .foo
>       & .bar
>         width: 10px
>    
>         ^[0]:hover ^[1..-1]
>           width: 20px

However, that example breaks when I make a slight adjustment.

    // When mouse is over .foo, .bar-baz should become wider
    .foo
      .bar
         border: 1px solid grey
         &-baz
           width: 10px
           ^[-2]:hover ^[-2..-1]
             width: 20px

```css
.foo .bar {
  border: 1px solid #808080;
}
.foo .bar-baz {
  width: 10px;
}
.foo:hover .bar -baz { /* <-- wrong selector */
  width: 20px;
}
```
