### ISSUE TITLE
imported css not compressed

### ISSUE THREAD

**Issue by ben-page** [stylus/stylus#2154]
The contents of an inline imported a .css file (using `--include-css`) is not compressed by `--compress` argument.

**normalize.css**
```css
/* normalize.css */
html {
    font-family: sans-serif;
}
```

**style.styl**
```css
@import 'normalize.css'
/* start of CSS */
body {
  box-sizing: border-box;
}
```

**Run stylus:**
```shell
>stylus --include-css --compress style.styl
  compiled style.css
```

**style.css**
```css
/*! normalize.css v0.0.1 */
html {
    font-family: sans-serif;
}
body{box-sizing:border-box}
```

In the resulting file, the contents of the .styl has been compressed, but contents of the .css file has not.
