### ISSUE TITLE
Duplicate properties aren't removed

### ISSUE THREAD

**Issue by thybzi** [stylus/stylus#2159]
Source
```styl
a 
  line-height: 16px
  line-height: 10px
```

Expected compilation result:
```css
a {
  line-height: 10px;
}
```

Actual compilation result:
```css
a {
  line-height: 16px;
  line-height: 10px;
}
```
