### ISSUE TITLE
Minus sign before variable

### ISSUE THREAD

**Issue by thybzi** [stylus/stylus#2160]
Stylus code:
```styl
a
  $size = 30px
  height: $size
  margin-top: -$size
```

Expected compile result:
```css
a {
  height: 30px;
  margin-top: -30px;
}
```

Actual compile result:
```css
a {
  height: 30px;
  margin-top: -$size;
}
```

In all major programming languages, and also in LESS and SASS, this minus sign works like a charm, but not in Stylus.

It is very inconvinient to replace each minus sign with `-1 *`.
