### ISSUE TITLE
`$args...` is not the same as `arguments` when passing space-separated arguments

### ISSUE THREAD

**Issue by thybzi** [stylus/stylus#2162]
When I'm passing space-separated values to function that accepts `$args...` (rest params), this values are parsed by space in `arguments` automatic variable, but stay solid in `$args`

Is that a bug or whatever?

Stylus code:
```styl
func($args...)
  /* arguments */
  arguments-value: arguments
  arguments-length: length(arguments)
  arguments-type: typeof(arguments)
  arguments-0: arguments[0]
  /* $args */
  args-value: $args
  args-length: length($args)
  args-type: typeof($args)
  args-0: $args[0]
  
.test1
  func(one two three) // passing space-separated list ($args and arguments are different)

.test2
  func(one, two, three) // passing comma-separated list ($args and arguments are similar)
```

Result:
```css
.test1 {
/* arguments */
  arguments-value: one two three;
  arguments-length: 3;
  arguments-type: 'ident';
  arguments-0: one;
/* $args */
  args-value: one two three;
  args-length: 1;
  args-type: 'ident';
  args-0: one two three;
}
.test2 {
/* arguments */
  arguments-value: one two three;
  arguments-length: 3;
  arguments-type: 'ident';
  arguments-0: one;
/* $args */
  args-value: one two three;
  args-length: 3;
  args-type: 'ident';
  args-0: one;
}
```

Codepen for quick reproduce: http://codepen.io/thybzi/pen/grXrqg?editors=0100
