### ISSUE TITLE
cos and sin return radians if the angle is radians

### ISSUE THREAD

**Issue by trikadin** [stylus/stylus#2188]
``` css
.some-class {
  cosine: cos(0rad)
}
```

=>

``` css
.some-class {
  cosine: 1rad;
}
```
