### ISSUE TITLE
[Question] Variable class

### ISSUE THREAD

**Issue by rogervila** [stylus/stylus#2209]
Hello, I have a pseudo-table created with divs and [lost](https://github.com/peterramsing/lost), and I want to add to them a "colspan" modifier, like this:
```css

.cell
    lost-column: 3/12

.cell--colspan2
    lost-column: 6/12

.cell--colspan3
    lost-column: 9/12

.cell--colspan4
    lost-column: 12/12

```

The idea is to make something like this

```css
/*this syntax is wrong but is the idea that I want to achieve*/

$max-rows = 12
$cell-space = 3

.cell--colspan{$space-value}
    lost-column: operate('*', $cell-space, $space-value)/$max-rows

``` 

What syntax do I need to create a variable class?

Thank you!
