### ISSUE TITLE
Linter allows hanging properties

### ISSUE THREAD

**Issue by mhkeller** [stylus/stylus#2212]
A stylus file like this

```styl
  .bar
    fill #e13a4a
    text
```

will compile to CSS like this without throwing any errors or warnings as far as I can tell.

```css
.bar {
  fill: #e13a4a;
text
}
```
