### ISSUE TITLE
Cannot use {block} within a media query

### ISSUE THREAD

**Issue by ibc** [stylus/stylus#2216]
This works:

```css
placeholder()
	&::-webkit-input-placeholder
		{block}
	&:-moz-placeholder
		{block}
	&::-moz-placeholder
		{block}
	&:-ms-input-placeholder
		{block}
```

```css
input {
	+placeholder() {
		color: rgba(#fff, 0.75);
		font-style: italic;
	}
}
```

However this does not work (it produces nothing in the generated CSS):

```css
mobile()
	@media (min-width: 900px)
		{block}
```

```css
body {
	+mobile() {
		padding: 0;
	}
}
```

Do I miss something?
