### ISSUE TITLE
Output raw input

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus#2218]
Possible to render raw input?

For instance:

```styl
.foo
  background: raw(@#$@#$@#$#@$///////1!!!!!!11`````-----)
  raw(derpderpderp234234234234: 234234234!111) 
```

would output

```css
.foo {
  background: @#$@#$@#$#@$///////1!!!!!!11`````-----;
  derpderpderp234234234234: 234234234!111;
}
```

Need this functionality so I can use it with my weird PostCSS stuff.

**Comment by OctoD** [comment]
Have you tried to unquote a string?

```sass
background: unquote('@#$@#$@#$#@$///////1!!!!!!11`````-----')
```

**Comment by corysimmons** [comment]
@OctoD Works for the first example, but not for the second.

```styl
body
  background: unquote('!!!!2123131`jj`j')
  unquote('!!!!2123131`jj`j: 1231231231231```~~~~;')
```

compiles to

```css
body {
  background: !!!!2123131`jj`j;
!!!!2123131`jj`j: 1231231231231```~~~~;
}
!!!!2123131`jj`j: 1231231231231```~~~~;
```

I would expect it to compile to

```css
body {
  background: !!!!2123131`jj`j;
  !!!!2123131`jj`j: 1231231231231```~~~~;
}
```
