### ISSUE TITLE
url function should not replace single quotes with double quotes

### ISSUE THREAD

**Issue by bitpshr** [stylus/stylus#2243]
When using the `url` function, single quotes shouldn't be blindly replaced with double quotes. This causes issues when using inline SVG that contains double-quoted attributes:

Stylus input:
```stylus
.example:after {
  content: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="-10 -18 100 135"><circle cx="50" cy="50" r="50" fill="none" stroke="#bddad5" stroke-width="3"/></svg>');
}
```

CSS output (invalid URL surrounded in double quotes with double-quoted attributes):

```css
.example:after {
  content: url("data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="-10 -18 100 135"><circle cx="50" cy="50" r="50" fill="none" stroke="#bddad5" stroke-width="3"/></svg>");
}
```

There are workarounds, such as manually replacing double-quoted attributes to be single-quoted, or surrounding the rule with `@css`, but this shouldn't be necessary. Single vs. double quotes should be detected (if any quotes even exist), and should be used when generating output.

I'd be happy to implement this assuming it's worth fixing / would be landed pending review.
