### ISSUE TITLE
ignore character escaping for selectors

### ISSUE THREAD

**Issue by mknudsen01** [stylus/stylus#2283]
I'm a big fan of atomic styling, and so with padding or margin classes, I'll use a `--`,`-`,`+`, `++` convention to quarter/halve/double/quadruple the normal gutter amounts -- i.e.,`mt` is `margin-top: 16px`, so `mt++` would be `margin-top: 64px`. 

For CSS selectors, a character like `+` needs to be escaped in the compiled stylesheet, though. Compiled CSS needs to look like `.mt\+\+` instead of just `.mt++`. 

So, I've got some code here: 
```stylus
// _margin.styl
:root {
  --gutter-width: 1rem;
}
.m\+
  margin calc(var(--gutter-width, 1rem) * 2)

.mt\+
  margin-top calc(var(--gutter-width, 1rem) * 2)

.mb\+
  margin-bottom calc(var(--gutter-width, 1rem) * 2)

.ml\+
  margin-left calc(var(--gutter-width, 1rem) * 2)

.mr\+
  margin-right calc(var(--gutter-width, 1rem) * 2)


.m\+\+
  margin calc(var(--gutter-width, 1rem) * 4)

.mt\+\+
  margin-top calc(var(--gutter-width, 1rem) * 4)

.mb\+\+
  margin-bottom calc(var(--gutter-width, 1rem) * 4)

.ml\+\+
  margin-left calc(var(--gutter-width, 1rem) * 4)

.mr\+\+
  margin-right calc(var(--gutter-width, 1rem) * 4)
```

which is compiling into: 
```css
/* styles.css */
.m+ {
  margin: calc(var(--gutter-width, 1rem) * 2);
}
.mt+ {
  margin-top: calc(var(--gutter-width, 1rem) * 2);
}
.mb+ {
  margin-bottom: calc(var(--gutter-width, 1rem) * 2);
}
.ml+ {
  margin-left: calc(var(--gutter-width, 1rem) * 2);
}
.mr+ {
  margin-right: calc(var(--gutter-width, 1rem) * 2);
}
.m++ {
  margin: calc(var(--gutter-width, 1rem) * 4);
}
.mt++ {
  margin-top: calc(var(--gutter-width, 1rem) * 4);
}
.mb++ {
  margin-bottom: calc(var(--gutter-width, 1rem) * 4);
}
.ml++ {
  margin-left: calc(var(--gutter-width, 1rem) * 4);
}
.mr++ {
  margin-right: calc(var(--gutter-width, 1rem) * 4);
}
```

In escaping the literals, the compiled CSS breaks and does not work (`.mt+` instead of `.mt\+`). Is there any way to compile the selectors and have them keep the `\` to escape the `+`? 

I tried `unquote` to no avail. `unquote(.m\+)` would create an `expected ")", got "."` error, and `unquote(\.m\+)` would just produce the same `.mt+` output. 

I'm alright with working around just doing `@css {}` and changing from stylus to normal CSS for those selectors, but I'd love to see/build less general solution.

Is there a way to ignore the character escaping that I'm not seeing? Or, if not, would adding in a method be feasible? Happy to try to dig into the code and create my own PR, as well, if it's something you all would allow in the library.
