### ISSUE TITLE
[Feature request] Comments in x > y selectors

### ISSUE THREAD

**Issue by Kristinita** [stylus/stylus#2298]
### 1. Request

It would be nice, **if** would be possible add comments in [**x > y selectors**](https://code.tutsplus.com/tutorials/the-30-css-selectors-you-must-memorize--net-16048).

### 2. Justification

For example, part of my `KristinaBigStylusDocument.styl` file:

```stylus
.SashaInlineHighlight
    background SashaColor1
    color SashaColor2

    .hll
        background-color SashaColor3

    .c
        color SashaColor4
        font-style italic
        background-color SashaColor5

    .err
        color SashaColor2

    .esc
        color SashaColor2

    .g
        color SashaColor2

    .k
        color SashaColor6
        font-weight bold

    .l
        color SashaColor2

    .n
        color SashaColor2

    .o
        color SashaColor2

    .x
        color SashaColor2

    .p
        color sandybrown

    .ch
        color SashaColor4
        font-style italic
        background-color SashaColor5
```

For example, user want to see comment, what is `.p` CSS class. Now user needs scroll all document, it may spend a user time.

### 3. Settings

For example, I have a `KristinaSilence.styl` file:

```stylus
/* Epigraph */

.SashaEpigraph
    margin-right 1rem
    margin-left 3rem
    text-align right

/* Disable gradient **for** em tag */

    >em
        background-image none

/*
 * Inscription after epigraph
 */

    >.SashaEpigraphAuthor
        line-height 1rem
        margin 2rem 0
```

### 4. Steps to reproduce

I run command in a terminal:

```shell
stylus KristinaSilence.styl
```

### 5. Actual behavior

Wrong CSS:

```css
/* Epigraph */
.SashaEpigraph {
  margin-right: 1rem;
  margin-left: 3rem;
  text-align: right;
}
/* Disable gradient **for** em tag */
>em {
  background-image: none;
}
/*
 * Inscription after epigraph
 */
>.SashaEpigraphAuthor {
  line-height: 1rem;
  margin: 2rem 0;
}

```

### 6. Expected behavior

If in `KristinaSilence.styl` I move comments to top of file, I get correct CSS:

```css
/* Epigraph */
/* Disable gradient **for** em tag */
/*
 * Inscription after epigraph
 */
.SashaEpigraph {
  margin-right: 1rem;
  margin-left: 3rem;
  text-align: right;
}
.SashaEpigraph >em {
  background-image: none;
}
.SashaEpigraph >.SashaEpigraphAuthor {
  line-height: 1rem;
  margin: 2rem 0;
}

```

Thanks.
