### ISSUE TITLE
[bug]With the attributes of the same name mixin is called twice?

### ISSUE THREAD

**Issue by baijunjie** [stylus/stylus#2308]
define
```css
border($color = #ccc, $width = 1px, $style = solid) {
    p($width $style $color);
    border: $width $style $color;
}
bd = border;
```
Do not conform to the anticipated.
Why the output twice?
```css
.test {
    bd();
}
// output:
// => inspect: (1px) (solid) (#ccc)
// => inspect: (solid) (#ccc) (1px)
```
In line with expectations
```css
.test {
    border();
}
// output:
// => inspect: (1px) (solid) (#ccc)
```
