### ISSUE TITLE
CSS Media Query Level 4

### ISSUE THREAD

**Issue by yukulele** [stylus/stylus#2317]
stylus is not compatible with [CSS Media Queries Level 4 range context](https://drafts.csswg.org/mediaqueries-4/#mq-range-context)

```css
@media screen and (width > 500px) and (100px <= height <= 700px) {
  :root {
    background-color: blue;
  }
}
```

Error `illegal unary ">", missing left-hand operand`
