### ISSUE TITLE
Unexpected result in nested block mixin and parent reference

### ISSUE THREAD

**Issue by admannon** [stylus/stylus#2320]
I'd try to use block mixins with parent reference in my sample code
```stylus
$resolutions = {
  sm: 768px,
  lg: 1200px
}

resolution-min($resolutions = $resolutions)
  {block}

  for $k, $v in $resolutions
    @media (min-width: $v)
      &-{$k}
        {block}

$grid-columns-max ?= 2

for $grid-size in (1..$grid-columns-max)
  .grid.-size-{$grid-size}
    +resolution-min()
      & > .cell
        max-width : (100% / $grid-size)
        
        for $cell-size in (1..$grid-size)
          &.-size-{$cell-size}
            +resolution-min()
              max-width: (100% * $cell-size / $grid-size)
```

So I want to see css like,
```css
.grid.-size-1 > .cell {
  max-width: 100%;
}

.grid.-size-1 > .cell.-size-1 {
  max-width: 100%;
}

@media (min-width: 768px) {
  .grid.-size-1 > .cell.-size-1-sm {
    max-width: 100%;
  }
}

@media (min-width: 1200px) {
  .grid.-size-1 > .cell.-size-1-lg {
    max-width: 100%;
  }
}

@media (min-width: 768px) {
  .grid.-size-1-sm > .cell {
    max-width: 100%;
  }
  .grid.-size-1-sm > .cell.-size-1 {
    max-width: 100%;
  }
}

@media (min-width: 768px) and (min-width: 768px) {
  .grid.-size-1-sm > .cell.-size-1-sm {
    max-width: 100%;
  }
}

@media (min-width: 768px) and (min-width: 1200px) {
  .grid.-size-1-sm > .cell.-size-1-lg {
    max-width: 100%;
  }
}

@media (min-width: 1200px) {
  .grid.-size-1-lg > .cell {
    max-width: 100%;
  }
  .grid.-size-1-lg > .cell.-size-1 {
    max-width: 100%;
  }
}

@media (min-width: 1200px) and (min-width: 768px) {
  .grid.-size-1-lg > .cell.-size-1-sm {
    max-width: 100%;
  }
}

@media (min-width: 1200px) and (min-width: 1200px) {
  .grid.-size-1-lg > .cell.-size-1-lg {
    max-width: 100%;
  }
}

.grid.-size-2 > .cell {
  max-width: 50%;
}

.grid.-size-2 > .cell.-size-1 {
  max-width: 50%;
}

@media (min-width: 768px) {
  .grid.-size-2 > .cell.-size-1-sm {
    max-width: 50%;
  }
}

@media (min-width: 1200px) {
  .grid.-size-2 > .cell.-size-1-lg {
    max-width: 50%;
  }
}

.grid.-size-2 > .cell.-size-2 {
  max-width: 100%;
}

@media (min-width: 768px) {
  .grid.-size-2 > .cell.-size-2-sm {
    max-width: 100%;
  }
}

@media (min-width: 1200px) {
  .grid.-size-2 > .cell.-size-2-lg {
    max-width: 100%;
  }
}

@media (min-width: 768px) {
  .grid.-size-2-sm > .cell {
    max-width: 50%;
  }
  .grid.-size-2-sm > .cell.-size-1 {
    max-width: 50%;
  }
}

@media (min-width: 768px) and (min-width: 768px) {
  .grid.-size-2-sm > .cell.-size-1-sm {
    max-width: 50%;
  }
}

@media (min-width: 768px) and (min-width: 1200px) {
  .grid.-size-2-sm > .cell.-size-1-lg {
    max-width: 50%;
  }
}

@media (min-width: 768px) {
  .grid.-size-2-sm > .cell.-size-2 {
    max-width: 100%;
  }
}

@media (min-width: 768px) and (min-width: 768px) {
  .grid.-size-2-sm > .cell.-size-2-sm {
    max-width: 100%;
  }
}

@media (min-width: 768px) and (min-width: 1200px) {
  .grid.-size-2-sm > .cell.-size-2-lg {
    max-width: 100%;
  }
}

@media (min-width: 1200px) {
  .grid.-size-2-lg > .cell {
    max-width: 50%;
  }
  .grid.-size-2-lg > .cell.-size-1 {
    max-width: 50%;
  }
}

@media (min-width: 1200px) and (min-width: 768px) {
  .grid.-size-2-lg > .cell.-size-1-sm {
    max-width: 50%;
  }
}

@media (min-width: 1200px) and (min-width: 1200px) {
  .grid.-size-2-lg > .cell.-size-1-lg {
    max-width: 50%;
  }
}

@media (min-width: 1200px) {
  .grid.-size-2-lg > .cell.-size-2 {
    max-width: 100%;
  }
}

@media (min-width: 1200px) and (min-width: 768px) {
  .grid.-size-2-lg > .cell.-size-2-sm {
    max-width: 100%;
  }
}

@media (min-width: 1200px) and (min-width: 1200px) {
  .grid.-size-2-lg > .cell.-size-2-lg {
    max-width: 100%;
  }
}
```

but I've get
```css
.grid.-size-1 > .cell {
  max-width: 100%;
}
.grid.-size-1 > .cell.-size-1 {
  max-width: 100%;
}
@media (min-width: 768px) {
  .grid.-size-1-sm > .cell {
    max-width: 100%;
  }
  .grid.-size-1-sm > .cell.-size-1 {
    max-width: 100%;
  }
}
@media (min-width: 1200px) {
  .grid.-size-1-lg > .cell {
    max-width: 100%;
  }
  .grid.-size-1-lg > .cell.-size-1 {
    max-width: 100%;
  }
}
@media (min-width: 768px) and (min-width: 768px) {
  .grid.-size-1-sm {
    max-width: 100%;
  }
}
@media (min-width: 768px) and (min-width: 1200px) {
  .grid.-size-1-lg {
    max-width: 100%;
  }
}
.grid.-size-2 > .cell {
  max-width: 50%;
}
.grid.-size-2 > .cell.-size-1 {
  max-width: 50%;
}
.grid.-size-2 > .cell.-size-2 {
  max-width: 100%;
}
@media (min-width: 768px) {
  .grid.-size-2-sm > .cell {
    max-width: 50%;
  }
  .grid.-size-2-sm > .cell.-size-1 {
    max-width: 50%;
  }
  .grid.-size-2-sm > .cell.-size-2 {
    max-width: 100%;
  }
}
@media (min-width: 1200px) {
  .grid.-size-2-lg > .cell {
    max-width: 50%;
  }
  .grid.-size-2-lg > .cell.-size-1 {
    max-width: 50%;
  }
  .grid.-size-2-lg > .cell.-size-2 {
    max-width: 100%;
  }
}
@media (min-width: 768px) and (min-width: 768px) {
  .grid.-size-2-sm {
    max-width: 50%;
  }
}
@media (min-width: 768px) and (min-width: 1200px) {
  .grid.-size-2-lg {
    max-width: 50%;
  }
}
@media (min-width: 768px) and (min-width: 768px) {
  .grid.-size-2-sm {
    max-width: 100%;
  }
}
@media (min-width: 768px) and (min-width: 1200px) {
  .grid.-size-2-lg {
    max-width: 100%;
  }
}
```
