### ISSUE TITLE
Is that possible?

### ISSUE THREAD

**Issue by geoshar** [stylus/stylus#2344]
I have a prefix called 
`.v-view-profile-login`
then i want to pass this name to next child class something like:
```stylus
.v-view-profile-login
font-size 12px
  {prevClass}-info
    border-radius 3px
      {prevClass}-home
        cursor pointer
```
for the {prevClass} i wish to use something shorter, for example `#`
the output should be:
```css
.v-view-profile-login{
font-size: 12px;
}
.v-view-profile-login-info{
border-radius: 3px;
}
.v-view-profile-login-info-home{
cursor:pointer;
}
```
Any suggestions?:)
_Edit_
Omg how simple it was, just by adding the `&`
