### ISSUE TITLE
Rendering of '#' Characters In Inline SVG Data Started to Cause A Chrome Deprecation Warning

### ISSUE THREAD

**Issue by muratgozel** [stylus/stylus#2379]
This is a new warning raised by Chrome recently.

I have the following stylus content:
```styl
brand-gray2 = rgb(232,232,232)

input[data-numeric]
  background-image: url("data:image/svg+xml;utf8,<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 5 14.263' width='5' height='14'><polygon fill='"brand-gray2"' points='0 4.327 2.5 0 5 4.327 0 4.327' /><polygon fill='"brand-gray2"' points='0 9.936 2.5 14.263 5 9.936 0 9.936' /></svg>")
```

Stylus renders it as follows:
```css
input[data-numeric] {
  background-image: url("data:image/svg+xml;utf8,<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 5 14.263' width='5' height='14'><polygon fill='#e8e8e8' points='0 4.327 2.5 0 5 4.327 0 4.327' /><polygon fill='#e8e8e8' points='0 9.936 2.5 14.263 5 9.936 0 9.936' /></svg>");
}
```

Stylus automatically converts the variable inside the `fill` attribute in the inline SVG data from `brand-gray2` to `#e8e8e8` which is a great thing.

As Chrome published a new update, the `#` characters will no longer accepted in data URI body:
```txt
[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M67, around May 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.
```

As mentioned in the deprecation notice, if i change the attr value from `fill='#e8e8e8'` to `fill='%23e8e8e8'`, warning goes away.

You can see the details of the deprecation notice here: https://www.chromestatus.com/features/5656049583390720
