### ISSUE TITLE
Prefixes in @keyframes

### ISSUE THREAD

**Issue by ndsn** [stylus/stylus#2390]
I converted to following piece of Stylus code to CSS with `stylus -P hs- main.styl`:
```Stylus
@keyframes animation
  0.0%
    opacity: 0
    transform: scale(.5)
...
```

The result I got was the following:
```CSS
@keyframes animation {
  0.hs-0% {
    opacity: 0;
    transform: scale(0.5);
  }
...
```

Is this an issue within Stylus or am I forgetting something?
