### ISSUE TITLE
 Not-efficient compilation of imported files

### ISSUE THREAD

**Issue by francescobaldan** [stylus/stylus#2398]
I have this project structure:

```
/stylus
    |-- /base
        |-- _base.styl
        |-- _colors.styl
        |-- _typography.styl
    |-- /some
    |-- /other
    |-- /folders
    |-- main.styl
```

The `main.styl` file contains only imports of the other files

So, this is the result:

`main.styl`
```stylus
@import "base/_base.styl"
@import "base/_typography.styl"
@import "base/_colors.styl"
```

`base/_base.styl`
```stylus
html,
body
	background-color #fafafa
```

`base/_colors.styl`
```stylus
.red
	color red
```

`base/_typography.styl`
```stylus
html,
body
	font-size 14px
```

I expected this code compiled in `main.css` file

```css
html,
body {
  background-color: #fafafa;
  font-size: 14px;
}
.red {
  color: #f00;
}
```

But this is the real result

```css
html,
body {
  background-color: #fafafa;
}
html,
body {
  font-size: 14px;
}
.red {
  color: #f00;
}
```

Am I doing something wrong or is this actually a bug?

Thank you
