### ISSUE TITLE
Iterate hash literal

### ISSUE THREAD

**Issue by coreyworrell** [stylus/stylus#2399]
Is is not possible to iterate a hash without first assigning it to a variable?

```stylus
for prop, abbr in ({ margin: m, padding: p })
  .mt-{abbr}
    {prop}: 1rem
```

`expected ")", got "{"`

Without `()`: `unexpected "eos"`

Thank you.

**Comment by atilkan** [comment]
What is your expected output, maybe i suggest something.

**Comment by coreyworrell** [comment]
I would expect:

```stylus
for prop, abbr in { margin: m, padding: p }
  .{abbr}t
    {prop}-top: 1rem
```

to output

```css
.mt {
  margin-top: 1rem;
}

.pt {
  padding-top: 1rem;
}
```
