### ISSUE TITLE
Iteration variable scope

### ISSUE THREAD

**Issue by coreyworrell** [stylus/stylus#2400]
It appears that if a variable is undefined, after declaring variable in a for loop, it will now be accessible outside the loop and will be set as whatever the last "looped-over" value was.

```stylus
list = #000 #111 #222

for item in list
  // do whatever here
  
body
  color: item
```

produces

```css
body {
  color: #222;
}
```

when I would expect

```css
body {
  color: item;
}
```

This is how JavaScript would behave if using `var` statements, but I think stylus should be using similar scoping as a `let` statement would behave.

It can cause issues such as:

```stylus
colors = {
  primary: #000
  secondary: #111
}

for name, color in colors
  .color-{name}
      color: color

// and then later, possibly in another @import'd file
.selector
  transition: color .15s
```

that will be rendered as

```css
.selector {
  transition: #111 .15s
}
```
