### ISSUE TITLE
Cannot reassign css variables

### ISSUE THREAD

**Issue by tinganho** [stylus/stylus#2412]
```css
body {
    --blue: #fff;
}

.selector {
   --color: var(--blue);
}
```

Here is an example:
![screen shot 2018-08-20 at 11 20 32](https://user-images.githubusercontent.com/1324476/44331938-212f3d00-a46b-11e8-9069-c17d52e9cf52.png)

https://codepen.io/anon/pen/pOzXGX
