### ISSUE TITLE
Nesting operator & is not parsed properly

### ISSUE THREAD

**Issue by Mikulas** [stylus/stylus#243]
``` css
div.flash
        &.success + &.error
                color red
```

produces

``` css
div.flash.success + &.error {
  color: red;
}
```

rather then

``` css
div.flash.success + div.flash.error {
  color: red;
}
```

This might be because of https://github.com/LearnBoost/stylus/issues/165, but dunno.
