### ISSUE TITLE
Wrong code generated after upgrading from version 0.54.5 to 0.54.6

### ISSUE THREAD

**Issue by doberkofler** [stylus/stylus#2483]
The following code snipped generates "wrong" code after upgrading from version 0.54.5 to 0.54.6:

**test.styl**
```stylus
$listWrapper = "#transitionlist";

{$listWrapper} {
	font-size: 12px;
	margin-bottom: 5px;

	/*
	 * table-Data
	 */
	table.section td {
		position: relative;
		padding: 5px;
	}

	/*column value and column description text fits in table*/
	table.section tr td:nth-child(1) {
		font-size: 10px;
	}
}
```

(wrong) css generated in 0.54.6:
```css
#transitionlist {
  font-size: 12px;
  margin-bottom: 5px;
/*
	 * table-Data
	 */
/*column value and column description text fits in table*/
table
}
#transitionlist table.section td {
  position: relative;
  padding: 5px;
}
#transitionlist .section tr td:nth-child(1) {
  font-size: 10px;
```

(correct) css generated in 0.54.6:
```css
#transitionlist {
  font-size: 12px;
  margin-bottom: 5px;
/*
	 * table-Data
	 */
/*column value and column description text fits in table*/
}
#transitionlist table.section td {
  position: relative;
  padding: 5px;
}
#transitionlist table.section tr td:nth-child(1) {
  font-size: 10px;
}
```
