### ISSUE TITLE
Do we have global variable?

### ISSUE THREAD

**Issue by dtvn** [stylus/stylus#2490]
I'm talking about this kind of global var:
- style.styl
- config.styl
- reset.styl

```STYL
// In style.styl
@require 'config'
```

```STYL
// In config.styl
schema= {
  link: red,
  primary: white
}
```

```STYL
// in reset.styl
body {
  background: schema.primary
}

a {
  color: schema.link
}
```

And then after compiling we would have:
```CSS
/* final style.css */
body {background: white}
a {color: red}
```

Can we do that? Because when I tried it return something like this: `schema has no property.primary`
