### ISSUE TITLE
combine similar 'block mixins' into one

### ISSUE THREAD

**Issue by sayomelu** [stylus/stylus#2503]
for example

```stylus
mobile()
  @media screen and (max-width: 800px)
    {block}

header
  margin: 0 auto
  +mobile()
    padding: 40px 0 0 0
    text-align: center

.site-info
  float: left
  margin: 0
  +mobile()
    float: none
    display: block
    margin: 0 auto
```

should be generated as

```css
@media screen and (max-width: 800px) {
  header {
    padding: 40px 0 0 0;
    text-align: center;
  }
  .site-info {
    float: none;
    display: block;
    margin: 0 auto;
  }
}
```

but it is generated as

```css
@media screen and (max-width: 800px) {
  header {
    padding: 40px 0 0 0;
    text-align: center;
  }
}
@media screen and (max-width: 800px) {
  .site-info {
    float: none;
    display: block;
    margin: 0 auto;
  }
}
```

the 'block mixins' is duplicate, and take too much space.

i think it should be generated to be the first result.
