### ISSUE TITLE
Stylus 0.54.7 compile @-values incorrectly

### ISSUE THREAD

**Issue by lightbringer1991** [stylus/stylus#2517]
Broken version: 0.54.7
Working version: 0.54.5

Styl code
```stylus
.is-spinner-button-loading:hover
  [ang-small-spinner]
    margin-bottom: 4px
    margin-top: -@margin-bottom
    margin-left: 13px
    margin-right: -@margin-left
```

CSS
```css
.is-spinner-button-loading:hover [ang-small-spinner] {
  margin-bottom: 4px;
  margin-top: -@margin-bottom;
  margin-left: 13px;
  margin-right: -@margin-left;
}
```
