### ISSUE TITLE
Defining placeholders inside mixins

### ISSUE THREAD

**Issue by CedSharp** [stylus/stylus#2521]
In sass, I like to work with colors using maps (hashes) and then transforming those into placeholders.
I can then simply extend them and I get colors without tons of variables. those that I don't use are simply not outputted to css (since they are placeholders) and hence I get a feature similar to tree-shaking.

Here is an example of what I like to do:
```scss
$color-blue: (
  '50':  #E3F2FD,
  '100': #BBDEFD,
  '200': #90CAF9,
  '300': #64B5F6,
  '400': #42A5F5,
  '500': #2196F3,
  '600': #1E88e5,
  '700': #1976D2,
  '800': #1565C0,
  '900': #0D47A1
);

@mixin makeColorPlacholders($color, $prefix, $property:'color') {
  @each $val, $col in $color {
    %#{$prefix}-#{$val} {
      #{$property}: $col;
    }
  }
}

@include makeColorPlacholders($color-blue, 'c-blue', 'color');

body {
  @extend %c-blue-300;
}
```

This will generate all of the colors in the format of "%c-blue-<50 to 900>" and then I can just extend them.

I can do something similar in stylus using a for loop, but it doesn't seem to work if I move that for loop inside of a mixin.

The following works:
```stylus
Blues = {
  '50':  #E3F2FD,
  '100': #BBDEFD,
  '200': #90CAF9,
  '300': #64B5F6,
  '400': #42A5F5,
  '500': #2196F3,
  '600': #1E88e5,
  '700': #1976D2,
  '800': #1565C0,
  '900': #0D47A1
}

for val, col in Blues
  $c-blue-{val}
    color col

body
  @extend $c-blue-300 !optional```

But if I move the for loop in a mixin, like the below, it doesn't work:
```stylus
makeColorPlaceholders(colors, prefix, property='color')
  for val, col in colors
    ${prefix}-{val}
      {property} col

body
  @extend $c-blue-300```

Either I missed something important, or this feature is not implemented.
I don't know if this is supposed to be a bug, but to me it certainly does appear to be one.

NOTE: All of this was tested using both codepend and the Try Stylus! compiler from the stylus website.

**Comment by groenroos** [comment]
This bit of your markup only _defines_ the mixin:

```stylus
makeColorPlaceholders(colors, prefix, property='color')
    for val, col in colors
        ${prefix}-{val}
            {property} col
```

You need to also separately _run_ the mixin in order to generate the rulesets to be extended, just like you did with the `@include` statement in the Sass example, i.e.

```stylus
makeColorPlaceholders(Blues, 'c-blue', 'color')
```

Putting it all together would look something like so;

```stylus
Blues = {
    '50':  #E3F2FD,
    '100': #BBDEFD,
    '200': #90CAF9,
    '300': #64B5F6,
    '400': #42A5F5,
    '500': #2196F3,
    '600': #1E88e5,
    '700': #1976D2,
    '800': #1565C0,
    '900': #0D47A1
}

makeColorPlaceholders(colors, prefix, property='color')
    for val, col in colors
        ${prefix}-{val}
            {property} col

makeColorPlaceholders(Blues, 'c-blue', 'color')

body
    @extend $c-blue-300
```

which yields the following CSS:

```css
body {
  color: #64b5f6;
}
```

Does this look like what you were intending to achieve?
