### ISSUE TITLE
Stylus can treat a set of element selectors (like `tbody tr` or `thead tr`) as property/value pairs when commas are not used

### ISSUE THREAD

**Issue by jh-pq** [stylus/stylus#2542]
Stylus appears to treat a set of element selectors, like `tbody tr` and `thead tr`, as properties instead of selectors when the following conditions are met:

* They appear in a list of selectors for a style definition
* The list of selectors is not using commas
* They appear before other non-element selectors in the list
* They are not the last selector in the list
* This definition is nested inside another definition

# Minimal test case

```stylus
table
  border 0

  tbody tr
  .table-body-row
    color red
```

This generates the following CSS. Note the `tbody: tr;` property definition:
```css
table {
  border: 0;
  tbody: tr;
}
table .table-body-row {
  color: #f00;
}
```

[Stylus sandbox link](https://stylus-lang.com/try.html#?code=table%0A%20%20border%200%0A%0A%20%20tbody%20tr%0A%20%20.table-body-row%0A%20%20%20%20color%20red)

![Screenshot 2020-06-25 at 13 22 08](https://user-images.githubusercontent.com/33226922/85718945-e80b2800-b6e6-11ea-8788-9c95d1ec8c04.png)

# Workarounds

Use commas:

```stylus
table
  border 0

  tbody tr,
  .table-body-row
    color red
```

```css
table {
  border: 0;
}
table tbody tr,
table .table-body-row {
  color: #f00;
}
```

Position other unambiguous selectors first:

```stylus
table
  border 0

  .table-body-row
  tbody tr
    color red
```

```css
table {
  border: 0;
}
table .table-body-row,
table tbody tr {
  color: #f00;
}
```

# Related observations

If multiple such selectors occur in a list, all of them are consumed as properties except the last one which is correctly interpreted as a selector.

```stylus
table
  border 0

  thead tr
  tbody tr
  tr td
  th td
    color red
```

```css
table {
  border: 0;
  thead: tr;
  tbody: tr;
  tr: td;
}
table th td {
  color: #f00;
}
```

If more than two elements are used, this case still applies, with each element after the first being treated as part of a value list.

```stylus
table
  border 0

  thead tr td
  tbody tr td
    color red
```

```css
table {
  border: 0;
  thead: tr td;
}
table tbody tr td {
  color: #f00;
}
```

If the selectors are not nested, everything is OK.

```stylus
thead tr td
tbody tr td
  color red
```

```css
thead tr td,
tbody tr td {
  color: #f00;
}
```
