### ISSUE TITLE
@extends not working as expected with  @media

### ISSUE THREAD

**Issue by laggingreflex** [stylus/stylus#2550]
I have the following style:

# Style

```styl
.theme-dark
  --font-color #ffffff
body
  @media (prefers-color-scheme: dark)
      @extends .theme-dark
```

# Resulting CSS (Actual)

```css
.theme-dark,
body {
  --font-color: #fff;
}
```

# Expected

```css
.theme-dark {
  --font-color: #fff;
}
@media (prefers-color-scheme: dark) {
  body {
    --font-color: #fff;
  }
}
```

Edit: Oops. Already reported previously: #669, #1095, #1972
