### ISSUE TITLE
Styles duplication with webpack stylus-loader

### ISSUE THREAD

**Issue by mytecor** [stylus/stylus#2556]
### Expected Behavior
```css
.box,.child,.test{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
.child{border-style:dotted;border-color:#008000}
.test{border-color:#f00}
```
### Actual Behavior
```css
.box{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
.box,.child{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
.child{border-style:dotted;border-color:#008000}
.box,.test{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
.test{border-color:#f00}
```
### How Do We Reproduce?
[Repo](https://github.com/midnightcoder-pro/stylus-duplication-demo)
```
yarn build
```

@evilebottnawi [recommended](https://github.com/webpack-contrib/stylus-loader/issues/293#issuecomment-707884941) me to reopen this issue in `stylus` repo
