### ISSUE TITLE
0fr is erroneously compressed to 0

### ISSUE THREAD

**Issue by jazzzz** [stylus/stylus#2570]
Input:

```stylus
*
  grid-template-columns 0fr 1fr
```

Compiling this file with Stylus 0.54.8 with the `--compress` option gives:

```css
*{grid-template-columns:0 1fr}
```

The expected output is:

```css
*{grid-template-columns:0fr 1fr}
```
