### ISSUE TITLE
stylus css conversion doesn't parse css correctly

### ISSUE THREAD

**Issue by jtopenpetition** [stylus/stylus#2577]
this might possibly be a duplicate, but I can't find one. might also be a library issue.

the **CSS** 
```CSS
.selector1
.selector2 {
    font-weight:bold
}
```

will be converted (via `--css` cli option) to stylus
```styl
.selector1
.selector2
  font-weight: bold
```

it should be 
```styl
.selector1 .selector2
  font-weight: bold
```
or with indentation:
```styl
.selector1
  .selector2
    font-weight: bold
```
