### ISSUE TITLE
:is(a,b) selector doesn't parse correctly

### ISSUE THREAD

**Issue by RiedleroD** [stylus/stylus#2581]
it does work in some circumstances, but since the comma is taken as a sign that a new selector has started, the following problems arise:

### stylus
```css
a{
  &:is(.this,.that){
    color:red;
  }
}
b,c{
  &:is(.this,.that){
    color:blue;
  }
}
d,e{
  &:is(.this\,/.that){
    color:green;
  }
}
```
### expected result
```css
a:is(.this,.that){
  color:#f00;
}
b:is(.this,.that),
c:is(.this,.that){
  color:#00f;
}
d:is(.this,.that),
e:is(.this,.that){
  color:#008000;
}
```
### actual result:
```css
a:is(.this,
a .that) {
  color: #f00;
}
b:is(.this,
c:is(.this,
b .that),
c .that) {
  color: #00f;
}
d:is(.this,
e:is(.this,
.that) {
  color: #008000;
}
```
### workarounds
```css
a{
  &:is(.this,/.that){
    color:red;
  }
}
b,c{
  &.this,
  &.that{
    color:blue;
  }
}
```
### workaround results
```css
a:is(.this,
.that) {
  color: #f00;
}
b.this,
c.this,
b.that,
c.that {
  color: #00f;
}
```

It would be nice to at least have the possiblity to actually escape the comma, but that isn't currently possible.
Also, using the :is() operator in parsing could reduce style size, but that's not as important as properly being able to use the selector manually.

**Comment by coreyworrell** [comment]
Another example I'm experiencing:

```stylus
:where(.wp-block-cover.has-background-dim, .wp-block-group.has-background, .wp-block-media-text).alignfull + :where(.wp-block-cover.has-background-dim, .wp-block-group.has-background, .wp-block-media-text).alignfull {
    margin-top: 0;
}
```
 **actual result** (missing `.wp-block-group.has-background` part in last `:where()`
```css
:where(.wp-block-cover.has-background-dim, .wp-block-group.has-background, .wp-block-media-text).alignfull + :where(.wp-block-cover.has-background-dim, .wp-block-media-text).alignfull {
    margin-top: 0;
}
```

@RiedleroD workaround didn't work in this case, so for now I'm using `@css` feature, but of course that only works if no variables or other stylus features are needed.
