### ISSUE TITLE
Incorrect handling of negated media queries (`@media not` ...)

### ISSUE THREAD

**Issue by kugland** [stylus/stylus#2591]
Stylus v0.54.8 handles negated media queries (`@media not ...`) incorrectly.

Code:

```stylus
@media all and (min-width: 10px)
  @media not all and (min-width: 20px)
    body
      background: red

@media all and (min-width: 10px)
  @media not screen and (min-width: 20px)
    body
      background: green
```

Transpiled CSS:

```css
@media all and (min-width: 20px) and (min-width: 10px) {
  body {
    color: #f00;
  }
}
@media all and (min-width: 10px) and (min-width: 20px) {
  body {
    background: #008000;
  }
}
```

Expected CSS:

```css
@media all and (min-width: 10px) {
  @media not all and (min-width: 20px) {
    body {
      background: #f00;
    }
  }
}
@media all and (min-width: 10px) {
  @media not screen and (min-width: 20px) {
    body {
      background: #008000;
    }
  }
}
```

**Comment by conlanpatrek** [comment]
For what it's worth I'm seeing a similar issue with a simpler repro as of 0.55. My repro, without the nested media queries:

```styl
@media not all and (max-width: 1000px)
    body
        background red
```

No css is emitted at all here. Note that the correct css is emitted if you change the query from `not all` to `not screen` so I feel like there is a hint there.

Let me know if you feel it's unrelated enough for me to open a new ticket and I will.

**Comment by Phroneris** [comment]
Even this simple code results in an error.

`test.styl`:

```stylus
@media not (width: 500px)
  .test
    display: block
```

Tested on Stylus 0.64.0 command installed by npm globally,
Console is Git Bash by Git for Windows.

```console
$ stylus test.styl
C:\Users\<user>\AppData\Roaming\nvm\v24.8.0\node_modules\stylus\bin\stylus:684
              throw err;
              ^

ParseError: test.styl:1:13
   1| @media not (width: 500px)
------------------^
   2|   .test
   3|     display: block
   4|

expected "indent", got "("

    at Parser.error (C:\Users\<user>\AppData\Roaming\nvm\v24.8.0\node_modules\stylus\lib\parser.js:252:11)
    at Parser.expect (C:\Users\<user>\AppData\Roaming\nvm\v24.8.0\node_modules\stylus\lib\parser.js:280:12)
    at Parser.block (C:\Users\<user>\AppData\Roaming\nvm\v24.8.0\node_modules\stylus\lib\parser.js:911:12)
    at Parser.media (C:\Users\<user>\AppData\Roaming\nvm\v24.8.0\node_modules\stylus\lib\parser.js:1227:24)
    at Parser.stmt (C:\Users\<user>\AppData\Roaming\nvm\v24.8.0\node_modules\stylus\lib\parser.js:836:30)
    at Parser.statement (C:\Users\<user>\AppData\Roaming\nvm\v24.8.0\node_modules\stylus\lib\parser.js:743:21)
    at Parser.parse (C:\Users\<user>\AppData\Roaming\nvm\v24.8.0\node_modules\stylus\lib\parser.js:229:25)
    at Renderer.render (C:\Users\<user>\AppData\Roaming\nvm\v24.8.0\node_modules\stylus\lib\renderer.js:64:24)
    at C:\Users\<user>\AppData\Roaming\nvm\v24.8.0\node_modules\stylus\bin\stylus:678:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)

Node.js v24.8.0
```

---

Without the `not`, everything is fine.

```stylus
@media (width: 500px)
  .test
    display: block
```

Result CSS:

```css
@media (width: 500px) {
  .test {
    display: block;
  }
}
```

---

`@css` literal also works, but it's no longer Stylus.

```stylus
@css {
  @media not (width: 500px) {
    .test {
      display: block;
    }
  }
}
```

Result CSS:

```css
/* A blank line is inserted here */
@media not (width: 500px) {
  .test {
    display: block;
  }
}
```
