### ISSUE TITLE
unexpected in hashes

### ISSUE THREAD

**Issue by tang412** [stylus/stylus#2638]
**To reproduce:**

```styl
colors = {
  primary: red,
  secondary: blue,
}

.btn
  color colors.primary
  &:hover
    color: colors.secondary

primary = red
secondary = blue

.bbtn
  color primary
  &:hover
    color secondary
```

**Current behavior:**
```styl
// unexpected
.btn color colors.primary,
.btn:hover {
  color: #00f;
}

// expected
.bbtn {
  color: #f00;
}
.bbtn:hover {
  color: #00f;
}
```
I'm not sure if it's my problem or problem of stylus

**Comment by iChenLei** [comment]
Add colon `:` will work ad expected.
```stylus
colors = {
  primary: red,
  secondary: blue,
}

.btn
  color: colors.primary // <---  add `:` here
  &:hover
    color: colors.secondary

primary = red
secondary = blue

.bbtn
  color primary
  &:hover
    color secondary
```
output css
```css
.btn {
  color: #f00;
}
.btn:hover {
  color: #00f;
}
.bbtn {
  color: #f00;
}
.bbtn:hover {
  color: #00f;
}
```
