### ISSUE TITLE
@import and @require css doesn't support block-level

### ISSUE THREAD

**Issue by zkqiang** [stylus/stylus#2655]
**To reproduce:**

```styl
.foo
  @require "test.css"
```

**Current behavior:**

If `@import` or `@require` a stylus file, they can support block-level, but not if it is a css file.

For example, the above code will generate:

```css
.test-class {
  margin-top: 1px;
}
```

`.foo` is not involved

**Expected behavior:**

```css
.foo .test-class {
  margin-top: 1px;
}
```

**Environment information:**

- `stylus` version: 0.56.0
- `nodejs` version: 12.22.7
