### ISSUE TITLE
Reduce compiled output for CSS level 4 combination selectors

### ISSUE THREAD

**Issue by camlnrd** [stylus/stylus#2694]
Reduce the compiled output for CSS level 4 combination selectors. It's nice to have a more compact output when the project does not require minification.

**Stylus**

```styl
:is(header, main, footer) p:hover
  color: red

:where(header, main, footer)
  color: red

body :not(.foo, .bar, .baz)
  color: red

h1:has(+ p)
  color: red
```

**Current behavior:**

```css
:is(header,
main,
footer) p:hover {
  color: #f00;
}
:where(header,
main,
footer) {
  color: #f00;
}
body :not(.foo,
.bar,
.baz) {
  color: #f00;
}
h1:has(+ p) {
  color: #f00;
}
```

**Expected behavior:**

```css
:is(header, main, footer) p:hover {
  color: #f00;
}
:where(header, main, footer) {
  color: #f00;
}
body :not(.foo, .bar, .baz) {
  color: #f00;
}
h1:has(+ p) {
  color: #f00;
}
```

Thank you for the CSS level 4 combination selectors addition.

**Environment information:**

- `stylus` version: 0.58.1
- `nodejs` version: v17.6.0
