### ISSUE TITLE
Firefox can't parse at-rule generated by @keyframes

### ISSUE THREAD

**Issue by aleclarson** [stylus/stylus#2698]
**To reproduce:**

```styl
@keyframes loader-rotate
  100%
    transform: rotate(360deg)
```

**Current behavior:**

Firefox fails to parse the CSS file:
```
Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’.
```

The generated CSS looks like this:
```css
@-moz-keyframes loader-rotate {
  100% {
    transform: rotate(360deg);
  }
}
@-webkit-keyframes loader-rotate {
  100% {
    transform: rotate(360deg);
  }
}
@-o-keyframes loader-rotate {
  100% {
    transform: rotate(360deg);
  }
}
@keyframes loader-rotate {
  100% {
    transform: rotate(360deg);
  }
}
```

**Expected behavior:**

Generate CSS that is compatible with modern Firefox versions.

**Environment information:**

- `stylus` version: 0.56.0
- `nodejs` version: 18.0.0
- Firefox version: 102.0b3
