### ISSUE TITLE
Wrong compile output with non top level element selector followed by new line comment.

### ISSUE THREAD

**Issue by suienzan** [stylus/stylus#2708]
**To reproduce:**

```styl
@-moz-document domain("www.google.com") {
  body, 
  // comment
  .class {
    background: #000;
  }
}
```

**Current behavior:**

compile output

```css
@-moz-document domain("www.google.com") {
  body: ,;
  .class {
    background: #000;
  }
}
```

**Expected behavior:**

output

```css
@-moz-document domain("www.google.com") {
  body,
  .class {
    background: #000;
  }
}
```

**Environment information:**

- `stylus` version: [https://stylus-lang.com/try.html](https://stylus-lang.com/try.html)

[demo1](https://stylus-lang.com/try.html#?code=%40-moz-document%20domain(%22www.google.com%22)%20%7B%0A%20%20body%2C%0A%20%20%2F%2F%20comment%0A%20%20.class%20%7B%0A%20%20%20%20background%3A%20%23000%3B%0A%20%20%7D%0A%7D) and [demo2](https://stylus-lang.com/try.html#?code=%40media%20print%20%7B%0A%20%20body%2C%20%0A%20%20%2F%2F%20comment%0A%20%20.class%20%7B%0A%20%20%20%20background%3A%20%23000%3B%0A%20%20%7D%0A%7D).

openstyles/stylus#1460
