### ISSUE TITLE
:is not work with & 

### ISSUE THREAD

**Issue by usrtax** [stylus/stylus#2710]
**To reproduce:**

```styl
input:is([type=text], [type=password])
  & + label
   color #f00
```

**Current behavior:**

```
input:is([type=text] + label,[type=password]) + label {
  color: #f00;
}
```
**Expected behavior:**
```
input:is([type=text] ,[type=password]) + label {
  color: #f00;
}
```

- `stylus` version:v0.58.1

**Comment by iChenLei** [comment]
```stylus
input:is([type=text], [type=password])
  & + label
   color #f00
```
It looks like `stylus` parse `input:is([type=text], [type=password])` as two selectors `input:is([type=text]` and `[type=password])`, and then apply `&` parent selector. so we get:

```css
input:is([type=text] + label,[type=password]) + label {
  color: #f00;
}
```
