### ISSUE TITLE
Char Escaping in some cases leaves backshash #g[value=\"{foo}\"] --> #g[value=\"bar"]

### ISSUE THREAD

**Issue by pabli24** [stylus/stylus#2729]
**To reproduce:**

```styl
foo = bar
#div[value=\"{foo}\"] > #message
	color: #fff
#div > #message [value=\"{foo}\"]
	color: #fff
#div > .message [value=\"{foo}\"]
	color: #fff
#a[value=\"{foo}\"]
#b[value=\"{foo}\"]
#c[value=\"{foo}\"]
#d[value=\"{foo}\"]
#e[value=\"{foo}\"]
#f[value=\"{foo}\"]
#g[value=\"{foo}\"]
#h[value=\"{foo}\"]
#i[value=\"{foo}\"]
#j[value=\"{foo}\"]
#k[value=\"{foo}\"]
#l[value=\"{foo}\"]
#m[value=\"{foo}\"]
#n[value=\"{foo}\"]
#o[value=\"{foo}\"]
#p[value=\"{foo}\"]
#q[value=\"{foo}\"]
#r[value=\"{foo}\"]
#s[value=\"{foo}\"]
#t[value=\"{foo}\"]
#u[value=\"{foo}\"]
#v[value=\"{foo}\"]
#w[value=\"{foo}\"]
#x[value=\"{foo}\"]
#y[value=\"{foo}\"]
#z[value=\"{foo}\"]
	color: #fff
```

**Current behavior:**

```styl
#div[value="bar"] > #message {
  color: #fff;
}
#div > #message [value=\"bar"] {
  color: #fff;
}
#div > .message [value="bar"] {
  color: #fff;
}
#a[value="bar"],
#b[value="bar"],
#c[value="bar"],
#d[value="bar"],
#e[value="bar"],
#f[value="bar"],
#g[value=\"bar"],
#h[value=\"bar"],
#i[value=\"bar"],
#j[value=\"bar"],
#k[value=\"bar"],
#l[value=\"bar"],
#m[value=\"bar"],
#n[value=\"bar"],
#o[value=\"bar"],
#p[value=\"bar"],
#q[value=\"bar"],
#r[value=\"bar"],
#s[value=\"bar"],
#t[value=\"bar"],
#u[value=\"bar"],
#v[value=\"bar"],
#w[value=\"bar"],
#x[value=\"bar"],
#y[value=\"bar"],
#z[value=\"bar"] {
  color: #fff;
}
```

**Expected behavior:**
```styl
#div[value="bar"] > #message {
  color: #fff;
}
#div > #message [value="bar"] {
  color: #fff;
}
#div > .message [value="bar"] {
  color: #fff;
}
#a[value="bar"],
#b[value="bar"],
#c[value="bar"],
#d[value="bar"],
#e[value="bar"],
#f[value="bar"],
#g[value="bar"],
#h[value="bar"],
#i[value="bar"],
#j[value="bar"],
#k[value="bar"],
#l[value="bar"],
#m[value="bar"],
#n[value="bar"],
#o[value="bar"],
#p[value="bar"],
#q[value="bar"],
#r[value="bar"],
#s[value="bar"],
#t[value="bar"],
#u[value="bar"],
#v[value="bar"],
#w[value="bar"],
#x[value="bar"],
#y[value="bar"],
#z[value="bar"] {
  color: #fff;
}
```

**Environment information:**

- `stylus` version: 0.59.0
- `nodejs` version: v16.17.0

**Comment by pabli24** [comment]
There is something wrong with the IDs and not just with the char escaping
input
```stylus
foo = bar
//comment test
div[value="{foo}"],
body[value="{foo}"],
#b[value="{foo}"],
#c[value="{foo}"],
#d[value="{foo}"],
#e[value="{foo}"],
#f[value="{foo}"],
#g[value="{foo}"],
#h[value="{foo}"],
#i[value="{foo}"],
#j[value="{foo}"],
#k[value="{foo}"],
#l[value="{foo}"],
#m[value="{foo}"],
#n[value="{foo}"],
#o[value="{foo}"],
#p[value="{foo}"],
#q[value="{foo}"],
#r[value="{foo}"],
#s[value="{foo}"],
#t[value="{foo}"],
#u[value="{foo}"],
#v[value="{foo}"],
#w[value="{foo}"],
#x[value="{foo}"],
#y[value="{foo}"],
#z[value="{foo}"] {
	color: #fff
}
//This double slash comment is not removed

div[value="{foo}"],
body[value="{foo}"],
#b[value="{foo}"],
#c[value="{foo}"],
#d[value="{foo}"],
#e[value="{foo}"],
#f[value="{foo}"] {
	color: #fff
}
```
output
```css
div[value="{foo}"],
body[value="{foo}"],
#b[value="{foo}"],
#c[value="{foo}"],
#d[value="{foo}"],
#e[value="{foo}"],
#f[value="{foo}"],
#g[value="bar"],
#h[value="bar"],
#i[value="bar"],
#j[value="bar"],
#k[value="bar"],
#l[value="bar"],
#m[value="bar"],
#n[value="bar"],
#o[value="bar"],
#p[value="bar"],
#q[value="bar"],
#r[value="bar"],
#s[value="bar"],
#t[value="bar"],
#u[value="bar"],
#v[value="bar"],
#w[value="bar"],
#x[value="bar"],
#y[value="bar"],
#z[value="bar"] {
	color: #fff
}
//This double slash comment is not removed

div[value="bar"],
body[value="bar"],
#b[value="bar"],
#c[value="bar"],
#d[value="bar"],
#e[value="bar"],
#f[value="bar"] {
  color: #fff;
}

```
