### ISSUE TITLE
Navigation makes the code entry disappear

### ISSUE THREAD

**Issue by nilslindemann** [stylus/stylus#2744]
Not sure if it is my browser - Ungoogled Chromium (103.0.5060.114 x64) - or my OS - Windows 7 - or a bug in Codemirror or in your add-on.

When navigating back to the overview page of the styles, and then back to the specific style page, the Codemirror text entry disappears. It requires pressing the reload button to appear again. Sometimes the back button is also dysfunctional. Stylus version 1.5.26.

On another browser - Iridium 2021.10 - with an older version of stylus - Version 1.5.17 - this does not happen.

---

Unrelated, but I need to get this off my chest - I like the older version of Stylus better. The newer has a more confusing GUI. You have added more features, that is nice. Now you need a better plan how to include all this. An expert mode comes to mind, which can be enabled when clicking on the icon. By default, the style page should look much more simple. Most non-programmers will never use most of these features, which you show to them right now. What they _will_ use is probably just this, and nothing else:

```css
#style-settings-btn,
#mozilla-format-buttons,
#details-wrapper,
.edit-actions,
.code-label /*,
.CodeMirror-gutters,
.CodeMirror-linenumber,
.CodeMirror-sizer ,
.Codemirror-sucks */
{
    display: none !important;
}

#header {
    box-shadow: none;
}

.buttons {
    min-width: 20em;
}

#cancel-button {
    position: absolute;
    top: 1.4em;
}

#heading {
    position: relative;
    right: -1.6em;
}

#basic-info-enabled {
    margin-top: 1.5em
}

/* Going too far here
#header-resizer,
#header-resizer::after,
.resize-grip,
.resize-grip::after {
    border: 0 !important;
}
*/

```
