### ISSUE TITLE
Wrong compiling for :is, :has, :where

### ISSUE THREAD

**Issue by cyfung1031** [stylus/stylus#2750]
```stylus
:is(section.is-styling, aside.is-styling, footer.is-styling) {
  a {
    color: red;
  }
}
```

is wrongly composed as 

```stylus
:is(section.is-styling a, aside.is-styling a, footer.is-styling) a{
  color: red;
}
```

<img width="736" alt="Screen Shot 2023-01-11 at 16 50 35" src="https://user-images.githubusercontent.com/44498510/211748659-6068793d-5cb2-4d80-bb09-494cef26283c.png">

**Comment by cyfung1031** [comment]
https://stylus-lang.com/try.html

Same result in official playground.
<img width="901" alt="Screen Shot 2023-01-11 at 18 19 54" src="https://user-images.githubusercontent.com/44498510/211767191-41c57588-0107-402e-8079-920efe606de5.png">

**Comment by cyfung1031** [comment]
Currently I am doing this way to ensure the correct compiling output.

```stylus
buildL4(type, args...) {
    st1 = join('', ':', type, '(', join('\, ', args), ')')
    selector(st1)
}
```

<img width="724" alt="Screen Shot 2023-01-11 at 18 57 02" src="https://user-images.githubusercontent.com/44498510/211775759-be64e815-3d5d-4c94-98e6-a29ecf861012.png">
<img width="777" alt="Screen Shot 2023-01-11 at 18 57 07" src="https://user-images.githubusercontent.com/44498510/211775783-039de97b-91eb-4c69-b49f-685e33c9dd01.png">

**Comment by EmmanuelBeziat** [comment]
This is still an issue today, even with simpler examples:

```stylus
.menu-item:is(:hover, :focus)
    color red
```

Should render:
```css
.menu-item:is(:hover, :focus) { color: red; }
```

But render this instead:
```css
.menu-item:is(:hover, .menu-item :focus) { color: red; }
```

**Comment by kyohei-23** [comment]
This problem also appears to occur when `:not` is used

From this I can infer that the problem is apparently occurring in pseudo-classes that accept a list of selectors in general.

![image](https://github.com/stylus/stylus/assets/70838736/ce27bba2-6057-428c-9e7c-9967a95c33e9)

**Comment by iChenLei** [comment]
Hello, everyone. I don't have enough bandwidth to fix it, so you can use [`@css`](https://stylus-lang.com/docs/literal.html) as a workaround.

**Comment by cyfung1031** [comment]
> Hello, everyone. I don't have enough bandwidth to fix it, so you can use [`@css`](https://stylus-lang.com/docs/literal.html) as a workaround.

can use this function to avoid the problem, but I just want it to be fixed officially.

```css
buildL4(type, args...) {
    st1 = join('', ':', type, '(', join('\, ', args), ')')
    selector(st1)
}

{buildL4('is', 'section.is-styling', 'aside.is-styling', 'footer.is-styling')} {
  a {
    color: red;
  }
}


.is-styling{buildL4('is', 'section', 'aside', 'footer')} {
  b {
    color: blue;
  }
}

```
It is proven working since I created this issue.
