### ISSUE TITLE
grid-area values are replaced with variables

### ISSUE THREAD

**Issue by IdkGoodName** [stylus/stylus#2752]
**To reproduce:**

```style
info = #0000FF

.class_parent
    display: grid
    grid-template-areas: "icon title" "info info"
    .class_info
        grid-area: info
```

**Current behavior:**

It replaces `info` value in `grid-area` with `info` variable, which causes it to compile to `grid-area: #0000FF`. This looks something like this after compiling:

```css
.class_parent {
    display: grid;
    grid-template-areas: "icon title" "info info";
}
.class_parent .class_info {
    grid-area: #0000FF;
}
```

**Expected behavior:**

Leaving `info` in `grid-area` and not modifying it. I guess it is expected to replace it usually in Stylus and it would be consistent of it, but for something like `grid-area` this doesn't entirely make sense.

**Environment information:**

- `stylus` version: `0.56.0`
- `nodejs` version: `19.4.0`
