### ISSUE TITLE
Wrong compilation in font-family

### ISSUE THREAD

**Issue by elliot-zzh** [stylus/stylus#2760]
**To reproduce:**

```styl
*
  font-family: "Roboto Mono", monospace
```

**Current behavior:**

output:

```css
* {
  font-family: Roboto Mono, monospace;
}
```

**Expected behavior:**

output:

```css
* {
  font-family: "Roboto Mono", monospace;
}
```

**Environment information:**

- `stylus` version: latest
- `nodejs` version: 18

Additionally, I use Stylus with Astro.
