### ISSUE TITLE
when I define a javascript hash variable I can't get expected iteration result.

### ISSUE THREAD

**Issue by hooozen** [stylus/stylus#2780]
**To reproduce:**

```node
var stylus = require('stylus');

str = `
.foo 
  for k, v in obj
    {k}: v;
`
stylus(str)
  .set('filename', 'nesting.css')
  .define("obj", { display: 'block', color: 'white' })
  .render(function (err, css) {
    if (err) throw err;
    console.log(css);
  })
```

**Current behavior:**

```css
.foo {
  display: 0;
  color: 1;
}
```

**Expected behavior:**

```css
.foo {
  display: block;
  color: white;
}
```

**Environment information:**

- `stylus` version: 0.59.0
- `nodejs` version: 18.5.0
