### ISSUE TITLE
JavaScript API `define` need able to return hash Object when second parameter is a function.

### ISSUE THREAD

**Issue by hooozen** [stylus/stylus#2782]
**To reproduce:**

```node
var stylus = require('stylus');

str = `
.foo 
  for p, v in obj
    {p}: v

.bar
  for p, v in getObj(#aaa)
    {p}: v
`
stylus(str)
  .set('filename', 'nesting.css')
  .define('obj', { display: 'block', color: 'white' }, true)
  .define("getObj", function (color) {
    return { display: 'block', color: color }
  }, true)
  .render(function (err, css) {
    if (err) throw err;
    console.log(css);
  }, true)
```

**Current behavior:**
```css
.foo {
  display: 'block';
  color: 'white';
}
.bar {
  display: 0;
  color: 1;
}

```

**Expected behavior:**

```css
.foo {
  display: 'block';
  color: 'white';
}
.bar {
  display: block;
  color: #aaa;
}

```

When I pass a JavaScript object variable to  `define()`  and want to get a hash object variable, I can do this by setting `raw` to `true`, as mentioned in #2780 and #1286. But when I pass a function that returns a JavaScript object to `define()`, the `raw` will not work as the former. see [utils.js#L304](https://github.com/stylus/stylus/blob/dev/lib/utils.js#L304).

**Environment information:**

- `stylus` version: 0.59.0
- `nodejs` version: 18.5.0
