### ISSUE TITLE
Stylus Parser Incorrectly Handles Color Functions with Special Operators (e.g., oklch, oklab)

### ISSUE THREAD

**Issue by sjfhsjfh** [stylus/stylus#2929]
**To reproduce:**

```sh
echo ":root\n  --wtf: oklch(0.65 0.15 245 / 35%)" | stylus
```

**Current behavior:**

The above command gives the following output:

```css
:root {
  --wtf: oklch(0.65 0.15 7%);
}
```

**Expected behavior:**

According to mdn web [docs](https://developer.mozilla.org/docs/Web/CSS/color_value/oklch)

```css
:root {
  --wtf: oklch(0.65 0.15 245 / 35%);
}
```

**Environment information:**

- `stylus` version: `0.64.0`
- `nodejs` version: `v23.6.1`

Any function with operators inside parentheses (like `oklch` or `oklab`) causes similar issues. This seems to be a design problem, where the `stylus` parser’s handling of operators doesn’t match CSS’s syntax, leading to incorrect parsing of color functions like oklch.
