### ISSUE TITLE
Ability to use mixins in selectors

### ISSUE THREAD

**Issue by ghost** [stylus/stylus#364]
Using mixins to generate selectors is very helpful, but actually we need to pass by a variable.

When they are called directly from selectors, it's not working:

``` css

hx()
  arguments = 1..6  if arguments is null
  buf = ''
  for arg, index in arguments
    buf += (index ? ',' : '') + 'h%s' % arg

// this case works

hx = hx(1..3)

{hx}
  color: #444

// doesn't render any selector

{hx()}
  color: #444

// throw a parserError:
// expected "indent", got "in"

{hx(1..3)}
  color: #444

```
