### ISSUE TITLE
Parent selector accessor ^ (feature request)

### ISSUE THREAD

**Issue by yuchi** [stylus/stylus#424]
I'd like to propose a new selector meta-character to acces the parent selector **block**. A possible character is the _caret_, `^` which resembles an up arrow.

Another option is `<` which looks good compared with `>`.

Example:

``` stylus
button.action
  span strong
    color blue
    ^:focus, ^:hover
      color black
```

should yeld to:

``` css
button.action span strong {
  color: blue;
}
button.action:hover span strong,
button.action:focus span strong {
  color: black;
}
```

If used with something after should throw an exception (`^ div` is meaningless):

``` stylus
button
  span
    color red
  ˆ span.icon // what should stylus do here?
    color blue
```

Used alone should not change nothing:

``` stylus
button
  span
    color red
    ^
      color blue
```

should yeld to

``` css
button span {
  color: red;
}
button span {
  color: blue;
}
```

**Comment by namero999** [comment]
I'm not sure this particular feature was covered by #1240.

Another example right from some stylus I'm working on.

We want the resulting CSS
```css
/* element that shows an inner element at hover */

li.entry {
  width: 300px;
}

li.entry > .overlay {
  display: none;
}

li.entry:hover > .overlay {
  display: block;
}
```
Currently the stylus needed is

```css
li.entry
  width 300px
  > .overlay
    display none
  &:hover > .overlay
    display block
```

While it would be great if it was

```css
li.entry
  width 300px
  > .overlay
    display none
    ^:hover
      display block
```

The reasoning behind this, is that it helps encapsulate better a specific behaviour (it is something specific only to overlay).

Any comment if this is already achievable, or planned to be implemented?
