### ISSUE TITLE
Fix current-property with commas

### ISSUE THREAD

**Issue by tj** [stylus/stylus#472]
this works:

``` css
replace(expr, str, val)
  expr = clone(expr)
  for e, i in expr
    if str == e
      expr[i] = val
  expr

bar()
  prop = current-property[0]
  val = current-property[1]
  add-property(prop, replace(val, '__CALL__', unquote('foo')))
  add-property(prop, replace(val, '__CALL__', unquote('bar')))
  unquote('baz')

body
  background: test bar()
```

producing:

``` css

body {
  background: test foo;
  background: test bar;
  background: test baz;
}
```

however this does not:

``` css
body
  background: test, bar()
```
