### ISSUE TITLE
Stylus --css throws "unexpected }";

### ISSUE THREAD

**Issue by Baggz** [stylus/stylus#530]
Hi, 

I'm trying to convert some CSS files to Stylus, but there's an error. The details are as follows...
### Output

```
stylus --css bounce.css 

/usr/local/lib/node_modules/stylus/node_modules/cssom/lib/parse.js:263
                        throw "unexpected }";
      ^
unexpected }
```
### CSS

_bounce.css_

``` css
@-webkit-keyframes bounce {
  0%, 20%, 50%, 80%, 100% {-webkit-transform: translateY(0);}
  40% {-webkit-transform: translateY(-30px);}
  60% {-webkit-transform: translateY(-15px);}
}

@-moz-keyframes bounce {
  0%, 20%, 50%, 80%, 100% {-moz-transform: translateY(0);}
  40% {-moz-transform: translateY(-30px);}
  60% {-moz-transform: translateY(-15px);}
}

@-ms-keyframes bounce {
  0%, 20%, 50%, 80%, 100% {-ms-transform: translateY(0);}
  40% {-ms-transform: translateY(-30px);}
  60% {-ms-transform: translateY(-15px);}
}

@-o-keyframes bounce {
  0%, 20%, 50%, 80%, 100% {-o-transform: translateY(0);}
  40% {-o-transform: translateY(-30px);}
  60% {-o-transform: translateY(-15px);}
}
@keyframes bounce {
  0%, 20%, 50%, 80%, 100% {transform: translateY(0);}
  40% {transform: translateY(-30px);}
  60% {transform: translateY(-15px);}
}

.bounce {
  -webkit-animation-name: bounce;
  -moz-animation-name: bounce;
  -ms-animation-name: bounce;
  -o-animation-name: bounce;
  animation-name: bounce;
}
```
### Information

```
stylus --version
0.22.5

node --version
v0.6.6
```
