### ISSUE TITLE
Mixin variables not declared inside @font-face

### ISSUE THREAD

**Issue by walling** [stylus/stylus#578]
The following code does not work as I expected:

``` stylus
test()
  name = "My Font"

  @font-face
    font-family name
    src url(name + ".ttf")

test()
```

Expected:

``` css
@font-face {
  font-family: "My Font";
  src: url("My Font.ttf");
}
```

Actual output:

``` css
@font-face {
  font-family: name;
  src: url("name.ttf");
}
```

This is (probably) unrelated to issue #396 as it works for me: All argument variables are accessible inside @font-face. Just non-argument variables declared outside the @font-face scope is not accessible. Maybe it is related to issue #269.
