### ISSUE TITLE
Evaluating quoted "{i}" variable

### ISSUE THREAD

**Issue by zanona** [stylus/stylus#600]
Attribute selectors and few properties require quotes sometimes as the case bellow. It seems I can't get these values quoted?
I've noticed the `unquote` function in stylus but not the opposite method?

``` css
.test {
  i = "red";
  &[title="{i}"]:before {
    content: i;
  } 
  for j in 1..2 {
    &[title="{j}"]:before {
      content: j;
    }
  }
}
```

compiles to:

``` css
.test[title="{i}"]:before {
  content: "red";
}
.test[title="{j}"]:before {
  content: 1;
}
.test[title="{j}"]:before {
  content: 2;
}
```

Also please notice that the value for  the `content` attribute also must be quoted but `"{x}"` in that cases won't evaluate as well.
