### ISSUE TITLE
Placeholder selectors in Stylus

### ISSUE THREAD

**Issue by scottkellum** [stylus/stylus#617]
Sass implemented placeholder selectors that render only when extended. Would be nice to see this in Stylus as well.

ex:

``` sass
%foo
  width: 100px

%bar
  height: 100px

.baz
  @extend %foo
```

compiles to:

``` css
.baz {
  width: 100px;
}
```
