### ISSUE TITLE
.define(url, function() {...}) is double quoting output

### ISSUE THREAD

**Issue by defunctzombie** [stylus/stylus#633]
The following no longer works in stylus 0.25.0

``` javascript
var stylus = require('stylus');

var styl = stylus('p { background: url("test.png"); }')
    .define('url', function() {
        return 'url("some/new/url.png");'
    });

styl.render(function(err, css) {
    console.log(css);
});
```

It produces the following invalid css:

``` css
p {
  background: 'url("some/new/url.png");';
}
```
