### ISSUE TITLE
unit expression precedence error

### ISSUE THREAD

**Issue by tj** [stylus/stylus#667]
```
body
  foo: foo bar (1)px
  foo: foo bar (2 * 5)px
  foo: foo (2 * 5)px bar
```

should not be

``` css

body {
  foo: foo bar 1 px;
  foo: foo bar 10 px;
  foo: foo 10 px bar;
}
```
