### ISSUE TITLE
mixin brace bug

### ISSUE THREAD

**Issue by geddski** [stylus/stylus#681]
this mixin compiles fine:

``` css
stretch(){
  position:absolute;
}
```

but when you add an if block like so:

``` css
stretch(top = 0){
  position:absolute;
  if top != false
    top: top;
}

```

it won't compile, giving this error: 

```
ParseError: styl/stretch.styl:5
   1| stretch(top = 0, right = 0, bottom = 0, left = 0){
   2|   position:absolute;
   3|   if top != false
   4|     top: top;
 > 5| }
   6| 

unexpected "}"
```

removing the mixin's optional braces `{}` makes it compile again:

```
stretch(top = 0, right = 0, bottom = 0, left = 0)
  position:absolute;
  if top != false
    top: top;
```

This is a bug, unless mixins are not intended to be able to use the optional braces, in which case it should probably fail every time braces are used with mixins.
