### ISSUE TITLE
Variable evaluation in mixins using `current-property` is order dependent

### ISSUE THREAD

**Issue by knuton** [stylus/stylus#702]
The output of 

```
replace(expr, str, val)
  expr = clone(expr)
  for e, i in expr
    if length(e) > 1
      expr[i] = replace(e, str, val)
    else
      if str == e
        expr[i] = val
  expr

b(x)
  prop = current-property[0]
  val = current-property[1]
  add-property(prop, replace(val, '__CALL__', unquote('alpha')))
  add-property(prop, replace(val, '__CALL__', unquote('beta')))
  unquote('gamma')

some-mixin($foo)
  // Only preceding variables are being evaluated when used inside mixin
  background: $foo, b($foo), $foo

$oof = blue

body
  // All variables are being evaluated when used outside of mixin
  background: $oof, b($oof), $oof

body
  some-mixin(red)
```

should be

``` css
body {
  background: #00f, alpha, #00f;
  background: #00f, beta, #00f;
  background: #00f, gamma, #00f;
}
body {
  background: #f00, alpha, #f00;
  background: #f00, beta, #f00;
  background: #f00, gamma, #f00;
}
```

but is

``` css
body {
  background: #00f, alpha, #00f;
  background: #00f, beta, #00f;
  background: #00f, gamma, #00f;
}
body {
  background: #f00, alpha, $foo;
  background: #f00, beta, $foo;
  background: #f00, gamma, #f00;
}
```

.

Interestingly, the issue only occurs when calling the mixin `b` from within another mixin.
