### ISSUE TITLE
testcase is wrong

### ISSUE THREAD

**Issue by sokra** [stylus/stylus#710]
https://github.com/LearnBoost/stylus/blob/master/test/cases/control.boilerplate.styl#L138

shouldn't compile to

https://github.com/LearnBoost/stylus/blob/master/test/cases/control.boilerplate.css#L289

Here are the snippets:

``` stylus
input:valid, textarea:valid   {  }
input:invalid, textarea:invalid {
   border-radius: 1px; -moz-box-shadow: 0px 0px 5px red; -webkit-box-shadow: 0px 0px 5px red; box-shadow: 0px 0px 5px red;
}
```

shouldn't compile to

``` css
input:valid,
textarea:valid,
input:invalid,
textarea:invalid {
  border-radius: 1px;
  -moz-box-shadow: 0px 0px 5px #f00;
  -webkit-box-shadow: 0px 0px 5px #f00;
  box-shadow: 0px 0px 5px #f00;
}
```

The testcase is wrong, and so stylus behaivior in this (rar) case
