### ISSUE TITLE
Stylus calls mixin that it should not call

### ISSUE THREAD

**Issue by saschagehlich** [stylus/stylus#729]
Hey,

this is my stylus file:

``` stylus
box-shadow-2(shadow_a, shadow_b)
  -webkit-box-shadow shadow_a, shadow_b
  -moz-box-shadow shadow_a, shadow_b
  -o-box-shadow shadow_a, shadow_b
  box-shadow shadow_a, shadow_b

box-shadow(shadow_a)
  -webkit-box-shadow shadow_a
  -moz-box-shadow shadow_a
  -o-box-shadow shadow_a
  box-shadow shadow_a

.box
  box-shadow-2(0 1px 0 rgba(255,255,255,.02) inset, 0 1px 0 red)
```

The rendered output looks like this:

``` css

.box {
  -webkit-box-shadow: 0 1px 0 rgba(255,255,255,0.02) inset, 0 1px 0 #f00;
  -moz-box-shadow: 0 1px 0 rgba(255,255,255,0.02) inset, 0 1px 0 #f00;
  -o-box-shadow: 0 1px 0 rgba(255,255,255,0.02) inset, 0 1px 0 #f00;
  -webkit-box-shadow: 0 1px 0 rgba(255,255,255,0.02) inset;
  -moz-box-shadow: 0 1px 0 rgba(255,255,255,0.02) inset;
  -o-box-shadow: 0 1px 0 rgba(255,255,255,0.02) inset;
  box-shadow: 0 1px 0 rgba(255,255,255,0.02) inset;
}
```

I guess you see the problem :)
