### ISSUE TITLE
Kwargs in CSS-Style mixin syntax?

### ISSUE THREAD

**Issue by lunelson** [stylus/stylus#734]
I like using CSS style formatting for most of my mixins, and was wondering if there's a syntax to supply kwargs in that format, and if so what is it? If it doesn't exist, then this is my +1 for it. 

``` css
.test {
    mixin: arg1=true, arg2=false;
}
```

The above was my best guess but that didn't seem to work...
