### ISSUE TITLE
Undefined variables return true in conditions

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#740]
As any undeclared variables return their ident, then it's impossible to tell was any given variable declared or not.

I propose that in boolean context such idents must return false if they were not declared.

So

```
foo = lol

.class
  a: foo if foo
  b: bar if bar
```

would render as

``` CSS
.class {
  a: lol;
}
```

but right now it renders as 

``` CSS
.class {
  a: lol;
  b: bar;
}
```
