### ISSUE TITLE
Parsing Issue If the brace starts in new line

### ISSUE THREAD

**Issue by ghost** [stylus/stylus#786]
Hi visonmedia, 
I am getting css parsing issue.
As of the project documentation stylus is supposed to support real world css.

My personal preferance is to write all colons and brace and brace on new line  when i write the brace in new line the parser returns unexpected reasults
This is my code

``` css
body
{
    color: green;
    background: #FFF;
    h1
    {
        text-transform: uppercase;
    }
}
```

The above code outputs

``` css

body,
 {
  color: #008000;
  background: #fff;
}
body h1,
 h1,
body,
 {
  text-transform: uppercase;
}

```

Isn't  that bit scary....

but when i write the code with one space and brace it works

``` css
body {
    color: green;
    background: #FFF;
    h1 {
        text-transform: uppercase;
    }
}

```

It works

``` css

body {
  color: #008000;
  background: #fff;
}
body h1 {
  text-transform: uppercase;
}

```

I think stylus should determine the block even if it starts in new line or after hundred lines ???
I think indention based coding is not best thats why sass moved to scss...
I love stylus and love it's transparent mixins .
But these type of errors bump my head.

Sorry if I didn't explain it enough :)
Thanks in advance ...
