### ISSUE TITLE
inline comments break with class declarations

### ISSUE THREAD

**Issue by ghost** [stylus/stylus#810]
Hi, consider the follwoing stylus code and its css output

``` css
a // commant
    atr def
a.class // comment
    atr def
```

``` css
a {
  atr: def;
}
a.class // comment {
  atr: def;
}
```

The latter will break as the comment should not go before the bracket
