### ISSUE TITLE
Extends in ampersand selector generating multiple selectors

### ISSUE THREAD

**Issue by OliverJAsh** [stylus/stylus#819]
Take this code:

``` styl
.l-nav-list-2-item-border
  @extend .divider-3

.l-nav-list-2
  &,
  > li
    @extend .l-nav-list-2-item-border
```

It generates this:

``` css
.divider-3,
.l-nav-list-2-item-border,
.l-nav-list-2,
.l-nav-list-2 > li,
.l-nav-list-2,
.l-nav-list-2 > li {
  background-image: url("/resource/images/divider-dotted.gif");
  background-position: 0 0;
  background-repeat: repeat-x;
  padding-top: 1px;
}
```

It seems that, because I am using this selector:

``` styl
.l-nav-list-2
  &,
  > li
```

… Stylus generates multiple selectors for `l-nav-list-2` and `.l-nav-list-2 > li` in the extend.

If I change my code to this:

``` styl
.l-nav-list-2
  @extend .l-nav-list-2-item-border

  > li
    @extend .l-nav-list-2-item-border
```

Then my output is correct:

``` css
.divider-3,
.l-nav-list-2-item-border,
.l-nav-list-2,
.l-nav-list-2 > li {
  background-image: url("/resource/images/divider-dotted.gif");
  background-position: 0 0;
  background-repeat: repeat-x;
  padding-top: 1px;
}
```
