### ISSUE TITLE
Sass-style Sub-Properties Shorthand

### ISSUE THREAD

**Issue by jamiebuilds** [stylus/stylus#848]
As you may know one of sass's many features is the ability to do the following:
#### SCSS

``` scss
#foo {
    font: {
        family: Helvetica, Arial, sans-serif;
        size: 1em;
        weight: 300;
    }
}
```
#### SASS

``` sass
#foo
    font:
        family: Helvetica, Arial, sans-serif
        size: 1em
        weight: 300
```

---
### I think it's time for stylus to re-imagine this

---
## 1. `FAIL` – No Additional Chars

``` sass
#foo
    font
        family Helvetica, Arial, sans-serif
        size 1em
        weight 300
```

If Stylus were to take this route, then it would limit the properties it could be applied to because it would have to be enabled for each property manually. It would also take up the name space. Every way I can think of how to implement this, it would be a complication and confusion.
## 2. `BETTER` – Using `-` before each sub-property

``` sass
#foo
    font
        -family Helvetica, Arial, sans-serif
        -size 1em
        -weight 300
```

However to use multiple properties you would have to use a `-` before each and on top of that it would lead to errors if there were properties that didn't have a `-`
## 3. `BEST` – Using `:` after parent property

``` sass
#foo
    font:
        family Helvetica, Arial, sans-serif
        size 1em
        weight 300
```

This is most like the sass notation and like most of stylus is very forgiving while processing. I think that this is the best option by far. 

It could also work in this format (identical to SCSS) 

``` scss
#foo {
    font: {
        family: Helvetica, Arial, sans-serif;
        size: 1em;
        weight: 300;
    }
}
```

This simple way of doing it opens up a world of possibilities, such as:

``` sass
#foo
    -webkit:
        box-shadow 0 1px 3px rgba(0, 0, 0, .15)
        transition background .1s linear
```
##### Or, cause why the hell not:

``` sass
#foo
    -webkit:,
    -moz:,
    : 
       box-shadow 0 1px 3px rgba(0, 0, 0, .15)
       transition background .1s linear
```
