### ISSUE TITLE
Bug when using multiple nested interpolations 

### ISSUE THREAD

**Issue by feross** [stylus/stylus#871]
The following Stylus:

``` css
$link = '&:link, &:visited'
$focus = '&:hover, &:focus, &:active'

#nav
  float: left

  a
    {$link}
      text-decoration: none

  & > li
    margin-bottom: 30px

    {$focus} > a
      {$link}
        border-bottom: 1px solid $red
```

produces this CSS:

``` css
#nav {
  float: left;
}
#nav a:link, #nav a:visited {
  text-decoration: none;
}
#nav > li {
  margin-bottom: 30px;
}
#nav > li:hover, #nav > li:focus, #nav > li:active > a:link, #nav > li:hover, #nav > li:focus, #nav > li:active > a:visited {
  border-bottom: 1px solid red;
}
```

when it should produce this CSS:

``` css
#nav {
  float: left;
}
#nav a:link, #nav a:visited {
  text-decoration: none;
}
#nav > li {
  margin-bottom: 30px;
}
#nav > li:hover > a:link, #nav > li:focus > a:link, #nav > li:active > a:link, #nav > li:hover  > a:visited, #nav > li:focus  > a:visited, #nav > li:active > a:visited {
  border-bottom: 1px solid red;
}
```

Note the difference in the last CSS block. This looks like a bug to me, but I could be using this wrong.

Thoughts?
