### ISSUE TITLE
Converting css to stylus miss line 

### ISSUE THREAD

**Issue by fossilet** [stylus/stylus#885]
I use stylus version 0.29.0.

I have a css file called `test.css`:

``` css
a.button {
    background-image: -moz-linear-gradient(center bottom , #F2F2F2 21%, #F9F9F9 50%);
    background-image: -webkit-linear-gradient(#f2f2f2, #f9f9f9);
}
```

I use `stylus -C test.css` to convert it to stylus, the output file `test.styl` is:

``` css
a.button
  background-image: -webkit-linear-gradient(#f2f2f2, #f9f9f9)
```

The first line for Mozilla is missing.

In real project, it is hard to find. Is it unsafe to convert css to stylus?
