### ISSUE TITLE
Error working with for..in and @extends

### ISSUE THREAD

**Issue by Karmac** [stylus/stylus#953]
I have the following code, but somehow the @extends method doesn't work.

``` css
.grid
    margin auto ($column_gutter / 2)

for num in 1..$column_number

    .grid-{num}
        @extends .grid
        width $column_width * num + $column_gutter * (num - 1)
```

Here's the CSS I get:

``` css
.grid {
  margin: auto 10px;
}
.grid-1 {
  width: 60px;
}
.grid-2 {
  width: 140px;
}
.grid-3 {
  width: 220px;
}
.grid-4 {
  width: 300px;
}
.grid-5 {
  width: 380px;
}
.grid-6 {
  width: 460px;
}
.grid-7 {
  width: 540px;
}
.grid-8 {
  width: 620px;
}
.grid-9 {
  width: 700px;
}
.grid-10 {
  width: 780px;
}
.grid-11 {
  width: 860px;
}
.grid-12 {
  width: 940px;
}
```

What am I doing wrong? Could be a bug? Thanks.
