### ISSUE TITLE
CSS braces on new line breaks rule

### ISSUE THREAD

**Issue by davetayls** [stylus/stylus#958]
When the braces for a rule begin on a new line a comma is inserted

Stylus

``` css
.foo
{
  background red;
}
```

outputs

``` css
.foo,
 {
  background: #f00;
}
```

It's not my preferred format but some IDEs of people on my team format CSS/Stylus this way grrr
