### ISSUE TITLE
tab-size not working

### ISSUE THREAD

**Issue by Karmac** [stylus/stylus#990]
I tried to use the `tab-size` property in my files but somehow it doesn't work.

Here's my code:

```
pre
    padding 1em 1.5em
    margin 2em 0
    white-space pre-wrap
    word-wrap break-word
    tab-size 4
```

and I get the following:

``` css
pre {
    padding: 1em 1.5em;
    margin: 2em 0;
    white-space: pre-wrap;
    word-wrap: break-word;
}
```

Thanks for your help.
